[CmdletBinding()]
param([switch]$SkipMigration)

$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$script:passed=0
$utf8NoBom=New-Object Text.UTF8Encoding($false)

function Assert-True([bool]$Condition,[string]$Name){if(-not $Condition){throw "ASSERT_FAIL|$Name"};$script:passed++;Write-Output "PASS|$Name"}
function Write-Text([string]$Path,[string]$Text){$parent=Split-Path -Parent $Path;if($parent -and -not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$v=$Text.Replace("`r`n","`n").Replace("`r","`n");if(-not $v.EndsWith("`n")){$v+="`n"};[IO.File]::WriteAllText($Path,$v,$utf8NoBom)}
function Write-Json([string]$Path,$Object){Write-Text $Path ($Object|ConvertTo-Json -Depth 40)}
function Get-Identity([string]$Path){$f=Get-Item -LiteralPath $Path;return $f.Length.ToString()+'|'+(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash}
function Invoke-Child([string]$Script,[string[]]$Arguments,[string]$WorkingDirectory){Push-Location $WorkingDirectory;$previous=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$out=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script @Arguments 2>&1|ForEach-Object{[string]$_});$code=$LASTEXITCODE}finally{$ErrorActionPreference=$previous;Pop-Location};return [pscustomobject]@{Code=$code;Text=($out-join"`n");Lines=$out}}
function Clone-Object($Object){return ($Object|ConvertTo-Json -Depth 40|ConvertFrom-Json)}
function Initialize-GitFixture([string]$Path){if(-not(Test-Path -LiteralPath $Path)){New-Item -ItemType Directory -Path $Path -Force|Out-Null};$out=@(& git -C $Path init --quiet 2>&1);if($LASTEXITCODE-ne0){throw "GIT_FIXTURE_INIT_FAILED|$Path|$($out-join' ')"}}
function Get-BindingDigest($Binding){$core=[ordered]@{schemaVersion=$Binding.schemaVersion;taskId=$Binding.taskId;taskLocator=$Binding.taskLocator;taskIdentity=$Binding.taskIdentity;resourceRequirementIdentity=$Binding.resourceRequirementIdentity;adapterPolicyLocator=$Binding.adapterPolicyLocator;adapterPolicyIdentity=$Binding.adapterPolicyIdentity;actualCapabilitySet=$Binding.actualCapabilitySet;selectedQuality=$Binding.selectedQuality;selectedTools=@($Binding.selectedTools);continuity=$Binding.continuity;phase=$Binding.phase;host=$Binding.host;contextIdentity=$Binding.contextIdentity};$bytes=[Text.Encoding]::UTF8.GetBytes(($core|ConvertTo-Json -Compress -Depth 20));$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','')}finally{$sha.Dispose()}}

$candidateRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$draftRoot=Split-Path -Parent $candidateRoot
$leanRootScripts=Join-Path $draftRoot 'lean-root-scripts'
$frameworkRoot=Split-Path -Parent (Split-Path -Parent $draftRoot)
$workspaceRoot=Split-Path -Parent $frameworkRoot
$scriptsRoot=Join-Path $candidateRoot 'scripts'
$remoteChecker=Join-Path $scriptsRoot 'check-remote-batch.ps1'
$resourceResolver=Join-Path $scriptsRoot 'resolve-resource-binding.ps1'
$authorizationChecker=Join-Path $scriptsRoot 'check-authorization.ps1'
$taskChecker=Join-Path $scriptsRoot 'check-task-card.ps1'
$routeChecker=Join-Path $scriptsRoot 'check-controller-route.ps1'
$protectedGit=Join-Path $scriptsRoot 'invoke-protected-safe-git.ps1'

$version=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $candidateRoot 'VERSION.json')|ConvertFrom-Json
Assert-True ([string]$version.version-ceq'1.6.0'-and[string]$version.lifecycle-ceq'DRAFT'-and-not[bool]$version.consumable-and-not[bool]$version.projectPinEligible) 'draft-not-consumable'
$manifest=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $candidateRoot 'LOAD_MANIFEST.json')|ConvertFrom-Json
Assert-True ([string]$manifest.frameworkVersion-ceq'1.6.0'-and[string]$manifest.lifecycle-ceq'DRAFT') 'load-manifest-draft'

$expectedNew=@('CONTROLLER_SCHEMA.json','PROJECT_CONFIG_SCHEMA.json','REMOTE_BATCH_SCHEMA.json','project-starter/controller.json','scripts/check-controller-route.ps1','scripts/check-remote-batch.ps1','scripts/invoke-protected-safe-git.ps1','scripts/resolve-resource-binding.ps1')
$stableRoot=Join-Path $frameworkRoot 'versions\1.5.2'
$stableFiles=@(Get-ChildItem -LiteralPath $stableRoot -Recurse -File|ForEach-Object{$_.FullName.Substring($stableRoot.Length+1).Replace('\','/')})
$expected=@($stableFiles+$expectedNew|Sort-Object -Unique)
$actual=@(Get-ChildItem -LiteralPath $candidateRoot -Recurse -File|ForEach-Object{$_.FullName.Substring($candidateRoot.Length+1).Replace('\','/')}|Sort-Object -Unique)
Assert-True ($expected.Count-eq40-and@(Compare-Object $expected $actual -CaseSensitive).Count-eq0) 'lean-inventory-exact40'
Assert-True ((Test-Path -LiteralPath (Join-Path $leanRootScripts 'register-project.ps1'))-and(Test-Path -LiteralPath (Join-Path $leanRootScripts 'upgrade-project.ps1'))) 'lean-root-exact2'
$releaseManifestPath=Join-Path $candidateRoot 'RELEASE_MANIFEST.json'
$releaseManifest=Get-Content -Raw -Encoding utf8 -LiteralPath $releaseManifestPath|ConvertFrom-Json
$releaseLines=New-Object 'System.Collections.Generic.List[string]';$releaseTotal=0
foreach($file in Get-ChildItem -LiteralPath $candidateRoot -Recurse -File){if($file.FullName-ceq$releaseManifestPath){continue};$relative=$file.FullName.Substring($candidateRoot.Length+1).Replace('\','/');$bytes=[IO.File]::ReadAllBytes($file.FullName);$releaseLines.Add("$relative|$($bytes.Length)|$((Get-FileHash -Algorithm SHA256 -LiteralPath $file.FullName).Hash.ToUpperInvariant())");$releaseTotal+=$bytes.Length}
$releaseLines.Sort([StringComparer]::Ordinal);$releasePayload=[Text.Encoding]::UTF8.GetBytes(($releaseLines-join"`n"));$releaseHasher=[Security.Cryptography.SHA256]::Create();try{$releaseHash=$releaseHasher.ComputeHash($releasePayload);$releaseCanonical=-join($releaseHash|ForEach-Object{$_.ToString('X2')})}finally{$releaseHasher.Dispose()}
Assert-True ([int]$releaseManifest.fileCount-eq$releaseLines.Count-and[int64]$releaseManifest.totalBytes-eq$releaseTotal-and[string]$releaseManifest.canonical-ceq$releaseCanonical) 'release-manifest-canonical'

$strictIssues=@()
foreach($file in Get-ChildItem -LiteralPath $candidateRoot -Recurse -File){$bytes=[IO.File]::ReadAllBytes($file.FullName);$text=$null;try{$text=(New-Object Text.UTF8Encoding($false,$true)).GetString($bytes)}catch{$strictIssues+=$file.FullName;continue};if(($bytes.Length-ge3-and$bytes[0]-eq0xEF-and$bytes[1]-eq0xBB-and$bytes[2]-eq0xBF)-or$text.Contains("`r")-or$text.Contains([char]0)-or$text.Contains([char]0xFFFD)-or-not$text.EndsWith("`n")){$strictIssues+=$file.FullName}}
Assert-True ($strictIssues.Count-eq0) 'strict-utf8-lf'
$jsonIssues=@();foreach($file in Get-ChildItem -LiteralPath $candidateRoot -Recurse -Filter '*.json' -File){if($file.FullName-like'*project-starter\project.json'-or$file.FullName-like'*project-starter\controller.json'){continue};try{$null=Get-Content -Raw -Encoding utf8 -LiteralPath $file.FullName|ConvertFrom-Json}catch{$jsonIssues+=$file.FullName}}
Assert-True ($jsonIssues.Count-eq0) 'json-parse'
$syntaxIssues=@();foreach($file in @((Get-ChildItem -LiteralPath $scriptsRoot -Filter '*.ps1' -File)+(Get-ChildItem -LiteralPath $leanRootScripts -Filter '*.ps1' -File)+(Get-ChildItem -LiteralPath $PSScriptRoot -Filter '*.ps1' -File))){$t=$null;$e=$null;[void][Management.Automation.Language.Parser]::ParseFile($file.FullName,[ref]$t,[ref]$e);if($e.Count){$syntaxIssues+=$file.FullName}}
Assert-True ($syntaxIssues.Count-eq0) 'powershell-syntax'
$consumerFiles=@('LOAD_MANIFEST.json','RELEASE_MANIFEST.json','scripts/check-authorization.ps1','scripts/check-controller-route.ps1','scripts/check-remote-batch.ps1','scripts/check-task-card.ps1','scripts/invoke-protected-safe-git.ps1','scripts/resolve-load-plan.ps1','scripts/resolve-resource-binding.ps1')
$badConsumer=@();foreach($relative in $consumerFiles){$text=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $candidateRoot $relative);if($text-match'framework/drafts/1\.6\.0/(candidate|root-scripts)' -or $text-match'REMOTE_TRANSACTION_SCHEMA|check-remote-transaction'){$badConsumer+=$relative}}
Assert-True ($badConsumer.Count-eq0) 'old-tree-zero-consumer'
$taskTemplateText=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $candidateRoot 'TASK_TEMPLATE.md');Assert-True ($taskTemplateText.Contains('"resourceBindingLocator": ".tmp/resource-bindings/<TASK-ID>.resource-binding.json"')-and-not$taskTemplateText.Contains('"resourceBindingLocator": ".tmp/<TASK-ID>.resource-binding.json"')) 'resource-template-locator-compatible'

$tempRoot=Join-Path ([IO.Path]::GetTempPath()) ('aiw-160-lean-'+[Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $tempRoot|Out-Null
try{
    $headA='A'*40;$headB='B'*40;$fpA='C'*64;$fpB='D'*64;$candidateIdentity='10|'+('E'*64);$auth1='11|'+('F'*64);$configIdentity='12|'+('1'*64)
    $batch=[ordered]@{schemaVersion=1;kind='REMOTE_BATCH';batchId='batch-0001';projectId='project-a';taskId='TASK-A';candidateIdentity=$candidateIdentity;gitCloser='closer-1';authorizationLocator='.tmp/batch.auth.json';authorizationIdentity=$auth1;projectConfigIdentity=$configIdentity;remotes=@(
        [ordered]@{remoteId='origin';endpointFingerprint=$fpA;action='PUSH_REF';refspec='refs/heads/main:refs/heads/main';expectedLocalHead=$headA;expectedRemoteHead='ABSENT';attempted=$true;status='SUCCEEDED';observedRemoteHead=$headA;receipt='remote-receipt-001'},
        [ordered]@{remoteId='mirror';endpointFingerprint=$fpB;action='PUSH_REF';refspec='refs/heads/main:refs/heads/main';expectedLocalHead=$headA;expectedRemoteHead=$headB;attempted=$true;status='FAILED';observedRemoteHead=$headB;errorClass='REMOTE_REJECTED'} )}
    $batchPath=Join-Path $tempRoot 'batch.json';Write-Json $batchPath $batch
    $remoteObserved=@([ordered]@{remoteId='origin';endpointFingerprint=$fpA;refspec='refs/heads/main:refs/heads/main';localHead=$headA;remoteHead='ABSENT'},[ordered]@{remoteId='mirror';endpointFingerprint=$fpB;refspec='refs/heads/main:refs/heads/main';localHead=$headA;remoteHead=$headB});Write-Json (Join-Path $tempRoot 'observed.json') $remoteObserved
    $args=@('-BatchPath',$batchPath,'-ObservedCandidateIdentity',$candidateIdentity,'-ObservedGitCloser','closer-1','-ObservedAuthorizationLocator','.tmp/batch.auth.json','-ObservedAuthorizationIdentity',$auth1,'-ObservedProjectConfigIdentity',$configIdentity,'-ObservedRemotePath',(Join-Path $tempRoot 'observed.json'))
    $result=Invoke-Child $remoteChecker $args $tempRoot;if($result.Code-ne0){Write-Output ('TRACE|remote-batch-partial|'+$result.Text);Write-Output ('TRACE|observed|'+(Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $tempRoot 'observed.json')))};Assert-True ($result.Code-eq0-and$result.Text-like'*aggregate=PARTIAL*') 'remote-batch-partial'
    $driftObserved=Clone-Object $remoteObserved;$driftObserved[1].remoteHead='ABSENT';Write-Json (Join-Path $tempRoot 'observed-drift.json') $driftObserved;$driftArgs=$args.Clone();$driftArgs[$driftArgs.Count-1]=(Join-Path $tempRoot 'observed-drift.json');$result=Invoke-Child $remoteChecker $driftArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*REMOTE_HEAD_DRIFT*') 'remote-batch-head-drift'
    $oldDto=Clone-Object $batch;$oldDto|Add-Member -NotePropertyName PreviousLedger -NotePropertyValue 'legacy';Write-Json (Join-Path $tempRoot 'old.json') $oldDto;$oldArgs=$args.Clone();$oldArgs[1]=(Join-Path $tempRoot 'old.json');$result=Invoke-Child $remoteChecker $oldArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*TOP_UNKNOWN_PreviousLedger*') 'remote-old-dto-rejected'
    $danger=Clone-Object $batch;$danger.remotes[0].refspec='+refs/heads/main:refs/heads/main';Write-Json (Join-Path $tempRoot 'danger.json') $danger;$dangerArgs=$args.Clone();$dangerArgs[1]=(Join-Path $tempRoot 'danger.json');$result=Invoke-Child $remoteChecker $dangerArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*REFSPEC_REJECTED*') 'remote-force-rejected'
    $retry=Clone-Object $batch;$retry.batchId='batch-0002';$retry.authorizationIdentity='13|'+('2'*64);$retry.remotes=@($retry.remotes[1]);$retry.remotes[0].attempted=$false;$retry.remotes[0].status='PENDING';$retry.remotes[0].PSObject.Properties.Remove('observedRemoteHead');$retry.remotes[0].PSObject.Properties.Remove('errorClass');Write-Json (Join-Path $tempRoot 'retry.json') $retry
    $retryObserved=@([ordered]@{remoteId='mirror';endpointFingerprint=$fpB;refspec='refs/heads/main:refs/heads/main';localHead=$headA;remoteHead=$headB});Write-Json (Join-Path $tempRoot 'retry-observed.json') $retryObserved;$retryArgs=@('-BatchPath',(Join-Path $tempRoot 'retry.json'),'-ObservedCandidateIdentity',$candidateIdentity,'-ObservedGitCloser','closer-1','-ObservedAuthorizationLocator','.tmp/batch.auth.json','-ObservedAuthorizationIdentity',$retry.authorizationIdentity,'-ObservedProjectConfigIdentity',$configIdentity,'-ObservedRemotePath',(Join-Path $tempRoot 'retry-observed.json'));$result=Invoke-Child $remoteChecker $retryArgs $tempRoot;Assert-True ($result.Code-eq0-and$result.Text-like'*aggregate=PLANNED*'-and$retry.authorizationIdentity-cne$auth1) 'remote-fresh-retry-new-auth'

    $projectRoot=Join-Path $tempRoot 'protected-project';Initialize-GitFixture $projectRoot;New-Item -ItemType Directory -Path (Join-Path $projectRoot '.ai-workspace') -Force|Out-Null
    $projectConfig=[ordered]@{schemaVersion=3;id='protected-project';displayName='Protected';controlPlaneLayout='repo-local';repositoryRoot='..';frameworkVersion='1.6.0';protectedPaths=@([ordered]@{path='src/config/secret.js';deny=@('visibility','read','hash','diff','index','write')});frameworkCapabilities=[ordered]@{}}
    $projectConfigPath=Join-Path $projectRoot '.ai-workspace/project.json';Write-Json $projectConfigPath $projectConfig;$projectConfigId=Get-Identity $projectConfigPath
    $result=Invoke-Child $protectedGit @('-ProjectRoot',$projectRoot,'-Operation','STATUS','-AllowPath','src/core/a.js','-ExpectedProjectConfigIdentity',$projectConfigId,'-PlanOnly') $tempRoot;Assert-True ($result.Code-eq0-and$result.Text-like'*VERIFIED_PLAN*'-and$result.Text-notlike'*secret.js*') 'protected-plan-safe'
    $result=Invoke-Child $protectedGit @('-ProjectRoot',$projectRoot,'-Operation','DIFF','-AllowPath','src','-ExpectedProjectConfigIdentity',$projectConfigId,'-PlanOnly') $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*PROTECTED_OVERLAP*'-and$result.Text-notlike'*secret.js*') 'protected-overlap-unverified-no-leak'
    $projectConfig.protectedPaths[0].deny=@('hash');Write-Json $projectConfigPath $projectConfig;$partialConfigId=Get-Identity $projectConfigPath;$result=Invoke-Child $protectedGit @('-ProjectRoot',$projectRoot,'-Operation','STATUS','-AllowPath','src','-ExpectedProjectConfigIdentity',$partialConfigId,'-PlanOnly') $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*PROTECTED_OVERLAP*'-and$result.Text-notlike'*secret.js*') 'protected-partial-deny-excluded'
    $nestedRoot=Join-Path $projectRoot 'nested';New-Item -ItemType Directory -Path (Join-Path $nestedRoot '.ai-workspace') -Force|Out-Null;Write-Json (Join-Path $nestedRoot '.ai-workspace/project.json') $projectConfig;$nestedConfigId=Get-Identity (Join-Path $nestedRoot '.ai-workspace/project.json');$result=Invoke-Child $protectedGit @('-ProjectRoot',$nestedRoot,'-Operation','STATUS','-AllowPath','src/core/a.js','-ExpectedProjectConfigIdentity',$nestedConfigId,'-PlanOnly') $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*GIT_TOPLEVEL_MISMATCH*') 'protected-nested-root-rejected'
    $result=Invoke-Child $protectedGit @('-ProjectRoot',$projectRoot,'-Operation','INDEX','-AllowPath','src/core/a.js','-ExpectedProjectConfigIdentity',('1|'+('0'*64)),'-PlanOnly') $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*CONFIG_IDENTITY_DRIFT*') 'protected-config-drift'

    Write-Text (Join-Path $tempRoot 'task.md') "# AUTH-TASK - fixture`n`n- Task schema: 1.6.0`n- Owner: owner-1`n- Resource requirement: DEFAULT`n- Range summary: profile=STANDARD; lifecycle=ACTIVE; expected_paths=[target.txt]; actual_paths=[target.txt]`n"
    Write-Json (Join-Path $tempRoot 'policy.json') ([ordered]@{schemaVersion=1;policyId='policy-1';host='CODEX';qualityOrder=@('MECHANICAL_LOW','ROUTINE_BALANCED','FOCUSED_HIGH','OWNER_FRONTIER')})
    Write-Json (Join-Path $tempRoot 'capability.json') ([ordered]@{schemaVersion=1;host='CODEX';qualities=@('ROUTINE_BALANCED','FOCUSED_HIGH','OWNER_FRONTIER');tools=@('browser','shell')})
    $policyId=Get-Identity (Join-Path $tempRoot 'policy.json');$capId=Get-Identity (Join-Path $tempRoot 'capability.json');$context='4|'+('3'*64)
    $resourceArgs=@('-TaskPath','task.md','-TaskId','AUTH-TASK','-AdapterPolicyPath','policy.json','-ExpectedAdapterPolicyIdentity',$policyId,'-CapabilityPath','capability.json','-ExpectedCapabilityIdentity',$capId,'-SelectedQuality','ROUTINE_BALANCED','-ContextMode','ANY','-HostName','CODEX','-Phase','IMPLEMENT','-ContextIdentity',$context,'-OutputPath','.tmp/resource-bindings/binding.json')
    $result=Invoke-Child $resourceResolver $resourceArgs $tempRoot;if($result.Code-ne0){Write-Output ('TRACE|resource-default|'+$result.Text)};Assert-True ($result.Code-eq0-and$result.Text-like'PASS|binding=*') 'resource-default-pass'
    $resolverTaskMismatchArgs=$resourceArgs.Clone();$resolverTaskMismatchArgs[[Array]::IndexOf($resolverTaskMismatchArgs,'AUTH-TASK')]='OTHER-TASK';$resolverTaskMismatchArgs[$resolverTaskMismatchArgs.Count-1]='.tmp/resource-bindings/task-id-mismatch.json';$result=Invoke-Child $resourceResolver $resolverTaskMismatchArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*Task ID does not match TaskPath*'-and-not(Test-Path -LiteralPath (Join-Path $tempRoot '.tmp/resource-bindings/task-id-mismatch.json'))) 'resource-resolver-task-id-mismatch-rejected'
    $bindingPath=Join-Path $tempRoot '.tmp/resource-bindings/binding.json';$bindingId=Get-Identity $bindingPath;$binding=Get-Content -Raw -Encoding utf8 -LiteralPath $bindingPath|ConvertFrom-Json
    $result=Invoke-Child $resourceResolver $resourceArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*must be fresh*') 'resource-existing-output-rejected'
    $absoluteArgs=$resourceArgs.Clone();$absoluteArgs[$absoluteArgs.Count-1]=(Join-Path $tempRoot 'absolute-binding.json');$result=Invoke-Child $resourceResolver $absoluteArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*locator is invalid*') 'resource-absolute-output-rejected'
    Write-Text (Join-Path $tempRoot '.tmp/resource-bindings/collision.json') "# AUTH-TASK - fixture`n`n- Task schema: 1.6.0`n- Owner: owner-1`n- Resource requirement: DEFAULT`n- Range summary: profile=STANDARD; lifecycle=ACTIVE; expected_paths=[target.txt]; actual_paths=[target.txt]`n"
    $inputCollisionArgs=$resourceArgs.Clone();$inputCollisionArgs[[Array]::IndexOf($inputCollisionArgs,'task.md')]='.tmp/resource-bindings/collision.json';$inputCollisionArgs[$inputCollisionArgs.Count-1]='.tmp/resource-bindings/collision.json';$result=Invoke-Child $resourceResolver $inputCollisionArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*collides with an input*') 'resource-input-output-collision-rejected'
    $resourceReparseRoot=Join-Path $tempRoot 'resource-reparse';New-Item -ItemType Directory -Path (Join-Path $resourceReparseRoot '.tmp') -Force|Out-Null;Copy-Item -LiteralPath (Join-Path $tempRoot 'task.md') -Destination (Join-Path $resourceReparseRoot 'task.md');Copy-Item -LiteralPath (Join-Path $tempRoot 'policy.json') -Destination (Join-Path $resourceReparseRoot 'policy.json');Copy-Item -LiteralPath (Join-Path $tempRoot 'capability.json') -Destination (Join-Path $resourceReparseRoot 'capability.json');$resourceReparseTarget=Join-Path $tempRoot 'resource-reparse-target';New-Item -ItemType Directory -Path $resourceReparseTarget -Force|Out-Null;New-Item -ItemType Junction -Path (Join-Path $resourceReparseRoot '.tmp/resource-bindings') -Target $resourceReparseTarget|Out-Null;$reparseArgs=$resourceArgs.Clone();$reparseArgs[$reparseArgs.Count-1]='.tmp/resource-bindings/reparse.json';$result=Invoke-Child $resourceResolver $reparseArgs $resourceReparseRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*reparse point*') 'resource-output-reparse-rejected'
    Write-Text (Join-Path $tempRoot 'exception-task.md') "# RESOURCE-EXCEPTION - fixture`n`n- Task schema: 1.6.0`n- Owner: owner-1`n- Resource requirement: {`"minimumQuality`":`"FOCUSED_HIGH`",`"requiredTools`":[`"browser`"],`"continuity`":`"FRESH`"}`n- Range summary: profile=STANDARD; lifecycle=ACTIVE; expected_paths=[target.txt]; actual_paths=[target.txt]`n"
    $exceptionArgs=@('-TaskPath','exception-task.md','-TaskId','RESOURCE-EXCEPTION','-AdapterPolicyPath','policy.json','-ExpectedAdapterPolicyIdentity',$policyId,'-CapabilityPath','capability.json','-ExpectedCapabilityIdentity',$capId,'-SelectedQuality','FOCUSED_HIGH','-SelectedTool','browser','-ContextMode','FRESH','-HostName','CODEX','-Phase','REVIEW','-ContextIdentity',$context,'-OutputPath','.tmp/resource-bindings/exception-binding.json')
    $result=Invoke-Child $resourceResolver $exceptionArgs $tempRoot;Assert-True ($result.Code-eq0) 'resource-exception-tool-fresh-pass';$exceptionBindingPath=Join-Path $tempRoot '.tmp/resource-bindings/exception-binding.json';$exceptionBinding=Get-Content -Raw -Encoding utf8 -LiteralPath $exceptionBindingPath|ConvertFrom-Json
    $lowArgs=$exceptionArgs.Clone();$lowArgs[[Array]::IndexOf($lowArgs,'FOCUSED_HIGH')]='ROUTINE_BALANCED';$result=Invoke-Child $resourceResolver $lowArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*Silent quality downgrade*') 'resource-no-silent-downgrade'
    $missingToolArgs=@('-TaskPath','exception-task.md','-TaskId','RESOURCE-EXCEPTION','-AdapterPolicyPath','policy.json','-ExpectedAdapterPolicyIdentity',$policyId,'-CapabilityPath','capability.json','-ExpectedCapabilityIdentity',$capId,'-SelectedQuality','FOCUSED_HIGH','-ContextMode','FRESH','-HostName','CODEX','-Phase','REVIEW','-ContextIdentity',$context,'-OutputPath','.tmp/resource-bindings/missing-tool-binding.json');$result=Invoke-Child $resourceResolver $missingToolArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*Required tool*') 'resource-required-tool-missing'
    $phaseArgs=$exceptionArgs.Clone();$phaseArgs[[Array]::IndexOf($phaseArgs,'REVIEW')]='VERIFY';$phaseArgs[$phaseArgs.Count-1]='.tmp/resource-bindings/phase-binding.json';$result=Invoke-Child $resourceResolver $phaseArgs $tempRoot;$phaseBinding=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $tempRoot '.tmp/resource-bindings/phase-binding.json')|ConvertFrom-Json;Assert-True ($result.Code-eq0-and[string]$phaseBinding.bindingDigest-cne[string]$exceptionBinding.bindingDigest) 'resource-phase-invalidates-binding'
    Write-Text (Join-Path $tempRoot 'target.txt') "target`n";$targetId=Get-Identity (Join-Path $tempRoot 'target.txt')
    $auth=[ordered]@{schemaVersion=1;frameworkVersion='1.6.0';taskId='AUTH-TASK';profile='STANDARD';lifecycle='ACTIVE';owner='owner-1';issuer='owner-1';issuerRole='DOMAIN_OWNER';grantee='executor-1';bundle='IMPLEMENT_LOCAL';decisionClass='ROUTINE_LOCAL';userConfirmation='NOT_REQUIRED';reviewIndependence='NOT_APPLICABLE';delegatedGitCloser=$false;actions=@('SOURCE_WRITE');resourceBindingLocator='.tmp/resource-bindings/binding.json';resourceBindingIdentity=$bindingId;resourceBindingDigest=[string]$binding.bindingDigest;exactPaths=@('target.txt');objectIdentities=@([ordered]@{path='target.txt';identity=$targetId});invalidatesOn=@('TASK_CHANGE','OWNER_CHANGE','GRANTEE_CHANGE','ACTION_CHANGE','PATHSET_CHANGE','OBJECT_DRIFT','USER_DECISION_CHANGE','RESOURCE_BINDING_CHANGE')}
    Write-Json (Join-Path $tempRoot 'auth.json') $auth
    $authArgs=@('-PackagePath','auth.json','-ObservedActor','executor-1','-ObservedTaskId','AUTH-TASK','-ObservedOwner','owner-1','-ObservedAction','SOURCE_WRITE','-ObservedPath','target.txt','-ObservedIdentity',("target.txt=$targetId"),'-ResourceBindingPath','.tmp/resource-bindings/binding.json','-ResourceTaskPath','task.md','-ResourceAdapterPolicyPath','policy.json','-ResourceCapabilityPath','capability.json','-ObservedPhase','IMPLEMENT','-ObservedHost','CODEX','-ObservedContextIdentity',$context)
    $result=Invoke-Child $authorizationChecker $authArgs $tempRoot;Assert-True ($result.Code-eq0-and$result.Text-like'PASS|*') 'authorization-domain-resource-pass'
    Write-Text (Join-Path $tempRoot 'decoy-task-id.md') "# OTHER-TASK - decoy`n`n- Task schema: 1.6.0`n- Owner: owner-1`n- Resource requirement: DEFAULT`n- Range summary: profile=STANDARD; lifecycle=ACTIVE; expected_paths=[target.txt]; actual_paths=[target.txt]`n";$forgedTaskIdBinding=Clone-Object $binding;$forgedTaskIdBinding.taskLocator='decoy-task-id.md';$forgedTaskIdBinding.taskIdentity=Get-Identity (Join-Path $tempRoot 'decoy-task-id.md');$forgedTaskIdBinding.bindingDigest=Get-BindingDigest $forgedTaskIdBinding;$forgedTaskIdBindingPath=Join-Path $tempRoot '.tmp/resource-bindings/forged-task-id.json';Write-Json $forgedTaskIdBindingPath $forgedTaskIdBinding;$forgedTaskIdAuth=Clone-Object $auth;$forgedTaskIdAuth.resourceBindingLocator='.tmp/resource-bindings/forged-task-id.json';$forgedTaskIdAuth.resourceBindingIdentity=Get-Identity $forgedTaskIdBindingPath;$forgedTaskIdAuth.resourceBindingDigest=[string]$forgedTaskIdBinding.bindingDigest;Write-Json (Join-Path $tempRoot 'forged-task-id-auth.json') $forgedTaskIdAuth;$forgedTaskIdArgs=@('-PackagePath','forged-task-id-auth.json','-ObservedActor','executor-1','-ObservedTaskId','AUTH-TASK','-ObservedOwner','owner-1','-ObservedAction','SOURCE_WRITE','-ObservedPath','target.txt','-ObservedIdentity',("target.txt=$targetId"),'-ResourceBindingPath','.tmp/resource-bindings/forged-task-id.json','-ResourceTaskPath','decoy-task-id.md','-ResourceAdapterPolicyPath','policy.json','-ResourceCapabilityPath','capability.json','-ObservedPhase','IMPLEMENT','-ObservedHost','CODEX','-ObservedContextIdentity',$context);$result=Invoke-Child $authorizationChecker $forgedTaskIdArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*RESOURCE_TASK_ID_MISMATCH*') 'authorization-resource-task-id-mismatch-rejected'
    Write-Text (Join-Path $tempRoot 'decoy-owner.md') "# AUTH-TASK - decoy`n`n- Task schema: 1.6.0`n- Owner: owner-2`n- Resource requirement: DEFAULT`n- Range summary: profile=STANDARD; lifecycle=ACTIVE; expected_paths=[target.txt]; actual_paths=[target.txt]`n";$forgedOwnerBinding=Clone-Object $binding;$forgedOwnerBinding.taskLocator='decoy-owner.md';$forgedOwnerBinding.taskIdentity=Get-Identity (Join-Path $tempRoot 'decoy-owner.md');$forgedOwnerBinding.bindingDigest=Get-BindingDigest $forgedOwnerBinding;$forgedOwnerBindingPath=Join-Path $tempRoot '.tmp/resource-bindings/forged-owner.json';Write-Json $forgedOwnerBindingPath $forgedOwnerBinding;$forgedOwnerAuth=Clone-Object $auth;$forgedOwnerAuth.resourceBindingLocator='.tmp/resource-bindings/forged-owner.json';$forgedOwnerAuth.resourceBindingIdentity=Get-Identity $forgedOwnerBindingPath;$forgedOwnerAuth.resourceBindingDigest=[string]$forgedOwnerBinding.bindingDigest;Write-Json (Join-Path $tempRoot 'forged-owner-auth.json') $forgedOwnerAuth;$forgedOwnerArgs=@('-PackagePath','forged-owner-auth.json','-ObservedActor','executor-1','-ObservedTaskId','AUTH-TASK','-ObservedOwner','owner-1','-ObservedAction','SOURCE_WRITE','-ObservedPath','target.txt','-ObservedIdentity',("target.txt=$targetId"),'-ResourceBindingPath','.tmp/resource-bindings/forged-owner.json','-ResourceTaskPath','decoy-owner.md','-ResourceAdapterPolicyPath','policy.json','-ResourceCapabilityPath','capability.json','-ObservedPhase','IMPLEMENT','-ObservedHost','CODEX','-ObservedContextIdentity',$context);$result=Invoke-Child $authorizationChecker $forgedOwnerArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*RESOURCE_TASK_OWNER_MISMATCH*') 'authorization-resource-task-owner-mismatch-rejected'
    $stalePhaseArgs=$authArgs.Clone();$stalePhaseArgs[[Array]::IndexOf($stalePhaseArgs,'IMPLEMENT')]='VERIFY';$result=Invoke-Child $authorizationChecker $stalePhaseArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*RESOURCE_PHASE_DRIFT*') 'authorization-resource-phase-drift'
    $staleHostArgs=$authArgs.Clone();$staleHostArgs[[Array]::IndexOf($staleHostArgs,'CODEX')]='OTHER_HOST';$result=Invoke-Child $authorizationChecker $staleHostArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*RESOURCE_HOST_DRIFT*') 'authorization-resource-host-drift'
    $staleContextArgs=$authArgs.Clone();$staleContextArgs[[Array]::IndexOf($staleContextArgs,$context)]='4|'+('4'*64);$result=Invoke-Child $authorizationChecker $staleContextArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*RESOURCE_CONTEXT_DRIFT*') 'authorization-resource-context-drift'
    foreach($forgery in @([ordered]@{name='quality';quality='MECHANICAL_LOW';tools=@('browser');continuity='FRESH';reason='RESOURCE_SILENT_QUALITY_DOWNGRADE'},[ordered]@{name='tool';quality='FOCUSED_HIGH';tools=@();continuity='FRESH';reason='RESOURCE_REQUIRED_TOOL_MISSING'},[ordered]@{name='continuity';quality='FOCUSED_HIGH';tools=@('browser');continuity='ANY';reason='RESOURCE_CONTINUITY_DOWNGRADE'})){$forged=Clone-Object $exceptionBinding;$forged.selectedQuality=$forgery.quality;$forged.selectedTools=@($forgery.tools);$forged.continuity=$forgery.continuity;$forged.bindingDigest=Get-BindingDigest $forged;$forgedLocator='.tmp/resource-bindings/forged-'+$forgery.name+'.json';$forgedPath=Join-Path $tempRoot $forgedLocator;Write-Json $forgedPath $forged;$forgedAuth=Clone-Object $auth;$forgedAuth.taskId='RESOURCE-EXCEPTION';$forgedAuth.resourceBindingLocator=$forgedLocator;$forgedAuth.resourceBindingIdentity=Get-Identity $forgedPath;$forgedAuth.resourceBindingDigest=[string]$forged.bindingDigest;$forgedAuthPath=Join-Path $tempRoot ('forged-'+$forgery.name+'-auth.json');Write-Json $forgedAuthPath $forgedAuth;$forgedArgs=@('-PackagePath',(Split-Path -Leaf $forgedAuthPath),'-ObservedActor','executor-1','-ObservedTaskId','RESOURCE-EXCEPTION','-ObservedOwner','owner-1','-ObservedAction','SOURCE_WRITE','-ObservedPath','target.txt','-ObservedIdentity',("target.txt=$targetId"),'-ResourceBindingPath',$forgedLocator,'-ResourceTaskPath','exception-task.md','-ResourceAdapterPolicyPath','policy.json','-ResourceCapabilityPath','capability.json','-ObservedPhase','REVIEW','-ObservedHost','CODEX','-ObservedContextIdentity',$context);$result=Invoke-Child $authorizationChecker $forgedArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like('*'+$forgery.reason+'*')) ('authorization-forged-'+$forgery.name+'-rejected')}
    $policyObject=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $tempRoot 'policy.json')|ConvertFrom-Json;$policyObject.policyId='policy-2';Write-Json (Join-Path $tempRoot 'policy.json') $policyObject;$result=Invoke-Child $authorizationChecker $authArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*RESOURCE_POLICY_DRIFT*') 'authorization-resource-policy-drift';$policyObject.policyId='policy-1';Write-Json (Join-Path $tempRoot 'policy.json') $policyObject;Assert-True ((Get-Identity (Join-Path $tempRoot 'policy.json'))-ceq$policyId) 'resource-policy-restored'
    $tampered=Clone-Object $binding;$tampered.phase='REVIEW';Write-Json $bindingPath $tampered;$result=Invoke-Child $authorizationChecker $authArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*RESOURCE_BINDING_*') 'authorization-binding-tamper'
    $rebindArgs=$resourceArgs.Clone();$rebindArgs[$rebindArgs.Count-1]='.tmp/resource-bindings/binding-rebound.json';$result=Invoke-Child $resourceResolver $rebindArgs $tempRoot;$bindingPath=Join-Path $tempRoot '.tmp/resource-bindings/binding-rebound.json';$bindingId=Get-Identity $bindingPath;$binding=Get-Content -Raw -Encoding utf8 -LiteralPath $bindingPath|ConvertFrom-Json;$auth.resourceBindingLocator='.tmp/resource-bindings/binding-rebound.json';$auth.resourceBindingIdentity=$bindingId;$auth.resourceBindingDigest=[string]$binding.bindingDigest
    $controller=[ordered]@{schemaVersion=1;projectId='project-a';controllerId='controller-new';controllerEpoch=3;state='CURRENT'};Write-Json (Join-Path $tempRoot '.ai-workspace/controller.json') $controller;$controllerId=Get-Identity (Join-Path $tempRoot '.ai-workspace/controller.json')
    $auth.issuer='controller-new';$auth.issuerRole='PROJECT_CONTROLLER';$auth.issuerControllerId='controller-new';$auth.issuerControllerEpoch=3;$auth.controllerControlIdentity=$controllerId;$auth.invalidatesOn+=@('CONTROLLER_EPOCH_CHANGE');Write-Json (Join-Path $tempRoot 'controller-auth.json') $auth
    $controllerArgs=@('-PackagePath','controller-auth.json','-ObservedActor','executor-1','-ObservedTaskId','AUTH-TASK','-ObservedOwner','owner-1','-ObservedAction','SOURCE_WRITE','-ObservedPath','target.txt','-ObservedIdentity',("target.txt=$targetId"),'-ResourceBindingPath','.tmp/resource-bindings/binding-rebound.json','-ResourceTaskPath','task.md','-ResourceAdapterPolicyPath','policy.json','-ResourceCapabilityPath','capability.json','-ObservedPhase','IMPLEMENT','-ObservedHost','CODEX','-ObservedContextIdentity',$context,'-ControllerControlPath','.ai-workspace/controller.json')
    $result=Invoke-Child $authorizationChecker $controllerArgs $tempRoot;Assert-True ($result.Code-eq0) 'authorization-controller-current-pass'
    $auth.issuerControllerEpoch=2;Write-Json (Join-Path $tempRoot 'controller-auth.json') $auth;$result=Invoke-Child $authorizationChecker $controllerArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*STALE_CONTROLLER_AUTHORIZATION*') 'authorization-controller-stale-rejected'

    $taskArgs=@('-TaskPath','task.md','-ObservedActualPath','target.txt');$result=Invoke-Child $taskChecker $taskArgs $tempRoot;if($result.Code-ne0){Write-Output ('TRACE|task-default|'+$result.Text)};Assert-True ($result.Code-eq0) 'task-default-coordination-pass'
    Write-Text (Join-Path $tempRoot 'bad-task.md') "# BAD-TASK - fixture`n`n- Task schema: 1.6.0`n- Owner: owner-1`n- Resource requirement: DEFAULT`n- Coordination exception: {`"mode`":`"INLINE`"}`n- Range summary: profile=STANDARD; lifecycle=ACTIVE; expected_paths=[target.txt]; actual_paths=[target.txt]`n";$result=Invoke-Child $taskChecker @('-TaskPath','bad-task.md','-ObservedActualPath','target.txt') $tempRoot;if($result.Code-eq0-or$result.Text-notlike'*COORDINATION_MODE*'){Write-Output ('TRACE|bad-task|'+$result.Text)};Assert-True ($result.Code-ne0-and$result.Text-like'*COORDINATION_MODE*') 'task-default-expansion-rejected'

    Write-Text (Join-Path $tempRoot 'current-task.md') "# ROUTE-TASK - current`n`n- Owner: owner-1`n";$taskIdentity=Get-Identity (Join-Path $tempRoot 'current-task.md')
    $route=[ordered]@{schemaVersion=1;projectId='project-a';originalControllerId='controller-new';originalControllerEpoch=3;targetControllerId='controller-new';targetControllerEpoch=3;sourceTaskId='ROUTE-TASK';taskIdentity=$taskIdentity;originalMessageClass='ROUTINE';messageClass='ROUTINE';candidateOrState='READY';responsibleReporter='owner-1';rerouteCount=0;authorizationDisposition='NOT_APPLICABLE';revalidatedAgainstCurrentTask=$false};Write-Json (Join-Path $tempRoot 'route.json') $route
    $routeArgs=@('-RoutePath','route.json','-ControllerControlPath','.ai-workspace/controller.json','-CurrentTaskPath','current-task.md');$result=Invoke-Child $routeChecker $routeArgs $tempRoot;if($result.Code-ne0){Write-Output ('TRACE|route-current|'+$result.Text)};Assert-True ($result.Code-eq0-and$result.Text-like'*SUPPRESSED_ROUTINE*') 'route-current-routine-suppressed'
    $route.originalControllerId='controller-old';$route.originalControllerEpoch=2;Write-Json (Join-Path $tempRoot 'route.json') $route;$result=Invoke-Child $routeChecker $routeArgs $tempRoot;Assert-True ($result.Code-eq0-and$result.Text-like'*STALE_QUEUED_AUDIT_ONLY*') 'route-stale-routine-audit'
    $route.originalMessageClass='DECISION';$route.messageClass='DECISION';Write-Json (Join-Path $tempRoot 'route.json') $route;$result=Invoke-Child $routeChecker $routeArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*STALE_CONTROL_MESSAGE*') 'route-stale-decision-rejected'
    $route.originalMessageClass='EXCEPTION';$route.messageClass='EXCEPTION';$route.rerouteCount=1;$route.authorizationDisposition='NONE_REUSED';$route.revalidatedAgainstCurrentTask=$true;Write-Json (Join-Path $tempRoot 'route.json') $route;$result=Invoke-Child $routeChecker $routeArgs $tempRoot;Assert-True ($result.Code-eq0-and$result.Text-like'*REROUTE_EXCEPTION_ONCE*') 'route-stale-exception-revalidated-once'
    $route.sourceTaskId='OTHER-TASK';Write-Json (Join-Path $tempRoot 'route.json') $route;$result=Invoke-Child $routeChecker $routeArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*SOURCE_TASK_MISMATCH*') 'route-source-task-mismatch-rejected';$route.sourceTaskId='ROUTE-TASK'
    $route.responsibleReporter='owner-2';Write-Json (Join-Path $tempRoot 'route.json') $route;$result=Invoke-Child $routeChecker $routeArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*RESPONSIBLE_REPORTER_MISMATCH*') 'route-reporter-mismatch-rejected';$route.responsibleReporter='owner-1'
    $route.originalControllerEpoch=0;Write-Json (Join-Path $tempRoot 'route.json') $route;$result=Invoke-Child $routeChecker $routeArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*ORIGINAL_CONTROLLER_EPOCH_RANGE*') 'route-epoch-zero-rejected';$route.originalControllerEpoch=2
    $route.originalMessageClass='DECISION';$route.messageClass='EXCEPTION';Write-Json (Join-Path $tempRoot 'route.json') $route;$result=Invoke-Child $routeChecker $routeArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*MESSAGE_RECLASSIFICATION*') 'route-reclassification-rejected'
    $route.originalControllerId='controller-new';$route.originalControllerEpoch=3;$route.originalMessageClass='EXCEPTION';$route.messageClass='EXCEPTION';$route.rerouteCount=0;$route.authorizationDisposition='NOT_APPLICABLE';$route.revalidatedAgainstCurrentTask=$false;Write-Json (Join-Path $tempRoot 'route.json') $route;$result=Invoke-Child $routeChecker $routeArgs $tempRoot;$stateKey=[regex]::Match($result.Text,'stateKey=(?<k>[A-F0-9]{64})').Groups['k'].Value;Assert-True ($result.Code-eq0-and$stateKey.Length-eq64) 'route-current-exception-state-key';$result=Invoke-Child $routeChecker ($routeArgs+@('-SeenStateKey',$stateKey)) $tempRoot;Assert-True ($result.Code-eq0-and$result.Text-like'*DEDUPLICATED*') 'route-state-dedup'

    if(-not$SkipMigration){
        $isolated=Join-Path $tempRoot 'workspace';New-Item -ItemType Directory -Path (Join-Path $isolated 'framework\versions') -Force|Out-Null;New-Item -ItemType Directory -Path (Join-Path $isolated 'scripts') -Force|Out-Null
        foreach($source in @('1.4.1','1.5.0','1.5.1','1.5.2')){Copy-Item -LiteralPath (Join-Path $frameworkRoot "versions\$source") -Destination (Join-Path $isolated "framework\versions\$source") -Recurse}
        Copy-Item -LiteralPath $candidateRoot -Destination (Join-Path $isolated 'framework\versions\1.6.0') -Recurse;Copy-Item -LiteralPath (Join-Path $leanRootScripts 'register-project.ps1') -Destination (Join-Path $isolated 'scripts\register-project.ps1');Copy-Item -LiteralPath (Join-Path $leanRootScripts 'upgrade-project.ps1') -Destination (Join-Path $isolated 'scripts\upgrade-project.ps1')
        $stableMeta=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $isolated 'framework\versions\1.6.0\VERSION.json')|ConvertFrom-Json;$stableMeta.lifecycle='STABLE';$stableMeta.consumable=$true;$stableMeta.projectPinEligible=$true;Write-Json (Join-Path $isolated 'framework\versions\1.6.0\VERSION.json') $stableMeta
        $env:AI_WORKSPACE_FRAMEWORK_TEST_MODE='1'
        $registerRepo=Join-Path $tempRoot 'register-repo';Initialize-GitFixture $registerRepo
        $result=Invoke-Child (Join-Path $isolated 'scripts\register-project.ps1') @('-ProjectId','registered-project','-DisplayName','Registered Project','-RepositoryPath',$registerRepo,'-FrameworkVersion','1.6.0','-ControllerId','controller-registered','-WorkspaceRoot',$isolated,'-Apply') $tempRoot
        if($result.Code-ne0-or-not(Test-Path -LiteralPath (Join-Path $registerRepo '.ai-workspace\project.json'))){Write-Output ('TRACE|register|'+$result.Text);throw 'REGISTER_FIXTURE_FAILED'}
        $registeredConfig=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $registerRepo '.ai-workspace\project.json')|ConvertFrom-Json;$registeredController=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $registerRepo '.ai-workspace\controller.json')|ConvertFrom-Json
        Assert-True ($result.Code-eq0-and[int]$registeredConfig.schemaVersion-eq3-and@($registeredConfig.protectedPaths).Count-eq0-and[string]$registeredController.controllerId-ceq'controller-registered'-and[int]$registeredController.controllerEpoch-eq1) 'register-schema3-controller'
        $missingRepo=Join-Path $tempRoot 'missing-controller-repo';Initialize-GitFixture $missingRepo;$result=Invoke-Child (Join-Path $isolated 'scripts\register-project.ps1') @('-ProjectId','missing-controller','-DisplayName','Missing','-RepositoryPath',$missingRepo,'-FrameworkVersion','1.6.0','-WorkspaceRoot',$isolated,'-Apply') $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*ControllerId is required*') 'register-controller-required'
        foreach($source in @('1.4.1','1.5.0','1.5.1','1.5.2')){
            $repo=Join-Path $tempRoot ("upgrade-"+$source.Replace('.','-'));Initialize-GitFixture $repo;$control=Join-Path $repo '.ai-workspace';New-Item -ItemType Directory -Path (Join-Path $control 'tasks\active') -Force|Out-Null
            $sourceRoot=Join-Path $isolated "framework\versions\$source";$projectTemplate=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $sourceRoot 'project-starter\project.json');$projectText=$projectTemplate.Replace('{{PROJECT_ID_JSON}}','"upgrade-project"').Replace('{{DISPLAY_NAME_JSON}}','"Upgrade Project"').Replace('{{FRAMEWORK_VERSION_JSON}}',('"'+$source+'"'));Write-Text (Join-Path $control 'project.json') $projectText
            $bootstrap=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $sourceRoot 'project-starter\BOOTSTRAP.md');$bootstrap=$bootstrap.Replace('{{PROJECT_ID}}','upgrade-project').Replace('{{DISPLAY_NAME}}','Upgrade Project').Replace('{{FRAMEWORK_VERSION}}',$source);Write-Text (Join-Path $control 'BOOTSTRAP.md') $bootstrap
            Write-Text (Join-Path $control 'tasks\active\legacy.authorization.json') "legacy-controller-package`n";$legacyPackageId=Get-Identity (Join-Path $control 'tasks\active\legacy.authorization.json')
            Write-Json (Join-Path $repo 'protected-migration.json') ([ordered]@{schemaVersion=1;projectId='upgrade-project';protectedPaths=@([ordered]@{path='src/config/level.js';deny=@('visibility','read','hash','diff','index','write')})});Write-Json (Join-Path $repo 'legacy-inventory.json') ([ordered]@{schemaVersion=1;projectId='upgrade-project';currentControllerId='controller-upgrade';packages=@([ordered]@{locator='.ai-workspace/tasks/active/legacy.authorization.json';identity=$legacyPackageId})})
            $migrationId=Get-Identity (Join-Path $repo 'protected-migration.json');$inventoryId=Get-Identity (Join-Path $repo 'legacy-inventory.json')
            $upgradeArgs=@('-ProjectId','upgrade-project','-RepositoryPath',$repo,'-ToVersion','1.6.0','-ControllerId','controller-upgrade','-ProtectedPathsMigrationPath',(Join-Path $repo 'protected-migration.json'),'-ExpectedProtectedPathsMigrationIdentity',$migrationId,'-LegacyControllerAuthorizationInventoryPath',(Join-Path $repo 'legacy-inventory.json'),'-ExpectedLegacyControllerAuthorizationInventoryIdentity',$inventoryId,'-WorkspaceRoot',$isolated,'-Apply')
            $result=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') $upgradeArgs $tempRoot;if($result.Code-ne0-or-not(Test-Path -LiteralPath (Join-Path $control 'controller.json'))){Write-Output ("TRACE|upgrade-$source|"+$result.Text);throw "UPGRADE_FIXTURE_FAILED_$source"};$upgraded=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $control 'project.json')|ConvertFrom-Json;$upController=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $control 'controller.json')|ConvertFrom-Json;$ledger=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $control 'controller-revocations.json')|ConvertFrom-Json
            Assert-True ($result.Code-eq0-and[int]$upgraded.schemaVersion-eq3-and[string]$upgraded.frameworkVersion-ceq'1.6.0'-and[string]$upController.controllerId-ceq'controller-upgrade'-and@($ledger.packages).Count-eq1) ("upgrade-$source-to-1.6.0")
            $repeat=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') @('-ProjectId','upgrade-project','-RepositoryPath',$repo,'-ToVersion','1.6.0','-WorkspaceRoot',$isolated) $tempRoot;if($repeat.Code-ne0){Write-Output ("TRACE|upgrade-$source-repeat|"+$repeat.Text)};Assert-True ($repeat.Code-eq0-and$repeat.Text-like'*ALREADY_UPGRADED*') ("upgrade-$source-idempotent")
            if($source-ceq'1.5.2'){
                $rotated=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $control 'controller.json')|ConvertFrom-Json;$rotated.controllerId='controller-successor';$rotated.controllerEpoch=2;Write-Json (Join-Path $control 'controller.json') $rotated;$repeat=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') @('-ProjectId','upgrade-project','-RepositoryPath',$repo,'-ToVersion','1.6.0','-WorkspaceRoot',$isolated) $tempRoot;Assert-True ($repeat.Code-eq0-and$repeat.Text-like'*ALREADY_UPGRADED*') 'upgrade-current-controller-epoch2-healthy'
                $repeatProjectPath=Join-Path $control 'project.json';$repeatControllerPath=Join-Path $control 'controller.json';$repeatLedgerPath=Join-Path $control 'controller-revocations.json';$healthyProjectRaw=Get-Content -Raw -Encoding utf8 -LiteralPath $repeatProjectPath;$healthyControllerRaw=Get-Content -Raw -Encoding utf8 -LiteralPath $repeatControllerPath;$healthyLedgerRaw=Get-Content -Raw -Encoding utf8 -LiteralPath $repeatLedgerPath
                Remove-Item -LiteralPath $repeatLedgerPath -Force;New-Item -ItemType Directory -Path $repeatLedgerPath|Out-Null;$repeat=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') @('-ProjectId','upgrade-project','-RepositoryPath',$repo,'-ToVersion','1.6.0','-WorkspaceRoot',$isolated) $tempRoot;Assert-True ($repeat.Code-ne0-and$repeat.Text-like'*must be a regular file*'-and(Test-Path -LiteralPath $repeatLedgerPath -PathType Container)) 'upgrade-repeat-ledger-directory-rejected';Remove-Item -LiteralPath $repeatLedgerPath -Recurse -Force;Write-Text $repeatLedgerPath $healthyLedgerRaw
                $repeatReparseTarget=Join-Path $tempRoot 'repeat-ledger-reparse-target';New-Item -ItemType Directory -Path $repeatReparseTarget -Force|Out-Null;Remove-Item -LiteralPath $repeatLedgerPath -Force;New-Item -ItemType Junction -Path $repeatLedgerPath -Target $repeatReparseTarget|Out-Null;$repeat=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') @('-ProjectId','upgrade-project','-RepositoryPath',$repo,'-ToVersion','1.6.0','-WorkspaceRoot',$isolated) $tempRoot;Assert-True ($repeat.Code-ne0-and$repeat.Text-like'*regular file*') 'upgrade-repeat-ledger-reparse-rejected';Remove-Item -LiteralPath $repeatLedgerPath -Recurse -Force;Write-Text $repeatLedgerPath $healthyLedgerRaw
                $unknownRepeatProject=$healthyProjectRaw|ConvertFrom-Json;$unknownRepeatProject|Add-Member -NotePropertyName unknownField -NotePropertyValue 'forbidden';Write-Json $repeatProjectPath $unknownRepeatProject;$unknownRepeatProjectId=Get-Identity $repeatProjectPath;$repeat=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') @('-ProjectId','upgrade-project','-RepositoryPath',$repo,'-ToVersion','1.6.0','-WorkspaceRoot',$isolated) $tempRoot;Assert-True ($repeat.Code-ne0-and$repeat.Text-like'*field set mismatch*'-and(Get-Identity $repeatProjectPath)-ceq$unknownRepeatProjectId) 'upgrade-repeat-project-unknown-no-write';Write-Text $repeatProjectPath $healthyProjectRaw
                $stateFieldRegex=[regex]'"state"\s*:\s*"CURRENT"';$duplicateRepeatController=$stateFieldRegex.Replace($healthyControllerRaw,"`"state`": `"CURRENT`",`n    `"state`": `"CURRENT`"",1);if([regex]::Matches($duplicateRepeatController,'"state"\s*:').Count-ne2){throw 'DUPLICATE_CONTROLLER_FIXTURE_FAILED'};Write-Text $repeatControllerPath $duplicateRepeatController;$duplicateRepeatControllerId=Get-Identity $repeatControllerPath;$repeat=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') @('-ProjectId','upgrade-project','-RepositoryPath',$repo,'-ToVersion','1.6.0','-WorkspaceRoot',$isolated) $tempRoot;Assert-True ($repeat.Code-ne0-and$repeat.Text-like'*duplicate or missing field*'-and(Get-Identity $repeatControllerPath)-ceq$duplicateRepeatControllerId) 'upgrade-repeat-controller-duplicate-no-write';Write-Text $repeatControllerPath $healthyControllerRaw
                $unknownRepeatLedger=$healthyLedgerRaw|ConvertFrom-Json;$unknownRepeatLedger|Add-Member -NotePropertyName unknownField -NotePropertyValue 'forbidden';Write-Json $repeatLedgerPath $unknownRepeatLedger;$unknownRepeatLedgerId=Get-Identity $repeatLedgerPath;$repeat=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') @('-ProjectId','upgrade-project','-RepositoryPath',$repo,'-ToVersion','1.6.0','-WorkspaceRoot',$isolated) $tempRoot;Assert-True ($repeat.Code-ne0-and$repeat.Text-like'*field set mismatch*'-and(Get-Identity $repeatLedgerPath)-ceq$unknownRepeatLedgerId) 'upgrade-repeat-ledger-unknown-no-write';Write-Text $repeatLedgerPath $healthyLedgerRaw
                $invalidProtected=$healthyProjectRaw|ConvertFrom-Json;$invalidProtected.protectedPaths[0].deny=@('visibility','bogus');Write-Json $repeatProjectPath $invalidProtected;$invalidProtectedId=Get-Identity $repeatProjectPath;$repeat=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') @('-ProjectId','upgrade-project','-RepositoryPath',$repo,'-ToVersion','1.6.0','-WorkspaceRoot',$isolated) $tempRoot;Assert-True ($repeat.Code-ne0-and$repeat.Text-like'*deny list is invalid*'-and(Get-Identity $repeatProjectPath)-ceq$invalidProtectedId) 'upgrade-repeat-protected-rule-invalid-no-write';Write-Text $repeatProjectPath $healthyProjectRaw
                $outsideProtected=$healthyProjectRaw|ConvertFrom-Json;$outsideProtected.protectedPaths[0].path='../outside';Write-Json $repeatProjectPath $outsideProtected;$outsideProtectedId=Get-Identity $repeatProjectPath;$repeat=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') @('-ProjectId','upgrade-project','-RepositoryPath',$repo,'-ToVersion','1.6.0','-WorkspaceRoot',$isolated) $tempRoot;Assert-True ($repeat.Code-ne0-and$repeat.Text-notlike'*ALREADY_UPGRADED*'-and(Get-Identity $repeatProjectPath)-ceq$outsideProtectedId) 'upgrade-repeat-protected-outside-no-write';Write-Text $repeatProjectPath $healthyProjectRaw
                $duplicateProtected=$healthyProjectRaw|ConvertFrom-Json;$duplicatePath=[string]$duplicateProtected.protectedPaths[0].path;$duplicateProtected.protectedPaths=@($duplicateProtected.protectedPaths[0],[pscustomobject][ordered]@{path=$duplicatePath;deny=@('hash')});Write-Json $repeatProjectPath $duplicateProtected;$duplicateProtectedId=Get-Identity $repeatProjectPath;$repeat=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') @('-ProjectId','upgrade-project','-RepositoryPath',$repo,'-ToVersion','1.6.0','-WorkspaceRoot',$isolated) $tempRoot;Assert-True ($repeat.Code-ne0-and$repeat.Text-like'*duplicate path*'-and(Get-Identity $repeatProjectPath)-ceq$duplicateProtectedId) 'upgrade-repeat-protected-duplicate-path-no-write';Write-Text $repeatProjectPath $healthyProjectRaw
                $tamperedLedger=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $control 'controller-revocations.json')|ConvertFrom-Json;$tamperedLedger.packages[0].identity='99|'+('9'*64);Write-Json (Join-Path $control 'controller-revocations.json') $tamperedLedger;$repeat=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') @('-ProjectId','upgrade-project','-RepositoryPath',$repo,'-ToVersion','1.6.0','-WorkspaceRoot',$isolated) $tempRoot;Assert-True ($repeat.Code-ne0-and$repeat.Text-like'*identity drift*') 'upgrade-tampered-revocation-rejected'
            }
        }
        $recoveryRepo=Join-Path $tempRoot 'upgrade-recovery';Initialize-GitFixture $recoveryRepo;$recoveryControl=Join-Path $recoveryRepo '.ai-workspace';New-Item -ItemType Directory -Path (Join-Path $recoveryControl 'tasks\active') -Force|Out-Null;$sourceRoot=Join-Path $isolated 'framework\versions\1.5.2';$projectTemplate=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $sourceRoot 'project-starter\project.json');$recoveryProjectText=$projectTemplate.Replace('{{PROJECT_ID_JSON}}','"recovery-project"').Replace('{{DISPLAY_NAME_JSON}}','"Recovery Project"').Replace('{{FRAMEWORK_VERSION_JSON}}','"1.5.2"');Write-Text (Join-Path $recoveryControl 'project.json') $recoveryProjectText;$bootstrap=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $sourceRoot 'project-starter\BOOTSTRAP.md');$recoveryBootstrapText=$bootstrap.Replace('{{PROJECT_ID}}','recovery-project').Replace('{{DISPLAY_NAME}}','Recovery Project').Replace('{{FRAMEWORK_VERSION}}','1.5.2');Write-Text (Join-Path $recoveryControl 'BOOTSTRAP.md') $recoveryBootstrapText;Write-Text (Join-Path $recoveryControl 'tasks\active\legacy.authorization.json') "legacy-controller-package`n";$legacyId=Get-Identity (Join-Path $recoveryControl 'tasks\active\legacy.authorization.json');Write-Json (Join-Path $recoveryRepo 'protected-migration.json') ([ordered]@{schemaVersion=1;projectId='recovery-project';protectedPaths=@()});Write-Json (Join-Path $recoveryRepo 'legacy-inventory.json') ([ordered]@{schemaVersion=1;projectId='recovery-project';currentControllerId='controller-recovery';packages=@([ordered]@{locator='.ai-workspace/tasks/active/legacy.authorization.json';identity=$legacyId})});$recoveryMigrationId=Get-Identity (Join-Path $recoveryRepo 'protected-migration.json');$recoveryInventoryId=Get-Identity (Join-Path $recoveryRepo 'legacy-inventory.json');$recoveryArgs=@('-ProjectId','recovery-project','-RepositoryPath',$recoveryRepo,'-ToVersion','1.6.0','-ControllerId','controller-recovery','-ProtectedPathsMigrationPath',(Join-Path $recoveryRepo 'protected-migration.json'),'-ExpectedProtectedPathsMigrationIdentity',$recoveryMigrationId,'-LegacyControllerAuthorizationInventoryPath',(Join-Path $recoveryRepo 'legacy-inventory.json'),'-ExpectedLegacyControllerAuthorizationInventoryIdentity',$recoveryInventoryId,'-WorkspaceRoot',$isolated,'-Apply')
        $unknownProject=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $recoveryControl 'project.json')|ConvertFrom-Json;$unknownProject|Add-Member -NotePropertyName unknownField -NotePropertyValue 'forbidden';Write-Json (Join-Path $recoveryControl 'project.json') $unknownProject;$result=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') $recoveryArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*field set mismatch*'-and-not(Test-Path -LiteralPath (Join-Path $recoveryControl 'controller.json'))) 'upgrade-source-unknown-field-no-write';Write-Text (Join-Path $recoveryControl 'project.json') $recoveryProjectText
        $duplicateProject=$recoveryProjectText.Replace('  "id": "recovery-project",',"  `"id`": `"recovery-project`",`n  `"id`": `"recovery-project`",");Write-Text (Join-Path $recoveryControl 'project.json') $duplicateProject;$result=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') $recoveryArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*duplicate or missing field*'-and-not(Test-Path -LiteralPath (Join-Path $recoveryControl 'controller.json'))) 'upgrade-source-duplicate-field-no-write';Write-Text (Join-Path $recoveryControl 'project.json') $recoveryProjectText
        Write-Text (Join-Path $recoveryControl 'BOOTSTRAP.md') $recoveryBootstrapText.Replace('<!-- PROJECT-CUSTOM:END -->','<!-- PROJECT-CUSTOM:END-BROKEN -->');$result=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') $recoveryArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*Bootstrap markers*'-and-not(Test-Path -LiteralPath (Join-Path $recoveryControl 'controller.json'))) 'upgrade-bootstrap-custom-marker-no-write';Write-Text (Join-Path $recoveryControl 'BOOTSTRAP.md') $recoveryBootstrapText
        $reparseRepo=Join-Path $tempRoot 'upgrade-reparse';Initialize-GitFixture $reparseRepo;$reparseTarget=Join-Path $tempRoot 'upgrade-reparse-target';New-Item -ItemType Directory -Path $reparseTarget -Force|Out-Null;$null=New-Item -ItemType Junction -Path (Join-Path $reparseRepo '.ai-workspace') -Target $reparseTarget;$result=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') @('-ProjectId','reparse-project','-RepositoryPath',$reparseRepo,'-ToVersion','1.6.0','-WorkspaceRoot',$isolated) $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*Reparse point is forbidden*') 'upgrade-control-reparse-rejected'
        $badMigrationArgs=$recoveryArgs.Clone();$badMigrationArgs[[Array]::IndexOf($badMigrationArgs,$recoveryMigrationId)]='1|'+('0'*64);$result=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') $badMigrationArgs $tempRoot;Assert-True ($result.Code-ne0-and-not(Test-Path -LiteralPath (Join-Path $recoveryControl 'controller.json'))) 'upgrade-migration-identity-drift-no-write'
        $env:AI_WORKSPACE_UPGRADE_TEST_STOP_AFTER_PREPARE='1';$result=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') $recoveryArgs $tempRoot;Remove-Item Env:AI_WORKSPACE_UPGRADE_TEST_STOP_AFTER_PREPARE -ErrorAction SilentlyContinue;$transactionRoot=Join-Path $recoveryControl '.framework-upgrade-transaction';Write-Text (Join-Path $transactionRoot 'foreign.txt') "foreign`n";$result=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') $recoveryArgs $tempRoot;Assert-True ($result.Code-ne0-and$result.Text-like'*Unexpected upgrade transaction entry*'-and(Test-Path -LiteralPath (Join-Path $transactionRoot 'foreign.txt'))) 'upgrade-unknown-transaction-entry-retained';Remove-Item -LiteralPath (Join-Path $transactionRoot 'foreign.txt') -Force;$result=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') $recoveryArgs $tempRoot;Assert-True ($result.Code-eq0-and$result.Text-like'*RECOVERED_ROLLED_BACK*'-and-not(Test-Path -LiteralPath $transactionRoot)) 'upgrade-known-transaction-recovery'
        $env:AI_WORKSPACE_UPGRADE_TEST_INTERRUPT_AFTER_PROJECT_REPLACE='1';$result=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') $recoveryArgs $tempRoot;Remove-Item Env:AI_WORKSPACE_UPGRADE_TEST_INTERRUPT_AFTER_PROJECT_REPLACE -ErrorAction SilentlyContinue;$rolledBack=Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $recoveryControl 'project.json')|ConvertFrom-Json;Assert-True ($result.Code-ne0-and[string]$rolledBack.frameworkVersion-ceq'1.5.2'-and-not(Test-Path -LiteralPath (Join-Path $recoveryControl 'controller.json'))-and-not(Test-Path -LiteralPath (Join-Path $recoveryControl '.framework-upgrade-transaction'))) 'upgrade-interrupt-rolls-back'
        $env:AI_WORKSPACE_UPGRADE_TEST_DRIFT_BEFORE_FINAL_SNAPSHOT='1';$result=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') $recoveryArgs $tempRoot;Remove-Item Env:AI_WORKSPACE_UPGRADE_TEST_DRIFT_BEFORE_FINAL_SNAPSHOT -ErrorAction SilentlyContinue;$transactionRoot=Join-Path $recoveryControl '.framework-upgrade-transaction';Assert-True ($result.Code-ne0-and$result.Text-like'*recovery retained materials*'-and(Test-Path -LiteralPath $transactionRoot)-and((Get-Content -Raw -Encoding utf8 -LiteralPath (Join-Path $recoveryControl 'project.json'))-ceq"test-final-snapshot-drift`n")) 'upgrade-final-snapshot-drift-retains-transaction'
        [IO.File]::WriteAllBytes((Join-Path $recoveryControl 'project.json'),[IO.File]::ReadAllBytes((Join-Path $transactionRoot 'new/0.bin')));$result=Invoke-Child (Join-Path $isolated 'scripts\upgrade-project.ps1') $recoveryArgs $tempRoot;Assert-True ($result.Code-eq0-and$result.Text-like'*RECOVERED_COMMITTED*'-and(Test-Path -LiteralPath (Join-Path $recoveryControl 'controller.json'))-and-not(Test-Path -LiteralPath $transactionRoot)) 'upgrade-final-snapshot-recovery-succeeds'
        Remove-Item Env:AI_WORKSPACE_FRAMEWORK_TEST_MODE -ErrorAction SilentlyContinue
    }
}
finally{
    Remove-Item Env:AI_WORKSPACE_FRAMEWORK_TEST_MODE -ErrorAction SilentlyContinue
    Remove-Item Env:AI_WORKSPACE_UPGRADE_TEST_DRIFT_BEFORE_FINAL_SNAPSHOT -ErrorAction SilentlyContinue
    if(Test-Path -LiteralPath $tempRoot){Remove-Item -LiteralPath $tempRoot -Recurse -Force}
}
Write-Output ("RESULT $script:passed/$script:passed passed|scope=A-C+G|lifecycle=DRAFT_NOT_CONSUMABLE")
exit 0
