[CmdletBinding()]
param([switch]$SkipRootMigration,[switch]$SkipManifest)

$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$utf8=New-Object Text.UTF8Encoding($false)
$utf8Strict=New-Object Text.UTF8Encoding($false,$true)
$script:passed=0
$selfPath=$MyInvocation.MyCommand.Path

function Assert-True([bool]$Condition,[string]$Name){if(-not $Condition){throw "ASSERT_FAIL|$Name"};$script:passed++;Write-Output "PASS|$Name"}
function Write-Utf8([string]$Path,[string]$Text){$parent=Split-Path -Parent $Path;if($parent -and -not (Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$value=$Text.Replace("`r`n","`n").Replace("`r","`n");if(-not $value.EndsWith("`n")){$value+="`n"};[IO.File]::WriteAllText($Path,$value,$utf8)}
function Get-Identity([string]$Path){$bytes=[IO.File]::ReadAllBytes($Path);$sha=[Security.Cryptography.SHA256]::Create();try{return $bytes.Length.ToString()+'|'+([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','')}finally{$sha.Dispose()}}
function Invoke-Ps([string]$Script,[string[]]$Arguments,[string]$WorkingDirectory=''){
    if($WorkingDirectory){Push-Location $WorkingDirectory}
    try{$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$output=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script @Arguments 2>&1|ForEach-Object{[string]$_});$code=$LASTEXITCODE;$ErrorActionPreference=$old;return [pscustomobject]@{Code=$code;Output=$output;Text=($output-join"`n")}}
    finally{if($WorkingDirectory){Pop-Location}}
}
function New-GitRepo([string]$Path){New-Item -ItemType Directory -Path $Path -Force|Out-Null;&git -C $Path init -q;if($LASTEXITCODE-ne 0){throw'git init failed'};&git -C $Path config user.email test@example.invalid;&git -C $Path config user.name FrameworkTest}
function New-IsolatedWorkspace([string]$Root,[string]$CandidateRoot){
    $ws=Join-Path $Root 'workspace';New-Item -ItemType Directory -Path (Join-Path $ws 'framework\versions') -Force|Out-Null
    foreach($v in @('1.4.1','1.5.0','1.5.1','1.5.2')){Copy-Item -LiteralPath (Join-Path $frameworkRoot "versions\$v") -Destination (Join-Path $ws "framework\versions\$v") -Recurse}
    Copy-Item -LiteralPath $CandidateRoot -Destination (Join-Path $ws 'framework\versions\1.6.0') -Recurse
    Write-Utf8 (Join-Path $ws 'framework\CURRENT') '1.4.1'
    return $ws
}
function New-Migration([string]$Repo,[string]$ProjectId,$Paths){$path=Join-Path $Repo '.tmp\routine-exclusions.json';$obj=[ordered]@{schemaVersion=1;projectId=$ProjectId;routineExcludedPaths=@($Paths)};Write-Utf8 $path ($obj|ConvertTo-Json -Depth 20);return [pscustomobject]@{Path=$path;Identity=Get-Identity $path}}
function New-TransactionFixture([string]$Root,$Saved){$transactionId=[Guid]::NewGuid().ToString('N');New-Item -ItemType Directory -Path (Join-Path $Root 'old'),(Join-Path $Root 'new') -Force|Out-Null;Write-Utf8 (Join-Path $Root 'old\project.json') $Saved.OldProject;Write-Utf8 (Join-Path $Root 'old\BOOTSTRAP.md') $Saved.OldBootstrap;Write-Utf8 (Join-Path $Root 'new\project.json') $Saved.NewProject;Write-Utf8 (Join-Path $Root 'new\BOOTSTRAP.md') $Saved.NewBootstrap;Write-Utf8 (Join-Path $Root 'new\controller.json') $Saved.NewController;$state=[ordered]@{schemaVersion=1;transactionId=$transactionId;projectId=$Saved.Id;fromVersion='1.5.2';toVersion='1.6.0';controllerMode='CREATE';oldProjectIdentity=Get-Identity (Join-Path $Root 'old\project.json');oldBootstrapIdentity=Get-Identity (Join-Path $Root 'old\BOOTSTRAP.md');newProjectIdentity=Get-Identity (Join-Path $Root 'new\project.json');newBootstrapIdentity=Get-Identity (Join-Path $Root 'new\BOOTSTRAP.md');newControllerIdentity=Get-Identity (Join-Path $Root 'new\controller.json')};Write-Utf8 (Join-Path $Root 'state.json') ($state|ConvertTo-Json -Depth 10);return $state}
function Register-Project([string]$Script,[string]$Ws,[string]$Repo,[string]$Id,[string]$Version,[string]$Controller=''){$args=@('-ProjectId',$Id,'-DisplayName',$Id,'-RepositoryPath',$Repo,'-WorkspaceRoot',$Ws,'-Apply');if($Version){$args+=@('-FrameworkVersion',$Version)};if($Controller){$args+=@('-ControllerId',$Controller)};return Invoke-Ps $Script $args}

$candidateRoot=Split-Path -Parent $PSScriptRoot
$frameworkRoot=Split-Path -Parent (Split-Path -Parent $candidateRoot)
$workspaceRoot=Split-Path -Parent $frameworkRoot
$stableRoot=Join-Path $frameworkRoot 'versions\1.5.2'
$rootDraft=$workspaceRoot
$register=Join-Path $rootDraft 'scripts\register-project.ps1'
$upgrade=Join-Path $rootDraft 'scripts\upgrade-project.ps1'
$auth=Join-Path $candidateRoot 'scripts\check-authorization.ps1'
$safeGit=Join-Path $candidateRoot 'scripts\invoke-protected-safe-git.ps1'
$loader=Join-Path $candidateRoot 'scripts\resolve-load-plan.ps1'
$knowledgeChecker=Join-Path $candidateRoot 'scripts\check-knowledge-entry.ps1'

$expected=@(
'AUTHORIZATION_MODEL.md','CHANGELOG.md','CONTROLLER_SCHEMA.json','EXAMPLES.md','FRAMEWORK_RELEASE.md','GIT_AND_EXTERNAL.md','HOST_CODEX.md','KNOWLEDGE_AND_REFERENCE.md','KNOWLEDGE_SCHEMA.json','LOAD_MANIFEST.json','MIGRATION_MATRIX.md','PERSPECTIVE_LENSES.md','PROJECT_CONFIG_SCHEMA.json','PROJECT_CONTROL.md','project-starter/.gitattributes','project-starter/BOOTSTRAP.md','project-starter/controller.json','project-starter/project.json','project-starter/PROJECT.md','project-starter/RELATIONSHIPS.md','project-starter/REVIEW_PROFILE.md','project-starter/STATUS.md','project-starter/tasks/README.md','PROMPTS.md','README.md','RECOVERY_CORE.md','RELEASE_MANIFEST.json','REVIEW_AND_EVIDENCE.md','scripts/check-authorization.ps1','scripts/check-knowledge-entry.ps1','scripts/check-task-card.ps1','scripts/invoke-protected-safe-git.ps1','scripts/resolve-load-plan.ps1','STATIC_COMPARISON.md','TASK_AND_SCOPE.md','TASK_TEMPLATE.md','tests/run-framework-tests.ps1','VERSION.json')
$actual=@(Get-ChildItem -LiteralPath $candidateRoot -Recurse -File -Force|ForEach-Object{$_.FullName.Substring($candidateRoot.Length+1).Replace('\','/')}|Sort-Object)
Assert-True (@(Compare-Object ($expected|Sort-Object) $actual -CaseSensitive).Count-eq 0) 'candidate-inventory-exact38'
Assert-True (-not(Test-Path -LiteralPath (Join-Path $candidateRoot 'tests\run-hotfix-tests.ps1'))) 'hotfix-runner-omitted'

foreach($path in @($actual|Where-Object{$_-match'\.(md|json|ps1|psm1)$'})){$full=Join-Path $candidateRoot $path;$bytes=[IO.File]::ReadAllBytes($full);$ok=$true;try{$text=$utf8Strict.GetString($bytes)}catch{$ok=$false;$text=''};if($bytes.Length-ge 3-and$bytes[0]-eq0xEF-and$bytes[1]-eq0xBB-and$bytes[2]-eq0xBF){$ok=$false};if($text.Contains("`r")-or$text.Contains([char]0)-or$text.Contains([char]0xFFFD)-or-not$text.EndsWith("`n")){$ok=$false};Assert-True $ok ("strict|"+$path);if($path.EndsWith('.json')-and$path-notin@('project-starter/project.json','project-starter/controller.json')){try{$null=$text|ConvertFrom-Json;$jsonOk=$true}catch{$jsonOk=$false};Assert-True $jsonOk ("json|"+$path)}}
$renderProject=(Get-Content -LiteralPath (Join-Path $candidateRoot 'project-starter\project.json') -Raw -Encoding utf8).Replace('{{PROJECT_ID_JSON}}','"sample"').Replace('{{DISPLAY_NAME_JSON}}','"Sample"').Replace('{{FRAMEWORK_VERSION_JSON}}','"1.6.0"')
$renderController=(Get-Content -LiteralPath (Join-Path $candidateRoot 'project-starter\controller.json') -Raw -Encoding utf8).Replace('{{PROJECT_ID_JSON}}','"sample"').Replace('{{CONTROLLER_ID_JSON}}','"controller"')
try{$null=$renderProject|ConvertFrom-Json;$null=$renderController|ConvertFrom-Json;$renderOk=$true}catch{$renderOk=$false};Assert-True $renderOk 'starter-json-templates-render'
foreach($path in @('scripts/check-authorization.ps1','scripts/check-knowledge-entry.ps1','scripts/check-task-card.ps1','scripts/invoke-protected-safe-git.ps1','scripts/resolve-load-plan.ps1','tests/run-framework-tests.ps1')){$tokens=$null;$errors=$null;[Management.Automation.Language.Parser]::ParseFile((Join-Path $candidateRoot $path),[ref]$tokens,[ref]$errors)|Out-Null;Assert-True ($errors.Count-eq 0) ("syntax|"+$path)}
foreach($path in @('INITIALIZATION.md','scripts/register-project.ps1','scripts/upgrade-project.ps1')){$full=Join-Path $rootDraft $path;$tokens=$null;$errors=$null;if($path.EndsWith('.ps1')){[Management.Automation.Language.Parser]::ParseFile($full,[ref]$tokens,[ref]$errors)|Out-Null;Assert-True ($errors.Count-eq 0) ("root-syntax|"+$path)}}
$rootExpected=@('INITIALIZATION.md','scripts/register-project.ps1','scripts/upgrade-project.ps1');$rootActual=@($rootExpected|Where-Object{Test-Path -LiteralPath (Join-Path $rootDraft $_) -PathType Leaf});Assert-True (@(Compare-Object $rootExpected $rootActual -CaseSensitive).Count-eq0) 'live-root-required-exact3'
foreach($path in $rootExpected){$bytes=[IO.File]::ReadAllBytes((Join-Path $rootDraft $path));$ok=$true;try{$text=$utf8Strict.GetString($bytes)}catch{$ok=$false;$text=''};if($bytes.Length-ge3-and$bytes[0]-eq0xEF-and$bytes[1]-eq0xBB-and$bytes[2]-eq0xBF){$ok=$false};if($text.Contains("`r")-or$text.Contains([char]0)-or$text.Contains([char]0xFFFD)-or-not$text.EndsWith("`n")){$ok=$false};Assert-True $ok ("root-strict|"+$path)}
Assert-True ((Get-Identity (Join-Path $workspaceRoot 'INITIALIZATION.md'))-ceq'8833|0016195C0A88606BBF8F891BFC78A5248C1C9D3709E05A95D25C9F5330BADE81') 'live-initialization-1.6.0'
Assert-True ((Get-Identity (Join-Path $workspaceRoot 'scripts\register-project.ps1'))-ceq'26779|4AF20EB77DEA77DAD4B7716AAB9C4C6FD79CD6FF271D5475401D8BB541667D74') 'live-register-1.6.0'
Assert-True ((Get-Identity (Join-Path $workspaceRoot 'scripts\upgrade-project.ps1'))-ceq'48922|C3EF6638F0102FB6F2AEF59A6671ADB743DBEB1F2C7BF9EFAB8F2491DACA8181') 'live-upgrade-1.6.0'
$current=((Get-Content -LiteralPath (Join-Path $frameworkRoot 'CURRENT') -Raw -Encoding utf8).Trim());$currentRoot=Join-Path $frameworkRoot "versions\$current";$currentVersion=Join-Path $currentRoot 'VERSION.json';if(Test-Path -LiteralPath $currentVersion -PathType Leaf){$currentMetadata=Get-Content -LiteralPath $currentVersion -Raw -Encoding utf8|ConvertFrom-Json;$currentOk=[string]$currentMetadata.lifecycle-ceq'STABLE'-and[bool]$currentMetadata.consumable}else{$currentOk=$current-ceq'1.4.1'-and(Test-Path -LiteralPath $currentRoot -PathType Container)};Assert-True $currentOk 'framework-current-target-is-stable-or-legacy-1.4.1'
$stableManifest=Get-Content -LiteralPath (Join-Path $stableRoot 'RELEASE_MANIFEST.json') -Raw|ConvertFrom-Json;[string[]]$stablePayload=@(Get-ChildItem -LiteralPath $stableRoot -Recurse -File -Force|ForEach-Object{$_.FullName.Substring($stableRoot.Length+1).Replace('\','/')}|Where-Object{$_-cne'RELEASE_MANIFEST.json'});[Array]::Sort($stablePayload,[StringComparer]::Ordinal);$stableRows=@();$stableBytes=[int64]0;foreach($path in $stablePayload){$full=Join-Path $stableRoot $path;$bytes=[IO.File]::ReadAllBytes($full);$stableBytes+=$bytes.Length;$stableRows+=("$path|$($bytes.Length)|"+(Get-Identity $full).Split('|')[1])};$sha=[Security.Cryptography.SHA256]::Create();try{$stableCanonical=([BitConverter]::ToString($sha.ComputeHash($utf8.GetBytes(($stableRows-join"`n"))))).Replace('-','')}finally{$sha.Dispose()};Assert-True ($stablePayload.Count-eq31-and$stableBytes-eq194871-and$stableCanonical-ceq'3DB3DB7DD90780C0E66203C5F31A4D77B9FDCDCEB206E3A9743C2EE2156A6AA0'-and[string]$stableManifest.canonical-ceq$stableCanonical) 'stable-1.5.2-zero-drift'

$same=@('PERSPECTIVE_LENSES.md','project-starter/.gitattributes','project-starter/RELATIONSHIPS.md','project-starter/tasks/README.md','scripts/check-task-card.ps1')
foreach($path in $same){Assert-True ((Get-Identity (Join-Path $candidateRoot $path))-ceq(Get-Identity (Join-Path $stableRoot $path))) ("baseline-identical|"+$path)}
$version=Get-Content -LiteralPath (Join-Path $candidateRoot 'VERSION.json') -Raw|ConvertFrom-Json
Assert-True ([string]$version.version-ceq'1.6.0'-and[string]$version.lifecycle-ceq'STABLE'-and[bool]$version.consumable-and-not[bool]$version.currentEligible-and[bool]$version.projectPinEligible) 'version-stable-consumable'
$projectSchema=Get-Content -LiteralPath (Join-Path $candidateRoot 'PROJECT_CONFIG_SCHEMA.json') -Raw -Encoding utf8|ConvertFrom-Json
Assert-True ([string]$projectSchema.'$comment'-match'routine'-and[string]$projectSchema.'$comment'-match'not a secrecy or source-authorization policy') 'project-schema-declares-routine-exclusion-boundary'
Assert-True (@($projectSchema.properties.frameworkCapabilities.properties.PSObject.Properties.Name).Count-eq1-and@($projectSchema.properties.frameworkCapabilities.properties.PSObject.Properties.Name)[0]-ceq'KNOWLEDGE_REFERENCE') 'project-schema-single-optional-capability'

$plans=@(
    @('DOMAIN_OWNER','STANDARD',@('PLAN','IMPLEMENT','VERIFY'),'CODEX',43598),
    @('EXECUTOR','STANDARD',@('PLAN','IMPLEMENT'),'CODEX',33444),
    @('REVIEWER','CRITICAL',@('REVIEW'),'CODEX',37389),
    @('CONTROLLER','CRITICAL',@('RECOVER','PLAN'),'CODEX',50106),
    @('FRAMEWORK_MAINTAINER','CRITICAL',@('RECOVER','PLAN','IMPLEMENT','VERIFY','REVIEW','GIT','EXTERNAL'),'CODEX',58186))
$knowledgeModuleBytes=(Get-Item -LiteralPath (Join-Path $candidateRoot 'KNOWLEDGE_AND_REFERENCE.md')).Length
foreach($plan in $plans){try{$loaderText=& $loader -Role $plan[0] -Profile $plan[1] -Phase @($plan[2]) -HostName $plan[3] -AsJson;$loaderOk=$true}catch{$loaderOk=$false;$loaderText=''};Assert-True $loaderOk ("loader-exit|"+$plan[0]);$json=($loaderText-join"`n")|ConvertFrom-Json;Assert-True ([int64]$json.totalBytes-ge[int64]$plan[4]-and([int64]$json.totalBytes-[int64]$plan[4])-le6000) ("loader-fixed-plumbing-delta|"+$plan[0]);$empty=(& $loader -Role $plan[0] -Profile $plan[1] -Phase @($plan[2]) -HostName $plan[3] -Capability @() -AsJson|Out-String)|ConvertFrom-Json;Assert-True ([int64]$empty.totalBytes-eq[int64]$json.totalBytes-and(@($empty.modules.path)-join'|')-ceq(@($json.modules.path)-join'|')-and@($json.capabilities).Count-eq0) ("loader-default-empty-equivalent|"+$plan[0]);$enabled=(& $loader -Role $plan[0] -Profile $plan[1] -Phase @($plan[2]) -HostName $plan[3] -Capability 'KNOWLEDGE_REFERENCE' -AsJson|Out-String)|ConvertFrom-Json;Assert-True (@($enabled.modules|Where-Object{$_.path-ceq'KNOWLEDGE_AND_REFERENCE.md'}).Count-eq1-and@($enabled.capabilities).Count-eq1-and[string]$enabled.capabilities[0]-ceq'KNOWLEDGE_REFERENCE'-and([int64]$enabled.totalBytes-[int64]$json.totalBytes)-eq$knowledgeModuleBytes-and$knowledgeModuleBytes-le6000) ("loader-knowledge-once-and-payload|"+$plan[0])}
$loaderUnknown=$false;try{$null=& $loader -Role EXECUTOR -Profile STANDARD -Phase PLAN -HostName CODEX -Capability UNKNOWN -AsJson}catch{$loaderUnknown=$_.Exception.Message.Contains('LOAD_CAPABILITY_UNKNOWN')};Assert-True $loaderUnknown 'loader-unknown-capability-rejected'
$loaderDuplicate=$false;try{$null=& $loader -Role EXECUTOR -Profile STANDARD -Phase PLAN -HostName CODEX -Capability @('KNOWLEDGE_REFERENCE','KNOWLEDGE_REFERENCE') -AsJson}catch{$loaderDuplicate=$_.Exception.Message.Contains('LOAD_CAPABILITY_DUPLICATE')};Assert-True $loaderDuplicate 'loader-duplicate-capability-rejected'
$loaderUnsupported=$false;try{$null=& $loader -Role EXECUTOR -Profile STANDARD -Phase PLAN -HostName GENERIC -Capability KNOWLEDGE_REFERENCE -AsJson}catch{$loaderUnsupported=$_.Exception.Message.Contains('LOAD_CAPABILITY_HOST_UNSUPPORTED')};Assert-True $loaderUnsupported 'loader-unsupported-host-capability-rejected'
$recoveryText=Get-Content -LiteralPath (Join-Path $candidateRoot 'RECOVERY_CORE.md') -Raw -Encoding utf8;$projectControlText=Get-Content -LiteralPath (Join-Path $candidateRoot 'PROJECT_CONTROL.md') -Raw -Encoding utf8;$hostText=Get-Content -LiteralPath (Join-Path $candidateRoot 'HOST_CODEX.md') -Raw -Encoding utf8;$knowledgeContractText=Get-Content -LiteralPath (Join-Path $candidateRoot 'KNOWLEDGE_AND_REFERENCE.md') -Raw -Encoding utf8;$knowledgeCheckerText=Get-Content -LiteralPath $knowledgeChecker -Raw -Encoding utf8
Assert-True ($recoveryText.Contains('canonical capability') -and $recoveryText.Contains('load manifest identity') -and $recoveryText.Contains('QUERY_RESULT_CACHE_PROHIBITED') -and $hostText.Contains('QUERY_RESULT_CACHE_PROHIBITED') -and $knowledgeContractText.Contains('QUERY_RESULT_CACHE_PROHIBITED')) 'knowledge-query-result-cache-prohibited'
Assert-True ($recoveryText.Contains('role/profile/phase/host') -and $recoveryText.Contains('canonical capability') -and $projectControlText.Contains('role/profile/phase/host') -and $projectControlText.Contains('canonical capability') -and -not[regex]::IsMatch($recoveryText,'loader\u8F93\u5165\u53EA\u6709')) 'loader-capability-forwarding-documented'
Assert-True (-not$knowledgeCheckerText.Contains('[string]$IndexLocator')-and-not$knowledgeCheckerText.Contains('[string]$ExpectedProjectId')) 'knowledge-checker-has-no-caller-index-or-project-truth'

$temp=Join-Path ([IO.Path]::GetTempPath()) ('aiw-minimal-tests-'+[Guid]::NewGuid().ToString('N'))
try{
    New-Item -ItemType Directory -Path $temp|Out-Null
    $authRoot=Join-Path $temp 'auth';New-Item -ItemType Directory -Path (Join-Path $authRoot '.ai-workspace') -Force|Out-Null
    $controller=[ordered]@{schemaVersion=1;projectId='test';controllerId='controller-1';controllerEpoch=2;state='CURRENT'};$controllerPath=Join-Path $authRoot '.ai-workspace\controller.json';Write-Utf8 $controllerPath ($controller|ConvertTo-Json);$controllerIdentity=Get-Identity $controllerPath
    $base=[ordered]@{schemaVersion=1;frameworkVersion='1.6.0';taskId='T';profile='STANDARD';lifecycle='ACTIVE';owner='owner';issuer='owner';issuerRole='DOMAIN_OWNER';grantee='worker';bundle='IMPLEMENT_LOCAL';decisionClass='ROUTINE_LOCAL';userConfirmation='NOT_REQUIRED';reviewIndependence='NOT_APPLICABLE';delegatedGitCloser=$false;actions=@('SOURCE_WRITE');exactPaths=@('src/a.js');objectIdentities=@([ordered]@{path='src/a.js';identity='NEW'});invalidatesOn=@('TASK_CHANGE','OWNER_CHANGE','GRANTEE_CHANGE','ACTION_CHANGE','PATHSET_CHANGE','OBJECT_DRIFT','USER_DECISION_CHANGE')}
    $packagePath=Join-Path $authRoot 'auth.json';Write-Utf8 $packagePath ($base|ConvertTo-Json -Depth 10)
    $args=@('-PackagePath',$packagePath,'-ObservedActor','worker','-ObservedTaskId','T','-ObservedOwner','owner','-ObservedAction','SOURCE_WRITE','-ObservedPath','src/a.js','-ObservedIdentity','src/a.js=NEW')
    $r=Invoke-Ps $auth $args $authRoot;Assert-True ($r.Code-eq0) 'authorization-domain-owner-positive'
    $pc=[ordered]@{};foreach($k in $base.Keys){$pc[$k]=$base[$k]};$pc.issuer='controller-1';$pc.issuerRole='PROJECT_CONTROLLER';$pc.invalidatesOn=@($pc.invalidatesOn)+@('CONTROLLER_EPOCH_CHANGE');$pc.issuerControllerId='controller-1';$pc.issuerControllerEpoch=2;$pc.controllerControlIdentity=$controllerIdentity;Write-Utf8 $packagePath ($pc|ConvertTo-Json -Depth 10)
    $pcArgs=$args+@('-ControllerControlPath','.ai-workspace/controller.json');$r=Invoke-Ps $auth $pcArgs $authRoot;Assert-True ($r.Code-eq0) 'authorization-controller-positive'
    $pc.issuerControllerEpoch=1;Write-Utf8 $packagePath ($pc|ConvertTo-Json -Depth 10);$r=Invoke-Ps $auth $pcArgs $authRoot;Assert-True ($r.Code-ne0-and$r.Text.Contains('STALE_CONTROLLER_AUTHORIZATION')) 'authorization-stale-epoch-rejected'
    $pc.issuerControllerEpoch=2;$pc.frameworkVersion='1.5.2';Write-Utf8 $packagePath ($pc|ConvertTo-Json -Depth 10);$r=Invoke-Ps $auth $pcArgs $authRoot;Assert-True ($r.Code-ne0-and$r.Text.Contains('FRAMEWORK_VERSION')) 'authorization-old-version-rejected'

    $knowledgeRoot=Join-Path $temp 'knowledge-project';$knowledgeControlDir=Join-Path $knowledgeRoot '.ai-workspace';$knowledgeDir=Join-Path $knowledgeControlDir 'knowledge';New-Item -ItemType Directory -Path $knowledgeDir -Force|Out-Null
    $noConfig=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',('0|'+('0'*64)),'-ExpectedIndexIdentity',('0|'+('0'*64)));Assert-True ($noConfig.Code-ne0-and$noConfig.Text.Contains('REFERENCE_UNAVAILABLE')-and$noConfig.Text.Contains('LOCATOR_MISSING')) 'knowledge-no-project-config-default-off'
    $knowledgeConfigPath=Join-Path $knowledgeControlDir 'project.json';$knowledgeConfig=[ordered]@{schemaVersion=3;id='knowledge-project';displayName='Knowledge Project';controlPlaneLayout='repo-local';repositoryRoot='..';frameworkVersion='1.6.0';routineExcludedPaths=@();frameworkCapabilities=[pscustomobject]@{}};Write-Utf8 $knowledgeConfigPath ($knowledgeConfig|ConvertTo-Json -Depth 20);$emptyCapability=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',(Get-Identity $knowledgeConfigPath),'-ExpectedIndexIdentity',('0|'+('0'*64)));Assert-True ($emptyCapability.Code-ne0-and$emptyCapability.Text.Contains('CAPABILITY_DISABLED')) 'knowledge-empty-capability-default-off'
    $knowledgeConfig.frameworkCapabilities=[pscustomobject]@{KNOWLEDGE_REFERENCE=[pscustomobject]@{enabled=$false}};Write-Utf8 $knowledgeConfigPath ($knowledgeConfig|ConvertTo-Json -Depth 20);$falseCapability=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',(Get-Identity $knowledgeConfigPath),'-ExpectedIndexIdentity',('0|'+('0'*64)));Assert-True ($falseCapability.Code-ne0-and$falseCapability.Text.Contains('CAPABILITY_DISABLED')) 'knowledge-explicit-false-default-off'
    $knowledgeConfig.frameworkCapabilities=[pscustomobject]@{KNOWLEDGE_REFERENCE=[pscustomobject]@{enabled=$true}};Write-Utf8 $knowledgeConfigPath ($knowledgeConfig|ConvertTo-Json -Depth 20);$missingCapabilityLocator=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',(Get-Identity $knowledgeConfigPath),'-ExpectedIndexIdentity',('0|'+('0'*64)));Assert-True ($missingCapabilityLocator.Code-ne0-and$missingCapabilityLocator.Text.Contains('CAPABILITY_FIELDS')) 'knowledge-enabled-requires-config-locator'
    $knowledgeConfig.frameworkCapabilities=[pscustomobject]@{KNOWLEDGE_REFERENCE=[pscustomobject]@{enabled=$true;indexLocator='.ai-workspace/knowledge/missing.json'}};Write-Utf8 $knowledgeConfigPath ($knowledgeConfig|ConvertTo-Json -Depth 20);$missingKnowledge=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',(Get-Identity $knowledgeConfigPath),'-ExpectedIndexIdentity',('0|'+('0'*64)));Assert-True ($missingKnowledge.Code-ne0-and$missingKnowledge.Text.Contains('REFERENCE_UNAVAILABLE')-and$missingKnowledge.Text.Contains('LOCATOR_MISSING')) 'knowledge-no-library-fallback'
    $knowledgeIndexPath=Join-Path $knowledgeDir 'index.json';$knowledgeConfig.frameworkCapabilities=[pscustomobject]@{KNOWLEDGE_REFERENCE=[pscustomobject]@{enabled=$true;indexLocator='.ai-workspace/knowledge/index.json'}};Write-Utf8 $knowledgeConfigPath ($knowledgeConfig|ConvertTo-Json -Depth 20);$knowledgeConfigIdentity=Get-Identity $knowledgeConfigPath;$emptyKnowledge=[ordered]@{schemaVersion=1;projectId='knowledge-project';entries=@()};Write-Utf8 $knowledgeIndexPath ($emptyKnowledge|ConvertTo-Json -Depth 20);$emptyResult=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',$knowledgeConfigIdentity,'-ExpectedIndexIdentity',(Get-Identity $knowledgeIndexPath));Assert-True ($emptyResult.Code-ne0-and$emptyResult.Text.Contains('EMPTY_INDEX')) 'knowledge-empty-index-fallback'
    $referencePath=Join-Path $knowledgeDir 'reference.md';$authorityPath=Join-Path $knowledgeRoot 'authority.md';Write-Utf8 $referencePath 'reference';Write-Utf8 $authorityPath 'authority';$referenceIdentity=Get-Identity $referencePath;$authorityIdentity=Get-Identity $authorityPath
    $entries=@();foreach($id in @('D','B','A','C')){$entries+=[ordered]@{id=$id;state='CURRENT';title=('Title '+$id);summary=('Summary '+$id);locator='.ai-workspace/knowledge/reference.md';identity=$referenceIdentity;authorityLocator='authority.md';authorityIdentity=$authorityIdentity;verifiedAt='2026-08-15T00:00:00Z';invalidatesOn=@('LOCATOR_IDENTITY_CHANGE','AUTHORITY_IDENTITY_CHANGE');tokenEstimate=20}};$entries+=[ordered]@{id='OLD';state='STALE';title='Old';summary='Ignored stale entry';locator='../broken';identity=('0|'+('0'*64));authorityLocator='../broken';authorityIdentity=('0|'+('0'*64));verifiedAt='2026-08-15T00:00:00Z';invalidatesOn=@('LOCATOR_IDENTITY_CHANGE','AUTHORITY_IDENTITY_CHANGE');tokenEstimate=20};$knowledgeIndex=[ordered]@{schemaVersion=1;projectId='knowledge-project';entries=$entries};Write-Utf8 $knowledgeIndexPath ($knowledgeIndex|ConvertTo-Json -Depth 20);$knowledgeIdentity=Get-Identity $knowledgeIndexPath
    $available=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',$knowledgeConfigIdentity,'-ExpectedIndexIdentity',$knowledgeIdentity,'-AsJson');$availableJson=($available.Text|ConvertFrom-Json);Assert-True ($available.Code-eq0-and[string]$availableJson.status-ceq'REFERENCE_AVAILABLE'-and-not[bool]$availableJson.authority-and[bool]$availableJson.referenceOnly-and[string]$availableJson.projectConfigIdentity-ceq$knowledgeConfigIdentity-and@($availableJson.entries).Count-eq3-and(@($availableJson.entries.id)-join',')-ceq'A,B,C') 'knowledge-current-max3-stable-reference-only'
    $configDrift=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',('0|'+('0'*64)),'-ExpectedIndexIdentity',$knowledgeIdentity);Assert-True ($configDrift.Code-ne0-and$configDrift.Text.Contains('PROJECT_CONFIG_IDENTITY_DRIFT')) 'knowledge-project-config-drift-fallback'
    $indexDrift=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',$knowledgeConfigIdentity,'-ExpectedIndexIdentity',('0|'+('0'*64)));Assert-True ($indexDrift.Code-ne0-and$indexDrift.Text.Contains('INDEX_IDENTITY_DRIFT')) 'knowledge-index-drift-fallback'
    $knowledgeConfig.frameworkCapabilities.KNOWLEDGE_REFERENCE.indexLocator='.ai-workspace/knowledge/config-is-authority.json';Write-Utf8 $knowledgeConfigPath ($knowledgeConfig|ConvertTo-Json -Depth 20);$derivedLocator=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',(Get-Identity $knowledgeConfigPath),'-ExpectedIndexIdentity',$knowledgeIdentity);Assert-True ($derivedLocator.Code-ne0-and$derivedLocator.Text.Contains('LOCATOR_MISSING')) 'knowledge-index-locator-derived-only-from-config';$knowledgeConfig.frameworkCapabilities.KNOWLEDGE_REFERENCE.indexLocator='.ai-workspace/knowledge/index.json';Write-Utf8 $knowledgeConfigPath ($knowledgeConfig|ConvertTo-Json -Depth 20);$knowledgeConfigIdentity=Get-Identity $knowledgeConfigPath
    $invalidEntry=$knowledgeIndex|ConvertTo-Json -Depth 20|ConvertFrom-Json;$invalidEntry.entries[0].locator=1;Write-Utf8 $knowledgeIndexPath ($invalidEntry|ConvertTo-Json -Depth 20);$invalidLocatorType=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',$knowledgeConfigIdentity,'-ExpectedIndexIdentity',(Get-Identity $knowledgeIndexPath));Assert-True ($invalidLocatorType.Code-ne0-and$invalidLocatorType.Text.Contains('ENTRY_VALUES')) 'knowledge-entry-locator-must-be-string'
    $invalidEntry=$knowledgeIndex|ConvertTo-Json -Depth 20|ConvertFrom-Json;$invalidEntry.entries[0].authorityLocator=2;Write-Utf8 $knowledgeIndexPath ($invalidEntry|ConvertTo-Json -Depth 20);$invalidAuthorityType=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',$knowledgeConfigIdentity,'-ExpectedIndexIdentity',(Get-Identity $knowledgeIndexPath));Assert-True ($invalidAuthorityType.Code-ne0-and$invalidAuthorityType.Text.Contains('ENTRY_VALUES')) 'knowledge-entry-authority-locator-must-be-string'
    $invalidEntry=$knowledgeIndex|ConvertTo-Json -Depth 20|ConvertFrom-Json;$invalidEntry.entries[0].verifiedAt='2026-99-99T99:99:99Z';Write-Utf8 $knowledgeIndexPath ($invalidEntry|ConvertTo-Json -Depth 20);$invalidDate=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',$knowledgeConfigIdentity,'-ExpectedIndexIdentity',(Get-Identity $knowledgeIndexPath));Assert-True ($invalidDate.Code-ne0-and$invalidDate.Text.Contains('ENTRY_VALUES')) 'knowledge-entry-verified-at-real-date'
    $nonCurrentEmptyRejected=$true;foreach($state in @('STALE','HISTORICAL')){foreach($field in @('locator','authorityLocator')){$invalidEntry=$knowledgeIndex|ConvertTo-Json -Depth 20|ConvertFrom-Json;$invalidEntry.entries[-1].state=$state;$invalidEntry.entries[-1].$field='';Write-Utf8 $knowledgeIndexPath ($invalidEntry|ConvertTo-Json -Depth 20);$invalidNonCurrent=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',$knowledgeConfigIdentity,'-ExpectedIndexIdentity',(Get-Identity $knowledgeIndexPath));if($invalidNonCurrent.Code-eq0-or-not$invalidNonCurrent.Text.Contains('ENTRY_VALUES')){$nonCurrentEmptyRejected=$false}}};Assert-True $nonCurrentEmptyRejected 'knowledge-noncurrent-empty-locators-rejected'
    Write-Utf8 $knowledgeIndexPath ($knowledgeIndex|ConvertTo-Json -Depth 20);$knowledgeIdentity=Get-Identity $knowledgeIndexPath;Write-Utf8 $referencePath 'reference changed';$referenceDrift=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',$knowledgeConfigIdentity,'-ExpectedIndexIdentity',$knowledgeIdentity);Assert-True ($referenceDrift.Code-ne0-and$referenceDrift.Text.Contains('ENTRY_IDENTITY_DRIFT')) 'knowledge-reference-drift-fallback';Write-Utf8 $referencePath 'reference'
    Write-Utf8 $authorityPath 'authority changed';$authorityConflict=Invoke-Ps $knowledgeChecker @('-ProjectRoot',$knowledgeRoot,'-ExpectedProjectConfigIdentity',$knowledgeConfigIdentity,'-ExpectedIndexIdentity',$knowledgeIdentity);Assert-True ($authorityConflict.Code-ne0-and$authorityConflict.Text.Contains('AUTHORITY_CONFLICT')) 'knowledge-authority-conflict-fallback'

    $upgradeText=Get-Content -LiteralPath $upgrade -Raw -Encoding utf8
    Assert-True ($upgradeText.Contains('staging preserved at $staging')-and$upgradeText.Contains('Complete-UpgradeTransaction')-and-not$upgradeText.Contains('Remove-Item')-and-not$upgradeText.Contains('[IO.Directory]::Delete')) 'upgrade-preserves-recovery-material-without-automatic-cleanup'
    Assert-True (-not(Test-Path -LiteralPath (Join-Path $candidateRoot 'scripts\ProtectedPolicy.psm1'))) 'retired-policy-module-removed'
    Assert-True (-not$upgradeText.Contains('.framework-1.6-upgrade-transaction')-and-not$upgradeText.Contains('Minimal16')) 'single-upgrade-transaction-engine'
    $releaseContractText=(@(Get-ChildItem -LiteralPath $candidateRoot -Recurse -File -Filter '*.md'|ForEach-Object{Get-Content -LiteralPath $_.FullName -Raw -Encoding utf8}) -join "`n")
    $retiredPolicyTerms='(?i)protected[- ]policy|protectedpolicy|protection policy|protected boundar|protected paths:|protected visibility-read-hash-diff-index-write|schema3\u4FDD\u62A4\u7B56\u7565|\u53D7\u4FDD\u62A4|\u4FDD\u62A4\u5BF9\u8C61|\u4FDD\u62A4\u8FB9\u754C|\u5FC5\u987B\u4FDD\u62A4|\u516D\u80FD\u529B\u5B89\u5168\u7B56\u7565'
    Assert-True (-not ([regex]::IsMatch($releaseContractText,$retiredPolicyTerms))) 'retired-policy-contract-zero-current-doc-reference'

    if(-not$SkipRootMigration){
        $ws=New-IsolatedWorkspace (Join-Path $temp 'integration') $candidateRoot
        $repoDefault=Join-Path $temp 'repo-default';New-GitRepo $repoDefault;$r=Register-Project $register $ws $repoDefault 'default-project' '' '';Assert-True ($r.Code-eq0-and(Get-Content -LiteralPath (Join-Path $repoDefault '.ai-workspace\project.json') -Raw|ConvertFrom-Json).schemaVersion-eq2) 'register-current-1.4.1-compatible'
        $repo152=Join-Path $temp 'repo-152';New-GitRepo $repo152;$r=Register-Project $register $ws $repo152 'explicit-152' '1.5.2' '';Assert-True ($r.Code-eq0) 'register-explicit-1.5.2-compatible'
        $repoMissing=Join-Path $temp 'repo-missing-controller';New-GitRepo $repoMissing;$r=Register-Project $register $ws $repoMissing 'missing-controller' '1.6.0' '';Assert-True ($r.Code-ne0) 'register-1.6-requires-controller'
        $repo16=Join-Path $temp 'repo-16';New-GitRepo $repo16;$r=Register-Project $register $ws $repo16 'project-16' '1.6.0' 'controller-16';Assert-True ($r.Code-eq0-and(Test-Path -LiteralPath (Join-Path $repo16 '.ai-workspace\controller.json'))) 'register-1.6-exact9'
        $repo16ConfigPath=Join-Path $repo16 '.ai-workspace\project.json';$repo16ConfigRaw=Get-Content -LiteralPath $repo16ConfigPath -Raw -Encoding utf8;$repo16Config=$repo16ConfigRaw|ConvertFrom-Json;$repo16Config.frameworkCapabilities=[pscustomobject]@{KNOWLEDGE_REFERENCE=[pscustomobject]@{enabled=$true;indexLocator='.ai-workspace/knowledge/index.json'}};Write-Utf8 $repo16ConfigPath ($repo16Config|ConvertTo-Json -Depth 20);$enabledRegistered=Register-Project $register $ws $repo16 'project-16' '1.6.0' 'controller-16';Assert-True ($enabledRegistered.Code-eq0-and$enabledRegistered.Text.Contains('ALREADY_REGISTERED')) 'register-1.6-knowledge-capability-valid';$repo16Config.frameworkCapabilities=[pscustomobject]@{unexpected=$true};Write-Utf8 $repo16ConfigPath ($repo16Config|ConvertTo-Json -Depth 20);$invalidRegistered=Register-Project $register $ws $repo16 'project-16' '1.6.0' 'controller-16';Assert-True ($invalidRegistered.Code-ne0) 'register-1.6-unknown-capability-rejected';$repo16Config.frameworkCapabilities=[pscustomobject]@{KNOWLEDGE_REFERENCE=[pscustomobject]@{enabled=$true}};Write-Utf8 $repo16ConfigPath ($repo16Config|ConvertTo-Json -Depth 20);$missingLocatorRegistered=Register-Project $register $ws $repo16 'project-16' '1.6.0' 'controller-16';Assert-True ($missingLocatorRegistered.Code-ne0) 'register-1.6-enabled-knowledge-requires-locator';Write-Utf8 $repo16ConfigPath $repo16ConfigRaw

        $saved152=$null
        foreach($source in @('1.4.1','1.5.0','1.5.1','1.5.2')){
            $id='upgrade-'+$source.Replace('.','-');$repo=Join-Path $temp $id;New-GitRepo $repo;$r=Register-Project $register $ws $repo $id $source '';Assert-True ($r.Code-eq0) ("upgrade-source-register|"+$source)
            $bootstrap=Join-Path $repo '.ai-workspace\BOOTSTRAP.md';$text=Get-Content -LiteralPath $bootstrap -Raw -Encoding utf8;$text=$text.Replace('<!-- PROJECT-CUSTOM:END -->',"kept-$source`n<!-- PROJECT-CUSTOM:END -->");Write-Utf8 $bootstrap $text
            $migration=New-Migration $repo $id @('src/config/levels/level_test2.js')
            $upgradeArgs=@('-ProjectId',$id,'-RepositoryPath',$repo,'-ToVersion','1.6.0','-ControllerId',('controller-'+$id),'-RoutineExcludedPathsMigrationPath',$migration.Path,'-ExpectedRoutineExcludedPathsMigrationIdentity',$migration.Identity,'-WorkspaceRoot',$ws)
            $preview=Invoke-Ps $upgrade $upgradeArgs;Assert-True ($preview.Code-eq0-and$preview.Text.Contains('WHAT_IF')) ("upgrade-preview|"+$source)
            if($source-ceq'1.5.2'){$saved152=[ordered]@{Repo=$repo;Id=$id;Migration=$migration;Args=$upgradeArgs;OldProject=Get-Content -LiteralPath (Join-Path $repo '.ai-workspace\project.json') -Raw -Encoding utf8;OldBootstrap=Get-Content -LiteralPath $bootstrap -Raw -Encoding utf8;NewProject='';NewBootstrap='';NewController=''}}
            $apply=Invoke-Ps $upgrade ($upgradeArgs+@('-Apply'));$config=Get-Content -LiteralPath (Join-Path $repo '.ai-workspace\project.json') -Raw|ConvertFrom-Json;$recovery=@(Get-ChildItem -LiteralPath (Join-Path $repo '.ai-workspace') -Directory -Filter '.framework-upgrade-recovery-*');Assert-True ($apply.Code-eq0-and[int]$config.schemaVersion-eq3-and[string]$config.frameworkVersion-ceq'1.6.0'-and@($config.routineExcludedPaths).Count-eq1-and@($config.frameworkCapabilities.PSObject.Properties).Count-eq0-and-not(Test-Path -LiteralPath (Join-Path $repo '.ai-workspace\knowledge'))-and$recovery.Count-eq1-and(Get-Content -LiteralPath $bootstrap -Raw -Encoding utf8).Contains("kept-$source")) ("upgrade-apply-default-knowledge-disabled|"+$source)
            if($source-ceq'1.5.2'){$saved152.NewProject=Get-Content -LiteralPath (Join-Path $repo '.ai-workspace\project.json') -Raw -Encoding utf8;$saved152.NewBootstrap=Get-Content -LiteralPath $bootstrap -Raw -Encoding utf8;$saved152.NewController=Get-Content -LiteralPath (Join-Path $repo '.ai-workspace\controller.json') -Raw -Encoding utf8}
            $repeat=Invoke-Ps $upgrade ($upgradeArgs+@('-Apply'));Assert-True ($repeat.Code-eq0-and$repeat.Text.Contains('ALREADY_UPGRADED')) ("upgrade-repeat|"+$source)
        }

        $oldTargetRepo=Join-Path $temp 'old-target';New-GitRepo $oldTargetRepo;$r=Register-Project $register $ws $oldTargetRepo 'old-target' '1.4.1' ''
        $oldTarget=Invoke-Ps $upgrade @('-ProjectId','old-target','-RepositoryPath',$oldTargetRepo,'-ToVersion','1.5.2','-WorkspaceRoot',$ws,'-Apply')
        $oldTargetConfig=Get-Content -LiteralPath (Join-Path $oldTargetRepo '.ai-workspace\project.json') -Raw|ConvertFrom-Json
        $oldTargetRecovery=@(Get-ChildItem -LiteralPath (Join-Path $oldTargetRepo '.ai-workspace') -Directory -Filter '.framework-upgrade-recovery-*')
        Assert-True ($r.Code-eq0-and$oldTarget.Code-eq0-and[string]$oldTargetConfig.frameworkVersion-ceq'1.5.2'-and$oldTargetRecovery.Count-eq1) 'upgrade-old-target-compatibility'
        $oldTargetActive=Join-Path $oldTargetRepo '.ai-workspace\.framework-upgrade-transaction';[IO.Directory]::Move($oldTargetRecovery[0].FullName,$oldTargetActive);[IO.File]::Copy((Join-Path $oldTargetActive 'old\BOOTSTRAP.md'),(Join-Path $oldTargetRepo '.ai-workspace\BOOTSTRAP.md'),$true)
        $oldTargetRecover=Invoke-Ps $upgrade @('-ProjectId','old-target','-RepositoryPath',$oldTargetRepo,'-ToVersion','1.5.2','-WorkspaceRoot',$ws,'-Apply');$oldTargetRolledBack=Get-Content -LiteralPath (Join-Path $oldTargetRepo '.ai-workspace\project.json') -Raw|ConvertFrom-Json
        Assert-True ($oldTargetRecover.Code-eq0-and$oldTargetRecover.Text.Contains('RECOVERED_ROLLBACK')-and[string]$oldTargetRolledBack.frameworkVersion-ceq'1.4.1'-and-not(Test-Path -LiteralPath $oldTargetActive)) 'upgrade-old-target-shared-recovery-engine'

        $prepRepo=Join-Path $temp 'abandoned-prep';New-GitRepo $prepRepo;$r=Register-Project $register $ws $prepRepo 'abandoned-prep' '1.5.2' '';$prepMigration=New-Migration $prepRepo 'abandoned-prep' @();$prepRoot=Join-Path $prepRepo '.ai-workspace\.fwu-prep-manual';Write-Utf8 (Join-Path $prepRoot 'sentinel.txt') 'preserve me';$prepResult=Invoke-Ps $upgrade @('-ProjectId','abandoned-prep','-RepositoryPath',$prepRepo,'-ToVersion','1.6.0','-ControllerId','controller-prep','-RoutineExcludedPathsMigrationPath',$prepMigration.Path,'-ExpectedRoutineExcludedPathsMigrationIdentity',$prepMigration.Identity,'-WorkspaceRoot',$ws,'-Apply');Assert-True ($r.Code-eq0-and$prepResult.Code-ne0-and(Test-Path -LiteralPath (Join-Path $prepRoot 'sentinel.txt') -PathType Leaf)-and-not(Test-Path -LiteralPath (Join-Path $prepRepo '.ai-workspace\controller.json'))) 'upgrade-abandoned-preparation-preserved'

        $watchRepo=Join-Path $temp 'watchdog';New-GitRepo $watchRepo;$r=Register-Project $register $ws $watchRepo 'watchdog' '1.5.2' ''
        $watchBootstrap=Join-Path $watchRepo '.ai-workspace\BOOTSTRAP.md';$watchText=Get-Content -LiteralPath $watchBootstrap -Raw -Encoding utf8;$watchText=$watchText.Replace('<!-- PROJECT-CUSTOM:END -->',(('x'*33554432)+"`n<!-- PROJECT-CUSTOM:END -->"));Write-Utf8 $watchBootstrap $watchText
        $watchMigration=New-Migration $watchRepo 'watchdog' @();$watchProject=Join-Path $watchRepo '.ai-workspace\project.json';$watchController=Join-Path $watchRepo '.ai-workspace\controller.json';$watchTransaction=Join-Path $watchRepo '.ai-workspace\.framework-upgrade-transaction'
        $watchState=[ordered]@{Killed=$false};$watchArgs=@('-NoProfile','-ExecutionPolicy','Bypass','-File',$upgrade,'-ProjectId','watchdog','-RepositoryPath',$watchRepo,'-ToVersion','1.6.0','-ControllerId','controller-watchdog','-RoutineExcludedPathsMigrationPath',$watchMigration.Path,'-ExpectedRoutineExcludedPathsMigrationIdentity',$watchMigration.Identity,'-WorkspaceRoot',$ws,'-Apply')
        $watchProcess=Start-Process -FilePath powershell.exe -ArgumentList $watchArgs -PassThru -WindowStyle Hidden
        $deadline=[DateTime]::UtcNow.AddSeconds(60)
        while(-not$watchProcess.HasExited-and[DateTime]::UtcNow-lt$deadline){
            try{$observedVersion=[string](Get-Content -LiteralPath $watchProject -Raw|ConvertFrom-Json).frameworkVersion}catch{$observedVersion=''}
            if($observedVersion-ceq'1.6.0'){$watchProcess.Kill();$watchState.Killed=$true;break}
            Start-Sleep -Milliseconds 1
        }
        if(-not$watchProcess.HasExited){$watchProcess.WaitForExit(10000)|Out-Null}
        if(-not$watchProcess.HasExited){$watchProcess.Kill();throw'watchdog upgrade timeout'}
        $watchPartial=(Test-Path -LiteralPath $watchTransaction -PathType Container)-and-not(Test-Path -LiteralPath $watchController)
        $watchVersion=try{[string](Get-Content -LiteralPath $watchProject -Raw|ConvertFrom-Json).frameworkVersion}catch{''}
        Assert-True ([bool]$watchState.Killed-and$watchPartial-and$watchVersion-ceq'1.6.0') 'upgrade-watchdog-killed-after-early-replace'
        $watchRecover=Invoke-Ps $upgrade @('-ProjectId','watchdog','-RepositoryPath',$watchRepo,'-ToVersion','1.6.0','-ControllerId','controller-watchdog','-RoutineExcludedPathsMigrationPath',$watchMigration.Path,'-ExpectedRoutineExcludedPathsMigrationIdentity',$watchMigration.Identity,'-WorkspaceRoot',$ws,'-Apply')
        $watchRecoveredVersion=[string](Get-Content -LiteralPath $watchProject -Raw|ConvertFrom-Json).frameworkVersion
        $watchRecovery=@(Get-ChildItem -LiteralPath (Join-Path $watchRepo '.ai-workspace') -Directory -Filter '.framework-upgrade-recovery-*');Assert-True ($watchRecover.Code-eq0-and$watchRecover.Text.Contains('RECOVERED_ROLLBACK')-and$watchRecoveredVersion-ceq'1.5.2'-and-not(Test-Path -LiteralPath $watchTransaction)-and$watchRecovery.Count-eq1) 'upgrade-watchdog-recovery-rollback-retains-material'

        $mixedRoot=Join-Path $saved152.Repo '.ai-workspace\.framework-upgrade-transaction';$mixedState=New-TransactionFixture $mixedRoot $saved152;Write-Utf8 (Join-Path $saved152.Repo '.ai-workspace\BOOTSTRAP.md') $saved152.OldBootstrap
        $mixedRecovery=Invoke-Ps $upgrade ($saved152.Args+@('-Apply'));$mixedProject=Get-Content -LiteralPath (Join-Path $saved152.Repo '.ai-workspace\project.json') -Raw -Encoding utf8;$mixedBootstrap=Get-Content -LiteralPath (Join-Path $saved152.Repo '.ai-workspace\BOOTSTRAP.md') -Raw -Encoding utf8;$mixedRetained=Join-Path $saved152.Repo ('.ai-workspace\.framework-upgrade-recovery-'+[string]$mixedState.transactionId)
        Assert-True ($mixedRecovery.Code-eq0-and$mixedRecovery.Text.Contains('RECOVERED_ROLLBACK')-and$mixedProject-ceq$saved152.OldProject-and$mixedBootstrap-ceq$saved152.OldBootstrap-and-not(Test-Path -LiteralPath (Join-Path $saved152.Repo '.ai-workspace\controller.json'))-and-not(Test-Path -LiteralPath $mixedRoot)-and(Test-Path -LiteralPath $mixedRetained -PathType Container)) 'upgrade-mixed-recovery-rolls-back-and-retains-material'

        $unknownRoot=Join-Path $saved152.Repo '.ai-workspace\.framework-upgrade-transaction';$null=New-TransactionFixture $unknownRoot $saved152
        $unknownConfig=Get-Content -LiteralPath (Join-Path $saved152.Repo '.ai-workspace\project.json') -Raw|ConvertFrom-Json;$unknownConfig|Add-Member -NotePropertyName unknown -NotePropertyValue $true;Write-Utf8 (Join-Path $saved152.Repo '.ai-workspace\project.json') ($unknownConfig|ConvertTo-Json -Depth 20)
        $unknownRecovery=Invoke-Ps $upgrade ($saved152.Args+@('-Apply'));Assert-True ($unknownRecovery.Code-ne0-and(Test-Path -LiteralPath $unknownRoot -PathType Container)) 'upgrade-unknown-live-bytes-preserves-transaction'

        $reparseRepo=Join-Path $temp 'reparse-source';New-GitRepo $reparseRepo;$r=Register-Project $register $ws $reparseRepo 'reparse-source' '1.5.2' '';$junctionTarget=Join-Path $temp 'junction-target';New-Item -ItemType Directory -Path $junctionTarget|Out-Null;$junction=Join-Path $reparseRepo '.ai-workspace\reparse-sentinel';New-Item -ItemType Junction -Path $junction -Target $junctionTarget|Out-Null;$reparseMigration=New-Migration $reparseRepo 'reparse-source' @();$reparseResult=Invoke-Ps $upgrade @('-ProjectId','reparse-source','-RepositoryPath',$reparseRepo,'-ToVersion','1.6.0','-ControllerId','controller-reparse','-RoutineExcludedPathsMigrationPath',$reparseMigration.Path,'-ExpectedRoutineExcludedPathsMigrationIdentity',$reparseMigration.Identity,'-WorkspaceRoot',$ws,'-Apply');Assert-True ($reparseResult.Code-ne0-and-not(Test-Path -LiteralPath (Join-Path $reparseRepo '.ai-workspace\controller.json'))) 'upgrade-reparse-source-no-write'

        $routineRepo=$repo16;$configPath=Join-Path $routineRepo '.ai-workspace\project.json';$config=Get-Content -LiteralPath $configPath -Raw|ConvertFrom-Json;$config.routineExcludedPaths=@('scope/excluded.txt');$config.frameworkCapabilities=[pscustomobject]@{KNOWLEDGE_REFERENCE=[pscustomobject]@{enabled=$true;indexLocator='.ai-workspace/knowledge/index.json'}};Write-Utf8 $configPath ($config|ConvertTo-Json -Depth 20);$identity=Get-Identity $configPath
        Write-Utf8 (Join-Path $routineRepo 'scope\excluded.txt') 'baseline excluded';Write-Utf8 (Join-Path $routineRepo 'scope\public.txt') 'baseline public';&git -C $routineRepo add -- 'scope/excluded.txt' 'scope/public.txt';&git -C $routineRepo commit -qm baseline;Write-Utf8 (Join-Path $routineRepo 'scope\excluded.txt') 'changed excluded';Write-Utf8 (Join-Path $routineRepo 'scope\public.txt') 'changed public'
        $bounded=Invoke-Ps $safeGit @('-ProjectRoot',$routineRepo,'-Operation','STATUS','-AllowPath','scope','-ExpectedProjectConfigIdentity',$identity);Assert-True ($bounded.Code-eq0-and$bounded.Text.Contains('scope/public.txt')-and-not$bounded.Text.Contains('scope/excluded.txt')) 'routine-status-default-excludes-configured-path'
        Assert-True ($bounded.Code-eq0) 'safe-git-accepts-valid-knowledge-capability'
        $override=Invoke-Ps $safeGit @('-ProjectRoot',$routineRepo,'-Operation','STATUS','-AllowPath','scope/excluded.txt','-ExpectedProjectConfigIdentity',$identity,'-IncludeRoutineExcluded');Assert-True ($override.Code-eq0-and$override.Text.Contains('scope/excluded.txt')) 'routine-exclusion-exact-override'
        $broadOverride=Invoke-Ps $safeGit @('-ProjectRoot',$routineRepo,'-Operation','STATUS','-AllowPath','scope','-ExpectedProjectConfigIdentity',$identity,'-IncludeRoutineExcluded');Assert-True ($broadOverride.Code-ne0-and$broadOverride.Text.Contains('EXCLUDED_OVERRIDE_MUST_BE_EXACT')) 'routine-exclusion-nonexact-override-rejected'
        $literalMetaOk=$true;foreach($invalidRoutinePath in @('assets/**','assets/?','assets/<draft>','assets/>','assets/"draft"','assets/a|b')){$config.routineExcludedPaths=@($invalidRoutinePath);Write-Utf8 $configPath ($config|ConvertTo-Json -Depth 20);$invalidMeta=Invoke-Ps $safeGit @('-ProjectRoot',$routineRepo,'-Operation','STATUS','-AllowPath','scope','-ExpectedProjectConfigIdentity',(Get-Identity $configPath));if($invalidMeta.Code-eq0-or-not$invalidMeta.Text.Contains('ROUTINE_PATH_LITERAL_METACHAR')-or-not$invalidMeta.Text.Contains('"launched":false')){$literalMetaOk=$false}};Assert-True $literalMetaOk 'routine-exclusion-literal-metacharacters-unverified-no-launch'
        $config.routineExcludedPaths=@('../outside');Write-Utf8 $configPath ($config|ConvertTo-Json -Depth 20);$invalidIdentity=Get-Identity $configPath;$invalid=Invoke-Ps $safeGit @('-ProjectRoot',$routineRepo,'-Operation','STATUS','-AllowPath','public.txt','-ExpectedProjectConfigIdentity',$invalidIdentity);Assert-True ($invalid.Code-ne0-and$invalid.Text.Contains('UNVERIFIED')) 'routine-exclusion-invalid-config-unverified'
        $config.routineExcludedPaths=@('scope/excluded.txt');Write-Utf8 $configPath ($config|ConvertTo-Json -Depth 20);$identity=Get-Identity $configPath;$oldGitIndex=[Environment]::GetEnvironmentVariable('GIT_INDEX_FILE','Process');try{[Environment]::SetEnvironmentVariable('GIT_INDEX_FILE',$routineRepo,'Process');$failedGit=Invoke-Ps $safeGit @('-ProjectRoot',$routineRepo,'-Operation','INDEX','-AllowPath','scope/public.txt','-ExpectedProjectConfigIdentity',$identity)}finally{[Environment]::SetEnvironmentVariable('GIT_INDEX_FILE',$oldGitIndex,'Process')};Assert-True ($failedGit.Code-ne0-and$failedGit.Text.Contains('GIT_COMMAND_FAILED')-and$failedGit.Text.Contains('"launched":true')) 'routine-git-command-failure-honest-unverified'

        $structuralRepo=Join-Path $temp 'structural-routine-data';New-GitRepo $structuralRepo;$r=Register-Project $register $ws $structuralRepo 'structural-routine-data' '1.5.2' '';$structuralMigration=New-Migration $structuralRepo 'structural-routine-data' @('../outside');$structuralArgs=@('-ProjectId','structural-routine-data','-RepositoryPath',$structuralRepo,'-ToVersion','1.6.0','-ControllerId','controller-structural','-RoutineExcludedPathsMigrationPath',$structuralMigration.Path,'-ExpectedRoutineExcludedPathsMigrationIdentity',$structuralMigration.Identity,'-WorkspaceRoot',$ws,'-Apply');$structuralApply=Invoke-Ps $upgrade $structuralArgs;$structuralRepeat=Invoke-Ps $upgrade $structuralArgs;$structuralConfigPath=Join-Path $structuralRepo '.ai-workspace\project.json';$structuralConfig=Get-Content -LiteralPath $structuralConfigPath -Raw|ConvertFrom-Json;Assert-True ($r.Code-eq0-and$structuralApply.Code-eq0-and$structuralRepeat.Code-eq0-and$structuralRepeat.Text.Contains('ALREADY_UPGRADED')-and[string]$structuralConfig.routineExcludedPaths[0]-ceq'../outside') 'routine-exclusions-structural-producer-and-repeat-health'
        $structuralUse=Invoke-Ps $safeGit @('-ProjectRoot',$structuralRepo,'-Operation','STATUS','-AllowPath','public.txt','-ExpectedProjectConfigIdentity',(Get-Identity $structuralConfigPath));Assert-True ($structuralUse.Code-ne0-and$structuralUse.Text.Contains('UNVERIFIED')) 'routine-exclusion-structural-data-rejected-at-use-site'

        $knowledgeUpgradeRepo=Join-Path $temp 'knowledge-upgrade';New-GitRepo $knowledgeUpgradeRepo;$r=Register-Project $register $ws $knowledgeUpgradeRepo 'knowledge-upgrade' '1.5.2' '';$knowledgeMigration=New-Migration $knowledgeUpgradeRepo 'knowledge-upgrade' @();$knowledgeUpgradeArgs=@('-ProjectId','knowledge-upgrade','-RepositoryPath',$knowledgeUpgradeRepo,'-ToVersion','1.6.0','-ControllerId','controller-knowledge','-RoutineExcludedPathsMigrationPath',$knowledgeMigration.Path,'-ExpectedRoutineExcludedPathsMigrationIdentity',$knowledgeMigration.Identity,'-WorkspaceRoot',$ws,'-Apply');$knowledgeApply=Invoke-Ps $upgrade $knowledgeUpgradeArgs;$knowledgeConfigPath=Join-Path $knowledgeUpgradeRepo '.ai-workspace\project.json';$knowledgeConfig=Get-Content -LiteralPath $knowledgeConfigPath -Raw|ConvertFrom-Json;$knowledgeConfig.frameworkCapabilities=[pscustomobject]@{KNOWLEDGE_REFERENCE=[pscustomobject]@{enabled=$true;indexLocator='.ai-workspace/knowledge/index.json'}};Write-Utf8 $knowledgeConfigPath ($knowledgeConfig|ConvertTo-Json -Depth 20);$knowledgeRepeat=Invoke-Ps $upgrade $knowledgeUpgradeArgs;Assert-True ($r.Code-eq0-and$knowledgeApply.Code-eq0-and$knowledgeRepeat.Code-eq0-and$knowledgeRepeat.Text.Contains('ALREADY_UPGRADED')) 'upgrade-repeat-accepts-valid-knowledge-capability'

        $driftRepo=Join-Path $temp 'migration-drift';New-GitRepo $driftRepo;$r=Register-Project $register $ws $driftRepo 'migration-drift' '1.5.2' '';$migration=New-Migration $driftRepo 'migration-drift' @();Write-Utf8 $migration.Path ((Get-Content -LiteralPath $migration.Path -Raw)+' ');$drift=Invoke-Ps $upgrade @('-ProjectId','migration-drift','-RepositoryPath',$driftRepo,'-ToVersion','1.6.0','-ControllerId','controller-drift','-RoutineExcludedPathsMigrationPath',$migration.Path,'-ExpectedRoutineExcludedPathsMigrationIdentity',$migration.Identity,'-WorkspaceRoot',$ws,'-Apply');Assert-True ($drift.Code-ne0-and-not(Test-Path -LiteralPath (Join-Path $driftRepo '.ai-workspace\controller.json'))) 'upgrade-migration-drift-no-write'
    }

    $forbidden=@('check-controller-route','check-remote-batch','resolve-resource-binding','controller-revocations','check-peer-task-reuse','PreviousLedger','COMPENSATION')
    $activeCode=@(Get-ChildItem -LiteralPath (Join-Path $candidateRoot 'scripts') -Recurse -File -Include *.ps1,*.json);$activeCode+=@(Get-Item -LiteralPath (Join-Path $rootDraft 'scripts\register-project.ps1'),(Join-Path $rootDraft 'scripts\upgrade-project.ps1'))
    foreach($term in $forbidden){$hits=@($activeCode|Select-String -Pattern $term -SimpleMatch);Assert-True ($hits.Count-eq0) ("old-mechanism-zero-code|"+$term)}
    $allText=@(Get-ChildItem -LiteralPath $candidateRoot -Recurse -File|Where-Object{$_.FullName-cne$selfPath}|ForEach-Object{Get-Content -LiteralPath $_.FullName -Raw -Encoding utf8});$allText+=@($rootExpected|ForEach-Object{Get-Content -LiteralPath (Join-Path $rootDraft $_) -Raw -Encoding utf8});$allText=$allText-join"`n"
    Assert-True (-not$allText.Contains('lean-candidate/')-and-not$allText.Contains('candidate/')-and-not$allText.Contains('lean-root-scripts/')-and-not$allText.Contains('root-scripts/')) 'old-tree-zero-import-path'

    if(-not$SkipManifest){
        $manifest=Get-Content -LiteralPath (Join-Path $candidateRoot 'RELEASE_MANIFEST.json') -Raw|ConvertFrom-Json
        [string[]]$payload=@($actual|Where-Object{$_-cne'RELEASE_MANIFEST.json'});[Array]::Sort($payload,[StringComparer]::Ordinal)
        $rows=@();$total=[int64]0;foreach($path in $payload){$full=Join-Path $candidateRoot $path;$bytes=[IO.File]::ReadAllBytes($full);$total+=$bytes.Length;$rows+=("$path|$($bytes.Length)|"+(Get-Identity $full).Split('|')[1])}
        $canonicalBytes=$utf8.GetBytes(($rows-join"`n"));$sha=[Security.Cryptography.SHA256]::Create();try{$canonical=([BitConverter]::ToString($sha.ComputeHash($canonicalBytes))).Replace('-','')}finally{$sha.Dispose()}
        Assert-True ([int]$manifest.fileCount-eq$payload.Count-and[int64]$manifest.totalBytes-eq$total-and[string]$manifest.canonical-ceq$canonical) 'release-manifest-canonical'
    }
}
finally{
    if(Test-Path -LiteralPath $temp){Get-ChildItem -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue|ForEach-Object{try{$_.Attributes=[IO.FileAttributes]::Normal}catch{}};Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue}
}

Write-Output ("RESULT|"+$script:passed+"/"+$script:passed+" passed|scope=Framework-1.6.0-stable|lifecycle=STABLE")
