#requires -Version 7.0
[CmdletBinding()]
param([string]$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$upgradePath = Join-Path $RepositoryRoot 'scripts\upgrade-project.ps1'
$registerPath = Join-Path $RepositoryRoot 'scripts\register-project.ps1'
$matrixPath = Join-Path $RepositoryRoot 'framework\versions\1.15.1\MIGRATION_MATRIX.md'
$failures = New-Object 'System.Collections.Generic.List[string]'
$passes = 0

function Confirm([bool]$Condition,[string]$Name){
    if($Condition){$script:passes++;return}
    $script:failures.Add($Name)
}

function Get-TestIdentity([string]$Path){
    $bytes=[IO.File]::ReadAllBytes($Path);$sha=[Security.Cryptography.SHA256]::Create()
    try{return $bytes.Length.ToString()+'|'+([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','')}
    finally{$sha.Dispose()}
}

function Get-TestBytesIdentity([byte[]]$Bytes){
    $sha=[Security.Cryptography.SHA256]::Create()
    try{return $Bytes.Length.ToString()+'|'+([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-','')}
    finally{$sha.Dispose()}
}

function Write-TestUtf8([string]$Path,[string]$Text){
    $parent=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null}
    [IO.File]::WriteAllText($Path,$Text.Replace("`r`n","`n").Replace("`r","`n"),[Text.UTF8Encoding]::new($false))
}

$tokens=$null;$errors=$null
$ast=[Management.Automation.Language.Parser]::ParseFile($upgradePath,[ref]$tokens,[ref]$errors)
Confirm ($errors.Count-eq0) 'upgrade-script-parses'
$registerTokens=$null;$registerErrors=$null
$registerAst=[Management.Automation.Language.Parser]::ParseFile($registerPath,[ref]$registerTokens,[ref]$registerErrors)
Confirm ($registerErrors.Count-eq0) 'register-script-parses'
$functions=@{}
foreach($functionAst in $ast.FindAll({param($node)$node-is[Management.Automation.Language.FunctionDefinitionAst]},$true)){$functions[$functionAst.Name]=[string]$functionAst.Extent.Text}
$registerFunctions=@{}
foreach($functionAst in $registerAst.FindAll({param($node)$node-is[Management.Automation.Language.FunctionDefinitionAst]},$true)){$registerFunctions[$functionAst.Name]=[string]$functionAst.Extent.Text}
Confirm $functions.ContainsKey('Assert-ActorBoundUpgradeLegacyMaterial') 'legacy-material-check-present'
Confirm $functions.ContainsKey('Get-ActorRouteMigration') 'actor-route-migration-present'
Confirm $functions.ContainsKey('Invoke-ActorBoundUpgrade115') '1.15-invoke-present'
Confirm $functions.ContainsKey('Resume-ActorBoundUpgrade115') '1.15-resume-present'
Confirm $functions.ContainsKey('Invoke-ActorBoundUpgrade') 'legacy-invoke-present'
Confirm $functions.ContainsKey('Resume-ActorBoundUpgrade') 'legacy-resume-present'
Confirm $functions.ContainsKey('Get-CurrentPinProcessBridge') 'current-pin-process-bridge-present'
Confirm ($functions.ContainsKey('Get-CurrentTaskBinding')-and$functions.ContainsKey('Get-SameVersionCorrectionsMigration')-and$functions.ContainsKey('Invoke-SameVersionCorrectionsMigration')-and$functions.ContainsKey('Get-ProjectCorrectionsReviewReturnTaskProjection')) 'same-version-project-corrections-migration-functions-present'
Confirm ($functions.ContainsKey('Get-TargetFrameworkCapabilityContract')-and$functions.ContainsKey('Assert-TargetFrameworkCapabilities')-and$functions.ContainsKey('Assert-TargetProjectCapabilities')) 'upgrade-target-capability-contract-functions-present'
Confirm ($registerFunctions.ContainsKey('Get-TargetFrameworkCapabilityContract')-and$registerFunctions.ContainsKey('Assert-TargetFrameworkCapabilities')) 'register-target-capability-contract-functions-present'

$migration=[string]$functions['Get-ActorRouteMigration']
$invoke115=[string]$functions['Invoke-ActorBoundUpgrade115']
$authorize115=[string]$functions['Assert-ActorBoundUpgrade115Authorization']
$resume115=[string]$functions['Resume-ActorBoundUpgrade115']
$invoke=[string]$functions['Invoke-ActorBoundUpgrade']
$resume=[string]$functions['Resume-ActorBoundUpgrade']
$processBridge=[string]$functions['Get-CurrentPinProcessBridge']
$currentTaskBinding=[string]$functions['Get-CurrentTaskBinding']
$correctionsMigration=[string]$functions['Get-SameVersionCorrectionsMigration']
$invokeCorrectionsMigration=[string]$functions['Invoke-SameVersionCorrectionsMigration']
$bridge=$processBridge
$upgradeCapabilityContract=[string]$functions['Get-TargetFrameworkCapabilityContract']
$upgradeCapabilityValidator=[string]$functions['Assert-TargetFrameworkCapabilities']
$registerCapabilityContract=[string]$registerFunctions['Get-TargetFrameworkCapabilityContract']
$registerCapabilityValidator=[string]$registerFunctions['Assert-TargetFrameworkCapabilities']
$upgradeText=[IO.File]::ReadAllText($upgradePath)
$registerText=[IO.File]::ReadAllText($registerPath)
$parameterNames=@($ast.ParamBlock.Parameters|ForEach-Object{[string]$_.Name.VariablePath.UserPath})
Confirm ($migration.Contains("Groups['actual']")-and$migration.Contains('ActualPaths=$actualPaths')) 'migration-binds-pre-upgrade-task-actual-pathset'
Confirm $invoke115.Contains('-ObservedActualPath @($Migration.ActualPaths)') '1.15-forward-check-receives-task-actual-pathset'
Confirm $resume115.Contains('-ObservedActualPath @($Migration.ActualPaths)') '1.15-resume-check-receives-task-actual-pathset'
Confirm $invoke.Contains('-ObservedActualPath @($Migration.ActualPaths)') 'legacy-forward-check-receives-task-actual-pathset'
Confirm $resume.Contains('-ObservedActualPath @($Migration.ActualPaths)') 'legacy-resume-check-receives-task-actual-pathset'
Confirm $invoke.Contains(".framework-actor-bound-upgrade-preparation-") 'deterministic-preparation-locator'
Confirm $invoke.Contains(".framework-actor-bound-upgrade-recovery-") 'deterministic-recovery-locator'
Confirm $invoke.Contains('$preparationRelative+''/old/''') 'preview-includes-preparation-old'
Confirm $invoke.Contains('$preparationRelative+''/new/''') 'preview-includes-preparation-new'
Confirm $invoke.Contains('$preparationRelative+''/state.json''') 'preview-includes-preparation-state'

$writeState=$invoke.IndexOf('Write-Utf8NoBom (Join-Path $preparationRoot ''state.json'')',[StringComparison]::Ordinal)
$validatePreparation=$invoke.IndexOf('Assert-ActorBoundUpgradeLegacyMaterial $preparationRoot',[StringComparison]::Ordinal)
$promote=$invoke.IndexOf('[IO.Directory]::Move($preparationRoot,$recoveryRoot)',[StringComparison]::Ordinal)
$validateRecovery=$invoke.IndexOf('Assert-ActorBoundUpgradeLegacyMaterial $recoveryRoot',[StringComparison]::Ordinal)
$firstLiveWrite=$invoke.IndexOf('Set-UpgradeFile ',[StringComparison]::Ordinal)
Confirm ($writeState-ge0) 'state-written-in-preparation'
Confirm ($validatePreparation-gt$writeState) 'preparation-validated-after-state'
Confirm ($promote-gt$validatePreparation) 'promotion-after-preparation-validation'
Confirm ($validateRecovery-gt$promote) 'recovery-validated-after-promotion'
Confirm ($firstLiveWrite-gt$validateRecovery) 'live-write-after-recovery-validation'
if($promote-ge0){
    $beforePromotion=$invoke.Substring(0,$promote)
    Confirm (-not$beforePromotion.Contains('Join-Path $recoveryRoot ''old''')) 'no-recovery-old-write-before-promotion'
    Confirm (-not$beforePromotion.Contains('Join-Path $recoveryRoot ''new''')) 'no-recovery-new-write-before-promotion'
}
Confirm ($resume.Contains('$usesPreparedPathset=')) 'resume-detects-prepared-pathset'
Confirm ($resume.Contains('ACTOR_BOUND_UPGRADE_PREPARATION_REAPPEARED')) 'resume-rejects-preparation-reappearance'
Confirm ($resume.Contains('if($usesPreparedPathset){$reconstructed.Add($preparationRelative+''/state.json'')')) 'resume-reconstructs-preparation-pathset'
Confirm ('CurrentProcessInputPath'-cin$parameterNames-and'ExpectedCurrentProcessInputIdentity'-cin$parameterNames) 'bridge-input-and-identity-parameters-present'
Confirm ('ProjectCorrectionsMigrationPath'-cin$parameterNames-and'ExpectedProjectCorrectionsMigrationIdentity'-cin$parameterNames-and'ReviewProjectCorrectionsMigration'-cin$parameterNames-and'PrepareProjectCorrectionsMigrationReview'-cin$parameterNames-and'PrepareProjectCorrectionsMigrationReviewReturn'-cin$parameterNames-and'ProjectCorrectionsMigrationReviewer'-cin$parameterNames-and'ProjectCorrectionsMigrationReviewDispositionPath'-cin$parameterNames-and'ExpectedProjectCorrectionsMigrationReviewDispositionIdentity'-cin$parameterNames) 'project-corrections-migration-input-identity-and-review-parameters-present'
Confirm ($bridge.Contains('-TargetVersion $FromVersion')-and$bridge.Contains('PROCESS_REQUIREMENTS_RESOLVE')-and$bridge.Contains('-InputPath $CurrentProcessInputPath -AsJson')-and$bridge.Contains('$resolverCode-notin@(0,2)')-and$bridge.Contains('$resolverCode-eq2')-and$bridge.Contains('SELECTED_RULE_PACK_BUDGET_EXCEEDED')) 'bridge-runs-current-sealed-resolver-and-accepts-only-exact-budget-failure'
Confirm ($processBridge.Contains('Import-Module $modulePath -Force -PassThru')-and$processBridge.Contains('Invoke-ProcessRequirementComposition')-and$processBridge.Contains('sourceBuildCount-ne1')-and$processBridge.Contains('fullText')) 'bridge-recomposes-complete-pack-once'
Confirm ($processBridge.Contains('ordinarySelectedPackBytes')-and$processBridge.Contains('absoluteSelectedPackBytes')-and$processBridge.Contains('legacySchema1CorrectionCompatibilityBytes')-and$processBridge.Contains('$packBytes-gt$targetCeiling')-and$processBridge.Contains("'ORDINARY'")-and$processBridge.Contains("'ABSOLUTE'")-and$processBridge.Contains("'LEGACY_SCHEMA1_CORRECTION_COMPATIBILITY'")) 'bridge-enforces-ordinary-absolute-and-eligible-legacy-budgets'
Confirm (-not$bridge.Contains('Write-Utf8')-and-not$bridge.Contains('Set-UpgradeFile')-and-not$bridge.Contains('Copy-Item')-and$bridge.Contains('SelectedPackIdentity')-and$bridge.Contains('SourceCompositionIdentity')) 'bridge-evidence-is-in-memory-and-non-authorizing'
Confirm ($authorize115.Contains('CURRENT_PIN_BRIDGE_USER_DECISION_DRIFT')-and$upgradeText.Contains("if(`$TargetVersion-ceq'1.15.1'-or`$profileTarget){`$script:CurrentPinBudgetBridge=Get-CurrentPinProcessBridge")) 'bridge-remains-bound-to-schema3-user-decision-and-profile-target'
Confirm ($upgradeText.Contains('$TargetVersion-in@(''1.15.0'',''1.15.1'')-and$FromVersion-notin@(''1.14.0'',''1.14.1'')')) 'bridge-source-family-is-exact-1.14.x'
Confirm ($upgradeCapabilityContract.Contains('PROJECT_CONFIG_SCHEMA.json')-and$upgradeCapabilityContract.Contains('additionalProperties')-and$upgradeCapabilityContract.Contains('KNOWLEDGE_REFERENCE')-and$registerCapabilityContract.Contains('PROJECT_CONFIG_SCHEMA.json')-and$registerCapabilityContract.Contains('additionalProperties')-and$registerCapabilityContract.Contains('KNOWLEDGE_REFERENCE')) 'root-tools-derive-closed-target-capability-schema'
Confirm ($upgradeCapabilityValidator.Contains('FRAMEWORK_CAPABILITIES_UNKNOWN_OR_DUPLICATE')-and$registerCapabilityValidator.Contains('FRAMEWORK_CAPABILITIES_UNKNOWN_OR_DUPLICATE')-and$upgradeText.Contains('Assert-TargetProjectCapabilities')-and$registerText.Contains('$script:ActiveTargetCapabilityContract=Get-TargetFrameworkCapabilityContract')) 'root-tools-enforce-target-capability-contract-consistently'
Confirm ($currentTaskBinding.Contains("Task schema:")-and$currentTaskBinding.Contains('CURRENT_TASK_DRIFT')-and$currentTaskBinding.Contains('CURRENT_TASK_BINDING_REQUIRED')) 'same-version-corrections-migration-binds-current-task'
Confirm ($correctionsMigration.Contains('PROJECT_CORRECTIONS_MIGRATION_HISTORICAL_DRIFT')-and$correctionsMigration.Contains('schemaVersion-ne1')-and$correctionsMigration.Contains('schemaVersion-ne2')-and$correctionsMigration.Contains('same-version project-control migration')) 'same-version-corrections-migration-preserves-history-and-binds-intent'
Confirm ($correctionsMigration.Contains('resolve-process-requirements.ps1')-and$correctionsMigration.Contains('SELECTED_RULE_PACK_BUDGET_EXCEEDED')-and$correctionsMigration.Contains('legacyCorrectionsFullReadCount-ne0')-and$correctionsMigration.Contains('ordinarySelectedPackBytes')) 'same-version-corrections-migration-proves-current-and-projected-discover'
Confirm ($invokeCorrectionsMigration.Contains('Assert-ActorBoundUpgrade115Authorization')-and$invokeCorrectionsMigration.Contains('[IO.File]::Move')-and$invokeCorrectionsMigration.Contains('PROJECT_CONTROL_MIGRATION_APPLIED')-and-not$invokeCorrectionsMigration.Contains('framework/versions/')) 'same-version-corrections-migration-is-authorized-atomic-root-tooling'
Confirm ($correctionsMigration.Contains('PROJECT_CORRECTIONS_MIGRATION_REVIEW_NORMAL_ROUTE_AVAILABLE')-and$correctionsMigration.Contains('PROJECT_CORRECTIONS_MIGRATION_REVIEW_BRIDGE_BUDGET')-and$correctionsMigration.Contains('legacySchema1CorrectionCompatibilityBytes')-and$correctionsMigration.Contains('Invoke-ProcessRequirementComposition')-and$correctionsMigration.Contains('pre-apply independent review')) 'same-version-corrections-review-bridge-is-budget-bounded-and-loads-complete-current-rules'
Confirm ($invokeCorrectionsMigration.Contains('PROJECT_CORRECTIONS_MIGRATION_REVIEW_TASK_BINDING_ADMISSION')-and$invokeCorrectionsMigration.Contains('CONTROLLER_TASK_BINDING_PROJECTION_ONLY')-and$invokeCorrectionsMigration.Contains('taskBindingWriteAuthorized')-and$invokeCorrectionsMigration.Contains('REVIEW_INDEPENDENCE_NOT_YET_PROVEN')) 'same-version-corrections-controller-binding-admission-is-projection-only-and-nonauthoritative'
Confirm ($invokeCorrectionsMigration.Contains('PROJECT_CORRECTIONS_MIGRATION_REVIEW_ADMISSION')-and$invokeCorrectionsMigration.Contains('reviewAuthorizationValidated')-and$invokeCorrectionsMigration.Contains('migrationApplyAuthorized')-and$invokeCorrectionsMigration.Contains('selectedRuleBlocks')) 'same-version-corrections-review-admission-is-nonauthoritative-and-apply-closed'
Confirm ($invokeCorrectionsMigration.Contains('PROJECT_CORRECTIONS_MIGRATION_REVIEW_TERMINAL_RETURN_ADMISSION')-and$invokeCorrectionsMigration.Contains('REVIEW_TERMINAL_AND_CURRENT_BINDING_VALIDATED')-and$invokeCorrectionsMigration.Contains('CONTROLLER_TASK_RETURN_PROJECTION_ONLY')-and$invokeCorrectionsMigration.Contains('ownerAcceptAuthorized')) 'same-version-corrections-review-terminal-return-is-projection-only-and-nonauthoritative'
$migrationBranch=$upgradeText.IndexOf('if($projectCorrectionsMigrationRequested){',[StringComparison]::Ordinal)
$alreadyUpgradedBranch=$upgradeText.IndexOf("if((`$ToVersion-in@('1.15.0','1.15.1')-or(Test-AdoptionProfileVersion `$ToVersion))-and[string]`$config.frameworkVersion-ceq`$ToVersion){",[StringComparison]::Ordinal)
Confirm ($migrationBranch-ge0-and$alreadyUpgradedBranch-gt$migrationBranch) 'same-version-corrections-migration-precedes-noop-validation'

$fixtureRoot=Join-Path ([IO.Path]::GetTempPath()) ('aiw-root-corrections-migration-'+[guid]::NewGuid().ToString('N'))
try{
    New-Item -ItemType Directory -Path $fixtureRoot -Force|Out-Null
    & git -C $fixtureRoot init -q
    $registerOutput=@(& $registerPath -ProjectId 'same-pin-fixture' -DisplayName 'Same Pin Fixture' -FrameworkVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'controller-fixture' -Apply -Confirm:$false -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$registerCode=$LASTEXITCODE
    Confirm ($registerCode-eq0-and(Test-Path -LiteralPath (Join-Path $fixtureRoot '.ai-workspace/project.json') -PathType Leaf)-and(Test-Path -LiteralPath (Join-Path $fixtureRoot '.ai-workspace/BOOTSTRAP.md') -PathType Leaf)) 'same-version-corrections-fixture-registers'
    $control=Join-Path $fixtureRoot '.ai-workspace';$correctionsPath=Join-Path $control 'corrections.json'
    $legacy=[ordered]@{schemaVersion=1;contractVersion='1.10.0';projectId='same-pin-fixture';corrections=@([ordered]@{correctionId='FIXTURE_RULE';introducedAgainstFramework='1.15.1';requirementReason='Observed fixture failure';effectiveRule='Fixture work must retain its exact task binding.';applicability='Fixture work only';decisionLocator='fixture:decision'})}
    Write-TestUtf8 $correctionsPath (($legacy|ConvertTo-Json -Depth 20)+"`n")
    $candidate=[ordered]@{schemaVersion=2;contractVersion='1.14.0';projectId='same-pin-fixture';corrections=@([ordered]@{correctionId='FIXTURE_RULE';introducedAgainstFramework='1.15.1';requirementReason='Observed fixture failure';effectiveRule='Fixture work must retain its exact task binding.';applicability='Fixture work only';decisionLocator='fixture:decision';selectors=[ordered]@{profiles=@('*');roles=@('*');phases=@('*');actionKinds=@('*');resultKinds=@('*');pathPrefixes=@();capabilities=@();semanticTerms=@('fixture-domain-only')};preparationRequirements=@();resultRequirements=@();requiredFacts=@();mechanicalCheckRefs=@()})}
    $candidatePath=Join-Path $control 'tmp/candidates/corrections-v2.json';Write-TestUtf8 $candidatePath (($candidate|ConvertTo-Json -Depth 30)+"`n")
    $taskRelative='.ai-workspace/tasks/active/SAME-PIN-MIGRATION-001.md';$taskPath=Join-Path $fixtureRoot $taskRelative
    $taskText=@('# SAME-PIN-MIGRATION-001 — same pin corrections fixture','', '- Status: `ACTIVE`','- Task schema: 1.16.0','- Profile: `CRITICAL`','- Owner: controller-fixture','- Work route: actor=controller-fixture; role=CONTROLLER; phase=PLAN','- Range summary: profile=CRITICAL; lifecycle=ACTIVE; current_exact=NONE; expected_paths=[]; actual_paths=[]','')-join"`n"
    Write-TestUtf8 $taskPath $taskText
    $controllerTaskIdentity=Get-TestIdentity $taskPath
    $projectPath=Join-Path $control 'project.json'
    $input=[ordered]@{schemaVersion=2;mode='DISCOVER';projectRoot=$fixtureRoot;frameworkRoot=$RepositoryRoot;taskPath=$taskPath;expectedProjectConfigIdentity=(Get-TestIdentity $projectPath);expectedCorrectionsIdentity=(Get-TestIdentity $correctionsPath);expectedTaskIdentity=(Get-TestIdentity $taskPath);observedActor='controller-fixture';capabilities=@();exactPaths=@('.ai-workspace/corrections.json');forbiddenPaths=@('src/','tests/','assets/','docs/');protectedPaths=@('.ai-workspace/');authorizationPackagePath='NOT_REQUIRED';expectedAuthorizationIdentity='NOT_REQUIRED';userDecision='USER_FIXTURE_APPROVED_SAME_VERSION_PROJECT_CONTROL_MIGRATION';recoveryState='FULL_COLD';hostEnforcementGrade='INSTRUCTION_BOUND';invocationState='PROVEN_EXPLICIT';intentEnvelope=[ordered]@{schemaVersion=1;objective='Preview the fixture project corrections migration without mutation';requestedActionKind='NONE';requestedResultKind='PLAN';semanticHints=@('Project corrections migration','same-version project-control migration');pathHints=@('.ai-workspace/corrections.json');capabilityHints=@();mutationHints=@();externalHints=@();ambiguityState='CLEAR'};evaluationOnly=$true}
    $inputPath=Join-Path $control 'tmp/corrections-migration-discover.json';Write-TestUtf8 $inputPath (($input|ConvertTo-Json -Depth 30 -Compress)+"`n")
    $preview=@(& $upgradePath -ProjectId 'same-pin-fixture' -ToVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'controller-fixture' -ActorRouteTaskPath $taskRelative -ExpectedActorRouteTaskIdentity (Get-TestIdentity $taskPath) -ActorRouteActor 'controller-fixture' -CurrentProcessInputPath $inputPath -ExpectedCurrentProcessInputIdentity (Get-TestIdentity $inputPath) -ProjectCorrectionsMigrationPath $candidatePath -ExpectedProjectCorrectionsMigrationIdentity (Get-TestIdentity $candidatePath) -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$previewCode=$LASTEXITCODE
    $previewText=$preview-join"`n"
    Confirm ($previewCode-eq0-and$previewText.Contains('PROJECT_CONTROL_MIGRATION_DISCOVER|current=PASS|projected=PASS')-and$previewText.Contains('WHAT_IF|from=1.16.0|to=1.16.0|objects=1|transaction=atomic-project-control-migration')-and[int](($legacy.corrections).Count)-eq1-and(Get-TestIdentity $correctionsPath)-cne(Get-TestIdentity $candidatePath)) 'same-version-corrections-migration-preview-proves-target-without-write'

    $legacyRecords=New-Object 'System.Collections.Generic.List[object]';$candidateRecords=New-Object 'System.Collections.Generic.List[object]'
    foreach($index in 1..20){
        $rule=('Fixture review rule '+$index+' '+('x'*2600));$historical=[ordered]@{correctionId=('FIXTURE_REVIEW_'+$index);introducedAgainstFramework='1.15.1';requirementReason=('Observed review bootstrap failure '+$index);effectiveRule=$rule;applicability='Fixture review only';decisionLocator=('fixture:review:'+ $index)}
        $legacyRecords.Add([pscustomobject]$historical)
        $candidateRecord=[ordered]@{};foreach($name in @('correctionId','introducedAgainstFramework','requirementReason','effectiveRule','applicability','decisionLocator')){$candidateRecord[$name]=$historical[$name]};$candidateRecord.selectors=[ordered]@{profiles=@('CRITICAL');roles=@('REVIEWER');phases=@('REVIEW');actionKinds=@('REVIEW_EXECUTE');resultKinds=@('REVIEW_VERDICT');pathPrefixes=@('.ai-workspace/tmp/candidates/');capabilities=@();semanticTerms=@(('fixture-review-'+$index))};$candidateRecord.preparationRequirements=@();$candidateRecord.resultRequirements=@();$candidateRecord.requiredFacts=@();$candidateRecord.mechanicalCheckRefs=@();$candidateRecords.Add([pscustomobject]$candidateRecord)
    }
    $legacy.corrections=@($legacyRecords|ForEach-Object{$_});$candidate.corrections=@($candidateRecords|ForEach-Object{$_});Write-TestUtf8 $correctionsPath (($legacy|ConvertTo-Json -Depth 30)+"`n");Write-TestUtf8 $candidatePath (($candidate|ConvertTo-Json -Depth 40)+"`n")
    $bootstrapPath=Join-Path $control 'BOOTSTRAP.md';$bootstrapText=[IO.File]::ReadAllText($bootstrapPath).Replace('No permanent project process rule is active in this legacy region. Structured rules belong to `.ai-workspace/process-policy.json`.','Fixture permanent project rule: independent migration Review must bind the exact candidate before Apply.');Write-TestUtf8 $bootstrapPath $bootstrapText

    $bindingInput=[ordered]@{schemaVersion=2;mode='DISCOVER';projectRoot=$fixtureRoot;frameworkRoot=$RepositoryRoot;taskPath=$taskPath;expectedProjectConfigIdentity=(Get-TestIdentity $projectPath);expectedCorrectionsIdentity=(Get-TestIdentity $correctionsPath);expectedTaskIdentity=(Get-TestIdentity $taskPath);observedActor='controller-fixture';capabilities=@();exactPaths=@($taskRelative);forbiddenPaths=@('src/','tests/','assets/','docs/');protectedPaths=@('.ai-workspace/');authorizationPackagePath='NOT_REQUIRED';expectedAuthorizationIdentity='NOT_REQUIRED';userDecision='USER_FIXTURE_APPROVED_CORRECTIONS_REVIEW_BINDING';recoveryState='FULL_COLD';hostEnforcementGrade='INSTRUCTION_BOUND';invocationState='PROVEN_EXPLICIT';intentEnvelope=[ordered]@{schemaVersion=1;objective='Project the Controller task binding required for independent corrections migration Review';requestedActionKind='NONE';requestedResultKind='PLAN';semanticHints=@('Project corrections migration','review task binding admission');pathHints=@($taskRelative);capabilityHints=@();mutationHints=@();externalHints=@();ambiguityState='CLEAR'};evaluationOnly=$true}
    $bindingInputPath=Join-Path $control 'tmp/corrections-review-binding-discover.json';Write-TestUtf8 $bindingInputPath (($bindingInput|ConvertTo-Json -Depth 40 -Compress)+"`n")
    $bindingOutput=@(& $upgradePath -ProjectId 'same-pin-fixture' -ToVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'controller-fixture' -ActorRouteTaskPath $taskRelative -ExpectedActorRouteTaskIdentity (Get-TestIdentity $taskPath) -ActorRouteActor 'controller-fixture' -CurrentProcessInputPath $bindingInputPath -ExpectedCurrentProcessInputIdentity (Get-TestIdentity $bindingInputPath) -ProjectCorrectionsMigrationPath $candidatePath -ExpectedProjectCorrectionsMigrationIdentity (Get-TestIdentity $candidatePath) -PrepareProjectCorrectionsMigrationReview -ProjectCorrectionsMigrationReviewer 'reviewer-fixture' -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$bindingCode=$LASTEXITCODE
    $bindingReceipt=if($bindingCode-eq0-and$bindingOutput.Count-eq1){$bindingOutput[0]|ConvertFrom-Json -Depth 100}else{$null}
    $bindingPostimageText=if($null-ne$bindingReceipt){[string]$bindingReceipt.taskBinding.postimageText}else{''}
    $bindingPostimageIdentity=if([string]::IsNullOrEmpty($bindingPostimageText)){'MISSING'}else{Get-TestBytesIdentity ([Text.UTF8Encoding]::new($false).GetBytes($bindingPostimageText))}
    Confirm ($bindingCode-eq0-and$null-ne$bindingReceipt-and[string]$bindingReceipt.receiptType-ceq'PROJECT_CORRECTIONS_MIGRATION_REVIEW_TASK_BINDING_ADMISSION'-and-not[bool]$bindingReceipt.taskBindingWriteAuthorized-and-not[bool]$bindingReceipt.reviewAuthorizationValidated-and-not[bool]$bindingReceipt.migrationApplyAuthorized-and[string]$bindingReceipt.taskBinding.preimage-ceq(Get-TestIdentity $taskPath)-and[string]$bindingReceipt.taskBinding.postimage-ceq$bindingPostimageIdentity-and$bindingPostimageText.Contains('lifecycle=REVIEW;')-and$bindingPostimageText.Contains('actor=reviewer-fixture; role=REVIEWER; phase=REVIEW')-and[int]$bindingReceipt.currentSource.selectedPackBytes-gt65536-and[int]$bindingReceipt.currentSource.selectedPackBytes-le98304-and[int]$bindingReceipt.projectedDiscover.selectedPackBytes-le32768-and[string]$bindingReceipt.candidateIdentity-ceq(Get-TestIdentity $candidatePath)) 'same-version-corrections-controller-binding-admission-projects-review-route-with-zero-write-or-apply'

    Write-TestUtf8 $taskPath $bindingPostimageText
    $reviewTaskRelative=$taskRelative;$reviewTaskPath=$taskPath;$candidateRelative='.ai-workspace/tmp/candidates/corrections-v2.json'
    $reviewAuthorization=[ordered]@{schemaVersion=1;frameworkVersion='1.16.0';taskId='SAME-PIN-MIGRATION-001';taskIdentity=(Get-TestIdentity $reviewTaskPath);profile='CRITICAL';lifecycle='ACTIVE';owner='controller-fixture';issuer='controller-fixture';issuerRole='PROJECT_CONTROLLER';grantee='reviewer-fixture';bundle='REVIEW_LOCAL';decisionClass='MAJOR_ARCHITECTURE';userConfirmation='USER_FIXTURE_APPROVED_CORRECTIONS_REVIEW';reviewIndependence='INDEPENDENT';delegatedGitCloser=$false;actions=@('REVIEW_EXECUTE');exactPaths=@($candidateRelative);objectIdentities=@([ordered]@{path=$candidateRelative;identity=(Get-TestIdentity $candidatePath)});projectConfigIdentity=(Get-TestIdentity $projectPath);invalidatesOn=@('TASK_CHANGE','OWNER_CHANGE','GRANTEE_CHANGE','ACTION_CHANGE','PATHSET_CHANGE','OBJECT_DRIFT','USER_DECISION_CHANGE','CONTRIBUTOR_SET_CHANGE','PROJECT_CONFIG_DRIFT','CONTROLLER_EPOCH_CHANGE');candidateWriter='writer-fixture';materialContributors=@('designer-fixture');issuerControllerId='controller-fixture';issuerControllerEpoch=1;controllerControlIdentity=(Get-TestIdentity (Join-Path $control 'controller.json'))}
    $reviewAuthorizationPath=Join-Path $control 'tmp/review-authorization.json';Write-TestUtf8 $reviewAuthorizationPath (($reviewAuthorization|ConvertTo-Json -Depth 30)+"`n")
    $reviewInput=[ordered]@{schemaVersion=2;mode='DISCOVER';projectRoot=$fixtureRoot;frameworkRoot=$RepositoryRoot;taskPath=$reviewTaskPath;expectedProjectConfigIdentity=(Get-TestIdentity $projectPath);expectedCorrectionsIdentity=(Get-TestIdentity $correctionsPath);expectedTaskIdentity=(Get-TestIdentity $reviewTaskPath);observedActor='reviewer-fixture';capabilities=@();exactPaths=@($candidateRelative);forbiddenPaths=@('src/','tests/','assets/','docs/');protectedPaths=@('.ai-workspace/');authorizationPackagePath=$reviewAuthorizationPath;expectedAuthorizationIdentity=(Get-TestIdentity $reviewAuthorizationPath);userDecision='USER_FIXTURE_APPROVED_CORRECTIONS_REVIEW';recoveryState='FULL_COLD';hostEnforcementGrade='INSTRUCTION_BOUND';invocationState='PROVEN_EXPLICIT';intentEnvelope=[ordered]@{schemaVersion=1;objective='Independently review the project corrections migration candidate';requestedActionKind='REVIEW_EXECUTE';requestedResultKind='REVIEW_VERDICT';semanticHints=@('Project corrections migration','pre-apply independent review','fixture-review-1');pathHints=@($candidateRelative);capabilityHints=@();mutationHints=@();externalHints=@();ambiguityState='CLEAR'};evaluationOnly=$false}
    $reviewInputPath=Join-Path $control 'tmp/corrections-review-discover.json';Write-TestUtf8 $reviewInputPath (($reviewInput|ConvertTo-Json -Depth 40 -Compress)+"`n")
    $reviewOutput=@(& $upgradePath -ProjectId 'same-pin-fixture' -ToVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'controller-fixture' -ActorRouteTaskPath $reviewTaskRelative -ExpectedActorRouteTaskIdentity (Get-TestIdentity $reviewTaskPath) -ActorRouteActor 'reviewer-fixture' -CurrentProcessInputPath $reviewInputPath -ExpectedCurrentProcessInputIdentity (Get-TestIdentity $reviewInputPath) -ProjectCorrectionsMigrationPath $candidatePath -ExpectedProjectCorrectionsMigrationIdentity (Get-TestIdentity $candidatePath) -ReviewProjectCorrectionsMigration -AuthorizationPackagePath $reviewAuthorizationPath -ExpectedAuthorizationPackageIdentity (Get-TestIdentity $reviewAuthorizationPath) -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$reviewCode=$LASTEXITCODE
    $reviewTerminal=[ordered]@{schemaVersion=1;receiptType='PROJECT_CORRECTIONS_MIGRATION_REVIEW_TERMINAL';status='COMPLETE';projectId='same-pin-fixture';frameworkVersion='1.16.0';taskId='SAME-PIN-MIGRATION-001';taskIdentity=(Get-TestIdentity $reviewTaskPath);taskOwner='controller-fixture';reviewer='reviewer-fixture';controllerId='controller-fixture';controllerEpoch=1;controllerControlIdentity=(Get-TestIdentity (Join-Path $control 'controller.json'));candidatePath=$candidateRelative;candidateIdentity=(Get-TestIdentity $candidatePath);verdict='CHANGES_REQUIRED'}
    $reviewTerminalPath=Join-Path $control 'tmp/review-terminal.json';Write-TestUtf8 $reviewTerminalPath (($reviewTerminal|ConvertTo-Json -Depth 20)+"`n")
    $returnInput=[ordered]@{schemaVersion=2;mode='DISCOVER';projectRoot=$fixtureRoot;frameworkRoot=$RepositoryRoot;taskPath=$reviewTaskPath;expectedProjectConfigIdentity=(Get-TestIdentity $projectPath);expectedCorrectionsIdentity=(Get-TestIdentity $correctionsPath);expectedTaskIdentity=(Get-TestIdentity $reviewTaskPath);observedActor='reviewer-fixture';capabilities=@();exactPaths=@($candidateRelative);forbiddenPaths=@('src/','tests/','assets/','docs/');protectedPaths=@('.ai-workspace/');authorizationPackagePath='NOT_REQUIRED';expectedAuthorizationIdentity='NOT_REQUIRED';userDecision='USER_FIXTURE_APPROVED_REVIEW_TERMINAL_RETURN';recoveryState='FULL_COLD';hostEnforcementGrade='INSTRUCTION_BOUND';invocationState='PROVEN_EXPLICIT';intentEnvelope=[ordered]@{schemaVersion=1;objective='Validate the completed independent Review terminal and project the current task back to its Controller';requestedActionKind='REVIEW_EXECUTE';requestedResultKind='REVIEW_VERDICT';semanticHints=@('Project corrections migration','review terminal return admission');pathHints=@($candidateRelative);capabilityHints=@();mutationHints=@();externalHints=@();ambiguityState='CLEAR'};evaluationOnly=$true}
    $returnInputPath=Join-Path $control 'tmp/corrections-review-return-discover.json';Write-TestUtf8 $returnInputPath (($returnInput|ConvertTo-Json -Depth 40 -Compress)+"`n")
    $returnOutput=@(& $upgradePath -ProjectId 'same-pin-fixture' -ToVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'controller-fixture' -ActorRouteTaskPath $reviewTaskRelative -ExpectedActorRouteTaskIdentity (Get-TestIdentity $reviewTaskPath) -ActorRouteActor 'reviewer-fixture' -CurrentProcessInputPath $returnInputPath -ExpectedCurrentProcessInputIdentity (Get-TestIdentity $returnInputPath) -ProjectCorrectionsMigrationPath $candidatePath -ExpectedProjectCorrectionsMigrationIdentity (Get-TestIdentity $candidatePath) -PrepareProjectCorrectionsMigrationReviewReturn -ProjectCorrectionsMigrationReviewer 'reviewer-fixture' -ProjectCorrectionsMigrationReviewDispositionPath $reviewTerminalPath -ExpectedProjectCorrectionsMigrationReviewDispositionIdentity (Get-TestIdentity $reviewTerminalPath) -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$returnCode=$LASTEXITCODE
    $returnReceipt=if($returnCode-eq0-and$returnOutput.Count-eq1){$returnOutput[0]|ConvertFrom-Json -Depth 100}else{$null}
    $returnPostimageText=if($null-ne$returnReceipt){[string]$returnReceipt.taskBinding.postimageText}else{''}
    Confirm ($returnCode-eq0-and$null-ne$returnReceipt-and[string]$returnReceipt.receiptType-ceq'PROJECT_CORRECTIONS_MIGRATION_REVIEW_TERMINAL_RETURN_ADMISSION'-and[string]$returnReceipt.reviewDisposition.path-ceq'.ai-workspace/tmp/review-terminal.json'-and[string]$returnReceipt.reviewDisposition.verdict-ceq'CHANGES_REQUIRED'-and[string]$returnReceipt.controller.id-ceq'controller-fixture'-and[int]$returnReceipt.controller.epoch-eq1-and[string]$returnReceipt.controller.state-ceq'CURRENT'-and[string]$returnReceipt.reviewer-ceq'reviewer-fixture'-and[string]$returnReceipt.taskBinding.preimage-ceq(Get-TestIdentity $reviewTaskPath)-and[string]$returnReceipt.taskBinding.postimage-ceq$controllerTaskIdentity-and$returnPostimageText.Contains('lifecycle=ACTIVE;')-and$returnPostimageText.Contains('actor=controller-fixture; role=CONTROLLER; phase=PLAN')-and-not[bool]$returnReceipt.taskBindingWriteAuthorized-and-not[bool]$returnReceipt.migrationApplyAuthorized-and-not[bool]$returnReceipt.ownerAcceptAuthorized-and(Get-TestIdentity $reviewTaskPath)-cne$controllerTaskIdentity) 'same-version-corrections-review-terminal-return-completes-controller-reviewer-controller-round-trip-with-zero-write'

    $missingTerminalOutput=@(& pwsh -NoProfile -NonInteractive -File $upgradePath -ProjectId 'same-pin-fixture' -ToVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'controller-fixture' -ActorRouteTaskPath $reviewTaskRelative -ExpectedActorRouteTaskIdentity (Get-TestIdentity $reviewTaskPath) -ActorRouteActor 'reviewer-fixture' -CurrentProcessInputPath $returnInputPath -ExpectedCurrentProcessInputIdentity (Get-TestIdentity $returnInputPath) -ProjectCorrectionsMigrationPath $candidatePath -ExpectedProjectCorrectionsMigrationIdentity (Get-TestIdentity $candidatePath) -PrepareProjectCorrectionsMigrationReviewReturn -ProjectCorrectionsMigrationReviewer 'reviewer-fixture' -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$missingTerminalCode=$LASTEXITCODE
    Confirm ($missingTerminalCode-ne0-and($missingTerminalOutput-join"`n").Contains('PROJECT_CORRECTIONS_MIGRATION_REVIEW_TERMINAL_REQUIRED')) 'same-version-corrections-review-return-rejects-missing-terminal'

    $pendingTerminal=[ordered]@{};foreach($name in $reviewTerminal.Keys){$pendingTerminal[$name]=$reviewTerminal[$name]};$pendingTerminal.status='PENDING';$pendingTerminalPath=Join-Path $control 'tmp/review-terminal-pending.json';Write-TestUtf8 $pendingTerminalPath (($pendingTerminal|ConvertTo-Json -Depth 20)+"`n")
    $pendingOutput=@(& pwsh -NoProfile -NonInteractive -File $upgradePath -ProjectId 'same-pin-fixture' -ToVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'controller-fixture' -ActorRouteTaskPath $reviewTaskRelative -ExpectedActorRouteTaskIdentity (Get-TestIdentity $reviewTaskPath) -ActorRouteActor 'reviewer-fixture' -CurrentProcessInputPath $returnInputPath -ExpectedCurrentProcessInputIdentity (Get-TestIdentity $returnInputPath) -ProjectCorrectionsMigrationPath $candidatePath -ExpectedProjectCorrectionsMigrationIdentity (Get-TestIdentity $candidatePath) -PrepareProjectCorrectionsMigrationReviewReturn -ProjectCorrectionsMigrationReviewer 'reviewer-fixture' -ProjectCorrectionsMigrationReviewDispositionPath $pendingTerminalPath -ExpectedProjectCorrectionsMigrationReviewDispositionIdentity (Get-TestIdentity $pendingTerminalPath) -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$pendingCode=$LASTEXITCODE
    Confirm ($pendingCode-ne0-and($pendingOutput-join"`n").Contains('PROJECT_CORRECTIONS_MIGRATION_REVIEW_TERMINAL_BINDING')) 'same-version-corrections-review-return-rejects-incomplete-terminal'

    $staleEpochTerminal=[ordered]@{};foreach($name in $reviewTerminal.Keys){$staleEpochTerminal[$name]=$reviewTerminal[$name]};$staleEpochTerminal.controllerEpoch=2;$staleEpochTerminalPath=Join-Path $control 'tmp/review-terminal-stale-epoch.json';Write-TestUtf8 $staleEpochTerminalPath (($staleEpochTerminal|ConvertTo-Json -Depth 20)+"`n")
    $staleEpochOutput=@(& pwsh -NoProfile -NonInteractive -File $upgradePath -ProjectId 'same-pin-fixture' -ToVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'controller-fixture' -ActorRouteTaskPath $reviewTaskRelative -ExpectedActorRouteTaskIdentity (Get-TestIdentity $reviewTaskPath) -ActorRouteActor 'reviewer-fixture' -CurrentProcessInputPath $returnInputPath -ExpectedCurrentProcessInputIdentity (Get-TestIdentity $returnInputPath) -ProjectCorrectionsMigrationPath $candidatePath -ExpectedProjectCorrectionsMigrationIdentity (Get-TestIdentity $candidatePath) -PrepareProjectCorrectionsMigrationReviewReturn -ProjectCorrectionsMigrationReviewer 'reviewer-fixture' -ProjectCorrectionsMigrationReviewDispositionPath $staleEpochTerminalPath -ExpectedProjectCorrectionsMigrationReviewDispositionIdentity (Get-TestIdentity $staleEpochTerminalPath) -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$staleEpochCode=$LASTEXITCODE
    Confirm ($staleEpochCode-ne0-and($staleEpochOutput-join"`n").Contains('PROJECT_CORRECTIONS_MIGRATION_REVIEW_TERMINAL_BINDING')) 'same-version-corrections-review-return-rejects-stale-controller-epoch'

    $staleControlTerminal=[ordered]@{};foreach($name in $reviewTerminal.Keys){$staleControlTerminal[$name]=$reviewTerminal[$name]};$staleControlTerminal.controllerControlIdentity='0|'+('0'*64);$staleControlTerminalPath=Join-Path $control 'tmp/review-terminal-stale-control.json';Write-TestUtf8 $staleControlTerminalPath (($staleControlTerminal|ConvertTo-Json -Depth 20)+"`n")
    $staleControlOutput=@(& pwsh -NoProfile -NonInteractive -File $upgradePath -ProjectId 'same-pin-fixture' -ToVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'controller-fixture' -ActorRouteTaskPath $reviewTaskRelative -ExpectedActorRouteTaskIdentity (Get-TestIdentity $reviewTaskPath) -ActorRouteActor 'reviewer-fixture' -CurrentProcessInputPath $returnInputPath -ExpectedCurrentProcessInputIdentity (Get-TestIdentity $returnInputPath) -ProjectCorrectionsMigrationPath $candidatePath -ExpectedProjectCorrectionsMigrationIdentity (Get-TestIdentity $candidatePath) -PrepareProjectCorrectionsMigrationReviewReturn -ProjectCorrectionsMigrationReviewer 'reviewer-fixture' -ProjectCorrectionsMigrationReviewDispositionPath $staleControlTerminalPath -ExpectedProjectCorrectionsMigrationReviewDispositionIdentity (Get-TestIdentity $staleControlTerminalPath) -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$staleControlCode=$LASTEXITCODE
    Confirm ($staleControlCode-ne0-and($staleControlOutput-join"`n").Contains('PROJECT_CORRECTIONS_MIGRATION_REVIEW_TERMINAL_BINDING')) 'same-version-corrections-review-return-rejects-stale-controller-control-identity'

    $wrongReviewerOutput=@(& pwsh -NoProfile -NonInteractive -File $upgradePath -ProjectId 'same-pin-fixture' -ToVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'controller-fixture' -ActorRouteTaskPath $reviewTaskRelative -ExpectedActorRouteTaskIdentity (Get-TestIdentity $reviewTaskPath) -ActorRouteActor 'reviewer-fixture' -CurrentProcessInputPath $returnInputPath -ExpectedCurrentProcessInputIdentity (Get-TestIdentity $returnInputPath) -ProjectCorrectionsMigrationPath $candidatePath -ExpectedProjectCorrectionsMigrationIdentity (Get-TestIdentity $candidatePath) -PrepareProjectCorrectionsMigrationReviewReturn -ProjectCorrectionsMigrationReviewer 'wrong-reviewer' -ProjectCorrectionsMigrationReviewDispositionPath $reviewTerminalPath -ExpectedProjectCorrectionsMigrationReviewDispositionIdentity (Get-TestIdentity $reviewTerminalPath) -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$wrongReviewerCode=$LASTEXITCODE
    Confirm ($wrongReviewerCode-ne0-and($wrongReviewerOutput-join"`n").Contains('PROJECT_CORRECTIONS_MIGRATION_REVIEW_RETURN_BINDING_INVALID')) 'same-version-corrections-review-return-rejects-wrong-reviewer'

    $wrongControllerOutput=@(& pwsh -NoProfile -NonInteractive -File $upgradePath -ProjectId 'same-pin-fixture' -ToVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'wrong-controller' -ActorRouteTaskPath $reviewTaskRelative -ExpectedActorRouteTaskIdentity (Get-TestIdentity $reviewTaskPath) -ActorRouteActor 'reviewer-fixture' -CurrentProcessInputPath $returnInputPath -ExpectedCurrentProcessInputIdentity (Get-TestIdentity $returnInputPath) -ProjectCorrectionsMigrationPath $candidatePath -ExpectedProjectCorrectionsMigrationIdentity (Get-TestIdentity $candidatePath) -PrepareProjectCorrectionsMigrationReviewReturn -ProjectCorrectionsMigrationReviewer 'reviewer-fixture' -ProjectCorrectionsMigrationReviewDispositionPath $reviewTerminalPath -ExpectedProjectCorrectionsMigrationReviewDispositionIdentity (Get-TestIdentity $reviewTerminalPath) -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$wrongControllerCode=$LASTEXITCODE
    Confirm ($wrongControllerCode-ne0-and($wrongControllerOutput-join"`n").Contains('controller.json values are invalid.')) 'same-version-corrections-review-return-rejects-wrong-controller'

    $wrongOwnerTaskRelative='.ai-workspace/tasks/active/SAME-PIN-WRONG-OWNER-001.md';$wrongOwnerTaskPath=Join-Path $fixtureRoot $wrongOwnerTaskRelative;$wrongOwnerTaskText=$bindingPostimageText.Replace('# SAME-PIN-MIGRATION-001','# SAME-PIN-WRONG-OWNER-001').Replace('- Owner: controller-fixture','- Owner: other-owner');Write-TestUtf8 $wrongOwnerTaskPath $wrongOwnerTaskText
    $wrongOwnerOutput=@(& pwsh -NoProfile -NonInteractive -File $upgradePath -ProjectId 'same-pin-fixture' -ToVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'controller-fixture' -ActorRouteTaskPath $wrongOwnerTaskRelative -ExpectedActorRouteTaskIdentity (Get-TestIdentity $wrongOwnerTaskPath) -ActorRouteActor 'reviewer-fixture' -CurrentProcessInputPath $returnInputPath -ExpectedCurrentProcessInputIdentity (Get-TestIdentity $returnInputPath) -ProjectCorrectionsMigrationPath $candidatePath -ExpectedProjectCorrectionsMigrationIdentity (Get-TestIdentity $candidatePath) -PrepareProjectCorrectionsMigrationReviewReturn -ProjectCorrectionsMigrationReviewer 'reviewer-fixture' -ProjectCorrectionsMigrationReviewDispositionPath $reviewTerminalPath -ExpectedProjectCorrectionsMigrationReviewDispositionIdentity (Get-TestIdentity $reviewTerminalPath) -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$wrongOwnerCode=$LASTEXITCODE
    Confirm ($wrongOwnerCode-ne0-and($wrongOwnerOutput-join"`n").Contains('PROJECT_CORRECTIONS_MIGRATION_REVIEW_RETURN_BINDING_INVALID')) 'same-version-corrections-review-return-rejects-wrong-owner'

    $staleTaskIdentity='0|'+('0'*64)
    $taskDriftOutput=@(& pwsh -NoProfile -NonInteractive -File $upgradePath -ProjectId 'same-pin-fixture' -ToVersion '1.16.0' -RepositoryPath $fixtureRoot -ControllerId 'controller-fixture' -ActorRouteTaskPath $reviewTaskRelative -ExpectedActorRouteTaskIdentity $staleTaskIdentity -ActorRouteActor 'reviewer-fixture' -CurrentProcessInputPath $returnInputPath -ExpectedCurrentProcessInputIdentity (Get-TestIdentity $returnInputPath) -ProjectCorrectionsMigrationPath $candidatePath -ExpectedProjectCorrectionsMigrationIdentity (Get-TestIdentity $candidatePath) -PrepareProjectCorrectionsMigrationReviewReturn -ProjectCorrectionsMigrationReviewer 'reviewer-fixture' -ProjectCorrectionsMigrationReviewDispositionPath $reviewTerminalPath -ExpectedProjectCorrectionsMigrationReviewDispositionIdentity (Get-TestIdentity $reviewTerminalPath) -WorkspaceRoot $RepositoryRoot 2>&1|ForEach-Object{[string]$_});$taskDriftCode=$LASTEXITCODE
    Confirm ($taskDriftCode-ne0-and($taskDriftOutput-join"`n").Contains('CURRENT_TASK_DRIFT')) 'same-version-corrections-review-return-rejects-task-drift'
    $reviewReceipt=if($reviewCode-eq0-and$reviewOutput.Count-eq1){$reviewOutput[0]|ConvertFrom-Json -Depth 100}else{$null}
    Confirm ($reviewCode-eq0-and$null-ne$reviewReceipt-and[string]$reviewReceipt.receiptType-ceq'PROJECT_CORRECTIONS_MIGRATION_REVIEW_ADMISSION'-and[bool]$reviewReceipt.reviewAuthorizationValidated-and-not[bool]$reviewReceipt.migrationApplyAuthorized-and[int]$reviewReceipt.currentSource.selectedPackBytes-gt65536-and[int]$reviewReceipt.currentSource.selectedPackBytes-le98304-and@($reviewReceipt.currentSource.selectedRuleBlocks).Count-gt0-and[int]$reviewReceipt.projectedDiscover.selectedPackBytes-le32768-and(Get-TestIdentity $correctionsPath)-cne(Get-TestIdentity $candidatePath)) 'same-version-corrections-review-bridge-admits-independent-review-with-complete-current-rules-and-zero-apply'
}finally{
    if(Test-Path -LiteralPath $fixtureRoot){Remove-Item -LiteralPath $fixtureRoot -Recurse -Force}
}

$matrix=[IO.File]::ReadAllText($matrixPath)
Confirm ($matrix.Contains('healthy repo-local schema4 1.14.0 or 1.14.1 | 1.15.1')-and$matrix.Contains('schema3 or schema4 version earlier than 1.14.0 | 1.15.1 | blocked from the direct route')) 'matrix-binds-exact-1.14.x-to-1.15.1-and-keeps-earlier-sources-blocked'

if($failures.Count-gt0){Write-Output ('FAIL|'+[string]::Join(',',$failures));exit 1}
Write-Output ('PASS|upgrade-project-bridge|checks='+$passes)
