[CmdletBinding()]
param([switch]$SkipRootMigration,[switch]$SkipManifest)

$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$utf8=New-Object Text.UTF8Encoding($false)
$utf8Strict=New-Object Text.UTF8Encoding($false,$true)
$script:passed=0

function Assert-True([bool]$Condition,[string]$Name){if(-not$Condition){throw "ASSERT_FAIL|$Name"};$script:passed++;Write-Output "PASS|$Name"}
function Write-Utf8([string]$Path,[string]$Text){$parent=Split-Path -Parent $Path;if($parent-and-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$value=$Text.Replace("`r`n","`n").Replace("`r","`n");if(-not$value.EndsWith("`n")){$value+="`n"};[IO.File]::WriteAllText($Path,$value,$utf8)}
function Get-Identity([string]$Path){$bytes=[IO.File]::ReadAllBytes($Path);$sha=[Security.Cryptography.SHA256]::Create();try{return $bytes.Length.ToString()+'|'+([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','')}finally{$sha.Dispose()}}
function Invoke-Ps([string]$Script,[string[]]$Arguments,[string]$WorkingDirectory=''){
    if($WorkingDirectory){Push-Location $WorkingDirectory}
    try{$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$output=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script @Arguments 2>&1|ForEach-Object{[string]$_});$code=$LASTEXITCODE;$ErrorActionPreference=$old;return [pscustomobject]@{Code=$code;Output=$output;Text=($output-join"`n")}}
    finally{if($WorkingDirectory){Pop-Location}}
}
function ConvertTo-PowerShellLiteral($Value){
    if($null-eq$Value){return '$null'}
    if($Value-is[string]){return "'"+$Value.Replace("'","''")+"'"}
    if($Value-is[char]){return "([char]'"+$Value.ToString().Replace("'","''")+"')"}
    if($Value-is[System.Array]){return '@('+(@($Value|ForEach-Object{ConvertTo-PowerShellLiteral $_})-join',')+')'}
    if($Value-is[int]){return '([int]'+$Value.ToString([Globalization.CultureInfo]::InvariantCulture)+')'}
    throw ('Unsupported knowledge test literal type: '+$Value.GetType().FullName)
}
function Invoke-Knowledge([string]$Script,[string]$Root,[string]$ConfigIdentity,[string]$IndexIdentity,[switch]$BindEntryId,[AllowNull()][object]$EntryIdValue=$null){
    $quote={param([string]$v) "'"+$v.Replace("'","''")+"'"}
    $command="& "+(& $quote $Script)+" -ProjectRoot "+(& $quote $Root)+" -ExpectedProjectConfigIdentity "+(& $quote $ConfigIdentity)+" -ExpectedIndexIdentity "+(& $quote $IndexIdentity)
    if($BindEntryId){$command+=' -EntryId '+(ConvertTo-PowerShellLiteral $EntryIdValue)}
    $command+=' -AsJson'
    $old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$output=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -Command $command 2>&1|ForEach-Object{[string]$_});$code=$LASTEXITCODE}finally{$ErrorActionPreference=$old}
    return [pscustomobject]@{Code=$code;Output=$output;Text=($output-join"`n")}
}
function New-GitRepo([string]$Path){New-Item -ItemType Directory -Path $Path -Force|Out-Null;&git -C $Path init -q;if($LASTEXITCODE-ne0){throw'git init failed'};&git -C $Path config user.email test@example.invalid;&git -C $Path config user.name FrameworkTest}
function New-IsolatedWorkspace([string]$Root,[string]$CandidateRoot,[string]$FrameworkRoot){
    $ws=Join-Path $Root 'workspace';New-Item -ItemType Directory -Path (Join-Path $ws 'framework\versions') -Force|Out-Null
    foreach($v in @('1.4.1','1.5.0','1.5.1','1.5.2','1.6.0')){Copy-Item -LiteralPath (Join-Path $FrameworkRoot "versions\$v") -Destination (Join-Path $ws "framework\versions\$v") -Recurse}
    Copy-Item -LiteralPath $CandidateRoot -Destination (Join-Path $ws 'framework\versions\1.6.1') -Recurse
    Write-Utf8 (Join-Path $ws 'framework\CURRENT') '1.4.1'
    return $ws
}
function New-Migration([string]$Repo,[string]$ProjectId,$Paths){$path=Join-Path $Repo '.tmp\routine-exclusions.json';$obj=[ordered]@{schemaVersion=1;projectId=$ProjectId;routineExcludedPaths=@($Paths)};Write-Utf8 $path ($obj|ConvertTo-Json -Depth 20);return [pscustomobject]@{Path=$path;Identity=Get-Identity $path}}
function Set-RecoveryLiveState([string]$Active,[string]$Project,[string]$Bootstrap,[string]$Controller,[ValidateSet('OLD','MIXED','NEW')][string]$State){
    $transaction=Get-Content -LiteralPath (Join-Path $Active 'state.json') -Raw -Encoding utf8|ConvertFrom-Json
    $projectSource=if($State-ceq'OLD'){Join-Path $Active 'old\project.json'}else{Join-Path $Active 'new\project.json'}
    $bootstrapSource=if($State-ceq'NEW'){Join-Path $Active 'new\BOOTSTRAP.md'}else{Join-Path $Active 'old\BOOTSTRAP.md'}
    [IO.File]::Copy($projectSource,$Project,$true);[IO.File]::Copy($bootstrapSource,$Bootstrap,$true)
    if([string]$transaction.controllerMode-ceq'CREATE'){
        if($State-ceq'OLD'){if(Test-Path -LiteralPath $Controller -PathType Leaf){[IO.File]::Delete($Controller)}}
        else{[IO.File]::Copy((Join-Path $Active 'new\controller.json'),$Controller,$true)}
    }
}
function Register-Project([string]$Script,[string]$Ws,[string]$Repo,[string]$Id,[string]$Version,[string]$Controller=''){$args=@('-ProjectId',$Id,'-DisplayName',$Id,'-RepositoryPath',$Repo,'-WorkspaceRoot',$Ws,'-FrameworkVersion',$Version,'-Apply');if($Controller){$args+=@('-ControllerId',$Controller)};return Invoke-Ps $Script $args}
function New-Entry([string]$Id,[string]$State,[string]$Reference,[string]$Authority){return [ordered]@{id=$Id;state=$State;title="Entry $Id";summary="Summary $Id";locator=$Reference;identity=if(Test-Path -LiteralPath $Reference){Get-Identity $Reference}else{'1|'+('0'*64)};authorityLocator=$Authority;authorityIdentity=if(Test-Path -LiteralPath $Authority){Get-Identity $Authority}else{'1|'+('0'*64)};verifiedAt='2026-08-16T00:00:00Z';invalidatesOn=@('LOCATOR_IDENTITY_CHANGE','AUTHORITY_IDENTITY_CHANGE');tokenEstimate=64}}

$candidateRoot=Split-Path -Parent $PSScriptRoot
$frameworkRoot=Split-Path -Parent (Split-Path -Parent $candidateRoot)
$workspaceRoot=Split-Path -Parent $frameworkRoot
$stableRoot=Join-Path $frameworkRoot 'versions\1.6.0'
$rootDraft=$workspaceRoot
$register=Join-Path $rootDraft 'scripts\register-project.ps1'
$upgrade=Join-Path $rootDraft 'scripts\upgrade-project.ps1'
$auth=Join-Path $candidateRoot 'scripts\check-authorization.ps1'
$safeGit=Join-Path $candidateRoot 'scripts\invoke-protected-safe-git.ps1'
$loader=Join-Path $candidateRoot 'scripts\resolve-load-plan.ps1'
$knowledgeChecker=Join-Path $candidateRoot 'scripts\check-knowledge-entry.ps1'

$expected=@(
'AUTHORIZATION_MODEL.md','CHANGELOG.md','CONTROLLER_SCHEMA.json','EXAMPLES.md','FRAMEWORK_RELEASE.md','GIT_AND_EXTERNAL.md','HOST_CODEX.md','KNOWLEDGE_AND_REFERENCE.md','KNOWLEDGE_SCHEMA.json','LOAD_MANIFEST.json','MIGRATION_MATRIX.md','PERSPECTIVE_LENSES.md','PROJECT_CONFIG_SCHEMA.json','PROJECT_CONTROL.md','project-starter/.gitattributes','project-starter/BOOTSTRAP.md','project-starter/controller.json','project-starter/project.json','project-starter/PROJECT.md','project-starter/RELATIONSHIPS.md','project-starter/REVIEW_PROFILE.md','project-starter/STATUS.md','project-starter/tasks/README.md','PROMPTS.md','README.md','RECOVERY_CORE.md','RELEASE_MANIFEST.json','REVIEW_AND_EVIDENCE.md','scripts/check-authorization.ps1','scripts/check-knowledge-entry.ps1','scripts/check-task-card.ps1','scripts/invoke-protected-safe-git.ps1','scripts/resolve-load-plan.ps1','STATIC_COMPARISON.md','TASK_AND_SCOPE.md','TASK_TEMPLATE.md','tests/run-framework-tests.ps1','VERSION.json')
$actual=@(Get-ChildItem -LiteralPath $candidateRoot -Recurse -File -Force|ForEach-Object{$_.FullName.Substring($candidateRoot.Length+1).Replace('\','/')}|Sort-Object)
Assert-True (@(Compare-Object ($expected|Sort-Object) $actual -CaseSensitive).Count-eq0) 'candidate-inventory-exact38'

foreach($path in @($actual|Where-Object{$_-match'\.(md|json|ps1)$'})){$full=Join-Path $candidateRoot $path;$bytes=[IO.File]::ReadAllBytes($full);$ok=$true;try{$text=$utf8Strict.GetString($bytes)}catch{$ok=$false;$text=''};if($bytes.Length-ge3-and$bytes[0]-eq0xEF-and$bytes[1]-eq0xBB-and$bytes[2]-eq0xBF){$ok=$false};if($text.Contains("`r")-or$text.Contains([char]0)-or$text.Contains([char]0xFFFD)-or-not$text.EndsWith("`n")){$ok=$false};Assert-True $ok ("strict|"+$path);if($path.EndsWith('.json')-and$path-notin@('project-starter/project.json','project-starter/controller.json')){try{$null=$text|ConvertFrom-Json;$jsonOk=$true}catch{$jsonOk=$false};Assert-True $jsonOk ("json|"+$path)}}
$renderProject=(Get-Content -LiteralPath (Join-Path $candidateRoot 'project-starter\project.json') -Raw -Encoding utf8).Replace('{{PROJECT_ID_JSON}}','"sample"').Replace('{{DISPLAY_NAME_JSON}}','"Sample"').Replace('{{FRAMEWORK_VERSION_JSON}}','"1.6.1"')
$renderController=(Get-Content -LiteralPath (Join-Path $candidateRoot 'project-starter\controller.json') -Raw -Encoding utf8).Replace('{{PROJECT_ID_JSON}}','"sample"').Replace('{{CONTROLLER_ID_JSON}}','"controller"')
try{$null=$renderProject|ConvertFrom-Json;$null=$renderController|ConvertFrom-Json;$renderOk=$true}catch{$renderOk=$false};Assert-True $renderOk 'starter-json-templates-render'
foreach($path in @('scripts/check-authorization.ps1','scripts/check-knowledge-entry.ps1','scripts/check-task-card.ps1','scripts/invoke-protected-safe-git.ps1','scripts/resolve-load-plan.ps1','tests/run-framework-tests.ps1')){$tokens=$null;$errors=$null;[Management.Automation.Language.Parser]::ParseFile((Join-Path $candidateRoot $path),[ref]$tokens,[ref]$errors)|Out-Null;Assert-True ($errors.Count-eq0) ("syntax|"+$path)}
foreach($path in @('scripts/register-project.ps1','scripts/upgrade-project.ps1')){$tokens=$null;$errors=$null;[Management.Automation.Language.Parser]::ParseFile((Join-Path $rootDraft $path),[ref]$tokens,[ref]$errors)|Out-Null;Assert-True ($errors.Count-eq0) ("root-syntax|"+$path)}

$stableManifest=Get-Content -LiteralPath (Join-Path $stableRoot 'RELEASE_MANIFEST.json') -Raw|ConvertFrom-Json;[string[]]$stablePayload=@(Get-ChildItem -LiteralPath $stableRoot -Recurse -File -Force|ForEach-Object{$_.FullName.Substring($stableRoot.Length+1).Replace('\','/')}|Where-Object{$_-cne'RELEASE_MANIFEST.json'});[Array]::Sort($stablePayload,[StringComparer]::Ordinal);$stableRows=@();$stableBytes=[int64]0;foreach($path in $stablePayload){$full=Join-Path $stableRoot $path;$bytes=[IO.File]::ReadAllBytes($full);$stableBytes+=$bytes.Length;$stableRows+=("$path|$($bytes.Length)|"+(Get-Identity $full).Split('|')[1])};$sha=[Security.Cryptography.SHA256]::Create();try{$stableCanonical=([BitConverter]::ToString($sha.ComputeHash($utf8.GetBytes(($stableRows-join"`n"))))).Replace('-','')}finally{$sha.Dispose()};Assert-True ($stablePayload.Count-eq37-and$stableBytes-eq220698-and$stableCanonical-ceq'EBB00A3EED4BD9E2871DDBD6CE2B12A252614BD36CD42E092187FF35C4E5E30D'-and[string]$stableManifest.canonical-ceq$stableCanonical) 'stable-1.6.0-zero-drift'
Assert-True ((Get-Identity (Join-Path $workspaceRoot 'INITIALIZATION.md'))-ceq'8833|0016195C0A88606BBF8F891BFC78A5248C1C9D3709E05A95D25C9F5330BADE81') 'live-initialization-zero-drift'
Assert-True ((Get-Identity (Join-Path $workspaceRoot 'scripts\register-project.ps1'))-ceq'26779|4AF20EB77DEA77DAD4B7716AAB9C4C6FD79CD6FF271D5475401D8BB541667D74') 'live-register-zero-drift'
Assert-True ((Get-Identity (Join-Path $workspaceRoot 'scripts\upgrade-project.ps1'))-ceq'48922|C3EF6638F0102FB6F2AEF59A6671ADB743DBEB1F2C7BF9EFAB8F2491DACA8181') 'live-upgrade-zero-drift'
foreach($path in @('PERSPECTIVE_LENSES.md','PROJECT_CONFIG_SCHEMA.json','KNOWLEDGE_SCHEMA.json','CONTROLLER_SCHEMA.json','project-starter/.gitattributes','project-starter/RELATIONSHIPS.md','project-starter/tasks/README.md')){Assert-True ((Get-Identity (Join-Path $candidateRoot $path))-ceq(Get-Identity (Join-Path $stableRoot $path))) ("baseline-identical|"+$path)}

$version=Get-Content -LiteralPath (Join-Path $candidateRoot 'VERSION.json') -Raw|ConvertFrom-Json;Assert-True ([string]$version.version-ceq'1.6.1'-and[string]$version.lifecycle-ceq'STABLE'-and[bool]$version.consumable-and[string]$version.baseline-ceq'1.6.0'-and-not[bool]$version.currentEligible-and[bool]$version.projectPinEligible) 'version-stable-consumable'
$load=(& $loader -Role CONTROLLER -Profile CRITICAL -Phase @('RECOVER','PLAN') -HostName CODEX -AsJson|Out-String)|ConvertFrom-Json;Assert-True ([string]$load.frameworkVersion-ceq'1.6.1'-and[string]$load.lifecycle-ceq'STABLE') 'loader-stable-version'
$loadKnowledge=(& $loader -Role CONTROLLER -Profile CRITICAL -Phase @('RECOVER','PLAN') -HostName CODEX -Capability KNOWLEDGE_REFERENCE -AsJson|Out-String)|ConvertFrom-Json;Assert-True (@($loadKnowledge.modules|Where-Object{$_.path-ceq'KNOWLEDGE_AND_REFERENCE.md'}).Count-eq1-and@($loadKnowledge.capabilities).Count-eq1) 'loader-knowledge-topology-unchanged'

$temp=Join-Path ([IO.Path]::GetTempPath()) ('aiw-161-tests-'+[Guid]::NewGuid().ToString('N'))
try{
    New-Item -ItemType Directory -Path $temp|Out-Null
    $knowledgeRoot=Join-Path $temp 'knowledge-project';$control=Join-Path $knowledgeRoot '.ai-workspace';$entryRoot=Join-Path $control 'knowledge\entries';$authorityRoot=Join-Path $knowledgeRoot 'docs';New-Item -ItemType Directory -Path $entryRoot,$authorityRoot -Force|Out-Null
    $config=[ordered]@{schemaVersion=3;id='knowledge-project';displayName='Knowledge Project';controlPlaneLayout='repo-local';repositoryRoot='..';frameworkVersion='1.6.1';routineExcludedPaths=@();frameworkCapabilities=[pscustomobject]@{KNOWLEDGE_REFERENCE=[pscustomobject]@{enabled=$true;indexLocator='.ai-workspace/knowledge/index.json'}}};$configPath=Join-Path $control 'project.json';Write-Utf8 $configPath ($config|ConvertTo-Json -Depth 20)
    $entries=@();foreach($id in @('D','B','A','C')){$reference=Join-Path $entryRoot ($id+'.md');$authority=Join-Path $authorityRoot ($id+'.md');Write-Utf8 $reference ("reference "+$id);Write-Utf8 $authority ("authority "+$id);$item=New-Entry $id 'CURRENT' $reference $authority;$item.locator='.ai-workspace/knowledge/entries/'+$id+'.md';$item.authorityLocator='docs/'+$id+'.md';$entries+=[pscustomobject]$item}
    $historical=New-Entry 'H' 'HISTORICAL' 'missing/h.md' 'missing/authority-h.md';$historical.locator='missing/h.md';$historical.authorityLocator='missing/authority-h.md';$entries+=[pscustomobject]$historical
    $index=[ordered]@{schemaVersion=1;projectId='knowledge-project';entries=$entries};$indexPath=Join-Path $control 'knowledge\index.json';Write-Utf8 $indexPath ($index|ConvertTo-Json -Depth 20);$configIdentity=Get-Identity $configPath;$indexIdentity=Get-Identity $indexPath
    $default=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity;Assert-True ($default.Code-eq0-and($default.Text|ConvertFrom-Json).entries.id-join','-ceq'A,B,C') 'knowledge-default-first-three-compatible'
    $single=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue 'C';Assert-True ($single.Code-eq0-and($single.Text|ConvertFrom-Json).entries.id-join','-ceq'C') 'knowledge-entry-id-single'
    $triple=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue ([object[]]@('D','A','C'));Assert-True ($triple.Code-eq0-and($triple.Text|ConvertFrom-Json).entries.id-join','-ceq'A,C,D') 'knowledge-entry-id-three-stable-order'
    $duplicate=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue ([object[]]@('A','A'));Assert-True ($duplicate.Code-ne0-and$duplicate.Text.Contains('ENTRY_ID_DUPLICATE')) 'knowledge-entry-id-duplicate-rejected'
    $unknown=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue 'Z';Assert-True ($unknown.Code-ne0-and$unknown.Text.Contains('ENTRY_ID_NOT_CURRENT')) 'knowledge-entry-id-unknown-rejected'
    $nonCurrent=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue 'H';Assert-True ($nonCurrent.Code-ne0-and$nonCurrent.Text.Contains('ENTRY_ID_NOT_CURRENT')) 'knowledge-entry-id-noncurrent-rejected'
    $invalid=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue 'bad/id';Assert-True ($invalid.Code-ne0-and$invalid.Text.Contains('ENTRY_ID_INVALID')) 'knowledge-entry-id-invalid-rejected'
    $emptyArray=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue ([object[]]@());Assert-True ($emptyArray.Code-ne0-and$emptyArray.Text.Contains('ENTRY_ID_EMPTY')) 'knowledge-entry-id-explicit-empty-array-rejected'
    $explicitNull=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue $null;Assert-True ($explicitNull.Code-ne0-and$explicitNull.Text.Contains('ENTRY_ID_EMPTY')) 'knowledge-entry-id-explicit-null-rejected'
    $numeric=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue 7;Assert-True ($numeric.Code-ne0-and$numeric.Text.Contains('ENTRY_ID_TYPE')) 'knowledge-entry-id-number-rejected-before-string-conversion'
    $character=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue ([char]'A');Assert-True ($character.Code-ne0-and$character.Text.Contains('ENTRY_ID_TYPE')) 'knowledge-entry-id-char-rejected-before-string-conversion'
    $mixed=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue ([object[]]@('A',7));Assert-True ($mixed.Code-ne0-and$mixed.Text.Contains('ENTRY_ID_TYPE')) 'knowledge-entry-id-mixed-types-rejected-before-string-conversion'
    $tooMany=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue ([object[]]@('A','B','C','D'));Assert-True ($tooMany.Code-ne0-and$tooMany.Text.Contains('ENTRY_ID_LIMIT')) 'knowledge-entry-id-limit-rejected'
    Write-Utf8 (Join-Path $entryRoot 'B.md') 'drifted unselected reference';$unselectedDrift=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue 'A';Assert-True ($unselectedDrift.Code-ne0-and$unselectedDrift.Text.Contains('ENTRY_IDENTITY_DRIFT|B')) 'knowledge-unselected-current-drift-still-fails'
    $invalidWithUnselectedDrift=Invoke-Knowledge $knowledgeChecker $knowledgeRoot $configIdentity $indexIdentity -BindEntryId -EntryIdValue 7;Assert-True ($invalidWithUnselectedDrift.Code-ne0-and$invalidWithUnselectedDrift.Text.Contains('ENTRY_IDENTITY_DRIFT|B')) 'knowledge-full-index-validates-before-entry-id-type'

    $authRoot=Join-Path $temp 'auth';New-Item -ItemType Directory -Path $authRoot|Out-Null;$package=[ordered]@{schemaVersion=1;frameworkVersion='1.6.1';taskId='T';profile='STANDARD';lifecycle='ACTIVE';owner='owner';issuer='owner';issuerRole='DOMAIN_OWNER';grantee='worker';bundle='IMPLEMENT_LOCAL';decisionClass='ROUTINE_LOCAL';userConfirmation='NOT_REQUIRED';reviewIndependence='NOT_APPLICABLE';delegatedGitCloser=$false;actions=@('SOURCE_WRITE');exactPaths=@('src/a.js');objectIdentities=@([ordered]@{path='src/a.js';identity='NEW'});invalidatesOn=@('TASK_CHANGE','OWNER_CHANGE','GRANTEE_CHANGE','ACTION_CHANGE','PATHSET_CHANGE','OBJECT_DRIFT','USER_DECISION_CHANGE')};$packagePath=Join-Path $authRoot 'auth.json';Write-Utf8 $packagePath ($package|ConvertTo-Json -Depth 10);$authorization=Invoke-Ps $auth @('-PackagePath',$packagePath,'-ObservedActor','worker','-ObservedTaskId','T','-ObservedOwner','owner','-ObservedAction','SOURCE_WRITE','-ObservedPath','src/a.js','-ObservedIdentity','src/a.js=NEW') $authRoot;Assert-True ($authorization.Code-eq0) 'authorization-1.6.1-version-projection'

    $stableRegression=Invoke-Ps (Join-Path $stableRoot 'tests\run-framework-tests.ps1') @('-SkipRootMigration');Assert-True ($stableRegression.Code-eq0-and$stableRegression.Text.Contains('RESULT')) 'stable-1.6.0-payload-regression-without-root-migration'

    if(-not$SkipRootMigration){
        $root161Ready=(Get-Content -LiteralPath $register -Raw -Encoding utf8).Contains('1.6.1')-and(Get-Content -LiteralPath $upgrade -Raw -Encoding utf8).Contains('1.6.1')
        if($root161Ready){
        $ws=New-IsolatedWorkspace $temp $candidateRoot $frameworkRoot
        foreach($source in @('1.4.1','1.5.0','1.5.1','1.5.2')){
            $oldId='candidate-old-'+$source.Replace('.','-');$oldRepo=Join-Path $temp $oldId;New-GitRepo $oldRepo;$oldRegistered=Register-Project $register $ws $oldRepo $oldId $source '';Assert-True ($oldRegistered.Code-eq0) ("candidate-root-old-source-register|"+$source)
            $oldBootstrapPath=Join-Path $oldRepo '.ai-workspace\BOOTSTRAP.md';$oldBootstrap=Get-Content -LiteralPath $oldBootstrapPath -Raw -Encoding utf8;$oldBootstrap=$oldBootstrap.Replace('<!-- PROJECT-CUSTOM:END -->',("candidate-root-kept-"+$source+"`n<!-- PROJECT-CUSTOM:END -->"));Write-Utf8 $oldBootstrapPath $oldBootstrap;$oldCustomBefore=[regex]::Match($oldBootstrap,'(?s)<!-- PROJECT-CUSTOM:BEGIN -->.*?<!-- PROJECT-CUSTOM:END -->').Value
            $oldMigration=New-Migration $oldRepo $oldId @('scope/excluded.txt');$oldUpgradeArgs=@('-ProjectId',$oldId,'-RepositoryPath',$oldRepo,'-ToVersion','1.6.0','-ControllerId',('controller-'+$oldId),'-RoutineExcludedPathsMigrationPath',$oldMigration.Path,'-ExpectedRoutineExcludedPathsMigrationIdentity',$oldMigration.Identity,'-WorkspaceRoot',$ws)
            $oldPreview=Invoke-Ps $upgrade $oldUpgradeArgs;Assert-True ($oldPreview.Code-eq0-and$oldPreview.Text.Contains('WHAT_IF')) ("candidate-root-old-to-1.6.0-preview|"+$source)
            $oldApply=Invoke-Ps $upgrade ($oldUpgradeArgs+@('-Apply'));$oldProjectPath=Join-Path $oldRepo '.ai-workspace\project.json';$oldConfig=Get-Content -LiteralPath $oldProjectPath -Raw -Encoding utf8|ConvertFrom-Json;$oldControllerPath=Join-Path $oldRepo '.ai-workspace\controller.json';$oldController=Get-Content -LiteralPath $oldControllerPath -Raw -Encoding utf8|ConvertFrom-Json;$oldCustomAfter=[regex]::Match((Get-Content -LiteralPath $oldBootstrapPath -Raw -Encoding utf8),'(?s)<!-- PROJECT-CUSTOM:BEGIN -->.*?<!-- PROJECT-CUSTOM:END -->').Value;$oldRecovery=@(Get-ChildItem -LiteralPath (Join-Path $oldRepo '.ai-workspace') -Directory -Filter '.framework-upgrade-recovery-*')
            Assert-True ($oldApply.Code-eq0-and[int]$oldConfig.schemaVersion-eq3-and[string]$oldConfig.frameworkVersion-ceq'1.6.0'-and@($oldConfig.routineExcludedPaths).Count-eq1-and[string]$oldConfig.routineExcludedPaths[0]-ceq'scope/excluded.txt'-and@($oldConfig.frameworkCapabilities.PSObject.Properties).Count-eq0-and[string]$oldController.controllerId-ceq('controller-'+$oldId)-and$oldCustomAfter-ceq$oldCustomBefore-and$oldRecovery.Count-eq1) ("candidate-root-old-to-1.6.0-exact3|"+$source)
            $oldRepeat=Invoke-Ps $upgrade ($oldUpgradeArgs+@('-Apply'));Assert-True ($oldRepeat.Code-eq0-and$oldRepeat.Text.Contains('ALREADY_UPGRADED')) ("candidate-root-old-to-1.6.0-repeat|"+$source)
            if($source-ceq'1.5.2'){
                $createActive=Join-Path $oldRepo '.ai-workspace\.framework-upgrade-transaction';$createRecoveryPath=$oldRecovery[0].FullName;[IO.Directory]::Move($createRecoveryPath,$createActive);Set-RecoveryLiveState $createActive $oldProjectPath $oldBootstrapPath $oldControllerPath 'NEW';$createProjectBefore=Get-Identity $oldProjectPath;$createBootstrapBefore=Get-Identity $oldBootstrapPath;$createControllerBefore=Get-Identity $oldControllerPath
                $createPreview=Invoke-Ps $upgrade $oldUpgradeArgs;Assert-True ($createPreview.Code-eq0-and$createPreview.Text.Contains('RECOVERY_REQUIRED')-and(Get-Identity $oldProjectPath)-ceq$createProjectBefore-and(Get-Identity $oldBootstrapPath)-ceq$createBootstrapBefore-and(Get-Identity $oldControllerPath)-ceq$createControllerBefore-and(Test-Path -LiteralPath $createActive -PathType Container)) 'recovery-v2-create-preview-validates-without-mutation'
                $createMismatch=Invoke-Ps $upgrade @('-ProjectId',$oldId,'-RepositoryPath',$oldRepo,'-ToVersion','1.5.2','-ControllerId',('controller-'+$oldId),'-WorkspaceRoot',$ws,'-Apply');Assert-True ($createMismatch.Code-ne0-and$createMismatch.Text.Contains('Requested target does not match')-and(Get-Identity $oldProjectPath)-ceq$createProjectBefore-and(Get-Identity $oldBootstrapPath)-ceq$createBootstrapBefore-and(Get-Identity $oldControllerPath)-ceq$createControllerBefore-and(Test-Path -LiteralPath $createActive -PathType Container)) 'recovery-v2-create-target-mismatch-preserves-active'
                $createStatePath=Join-Path $createActive 'state.json';$createStateRaw=Get-Content -LiteralPath $createStatePath -Raw -Encoding utf8;$unsupportedState=$createStateRaw|ConvertFrom-Json;$unsupportedState.toVersion='1.6.1';Write-Utf8 $createStatePath ($unsupportedState|ConvertTo-Json -Depth 10);$unsupportedRecovery=Invoke-Ps $upgrade @('-ProjectId',$oldId,'-RepositoryPath',$oldRepo,'-ToVersion','1.6.1','-ControllerId',('controller-'+$oldId),'-WorkspaceRoot',$ws,'-Apply');$unsupportedOk=$unsupportedRecovery.Code-ne0-and$unsupportedRecovery.Text.Contains('Unsupported upgrade recovery matrix combination')-and(Get-Identity $oldProjectPath)-ceq$createProjectBefore-and(Get-Identity $oldBootstrapPath)-ceq$createBootstrapBefore-and(Get-Identity $oldControllerPath)-ceq$createControllerBefore-and(Test-Path -LiteralPath $createActive -PathType Container);Write-Utf8 $createStatePath $createStateRaw;Assert-True $unsupportedOk 'recovery-v2-unsupported-matrix-preserves-active'
                $activePrep=Join-Path $oldRepo '.ai-workspace\.fwu-prep-manual';Write-Utf8 (Join-Path $activePrep 'sentinel.txt') 'preserve active plus prep';$activePrepResult=Invoke-Ps $upgrade ($oldUpgradeArgs+@('-Apply'));Assert-True ($activePrepResult.Code-ne0-and$activePrepResult.Text.Contains('Abandoned upgrade preparation exists')-and(Test-Path -LiteralPath $createActive -PathType Container)-and(Test-Path -LiteralPath (Join-Path $activePrep 'sentinel.txt') -PathType Leaf)-and(Get-Identity $oldProjectPath)-ceq$createProjectBefore-and(Get-Identity $oldBootstrapPath)-ceq$createBootstrapBefore-and(Get-Identity $oldControllerPath)-ceq$createControllerBefore) 'recovery-v2-active-plus-prep-preserved';Remove-Item -LiteralPath $activePrep -Recurse -Force
                $createNew=Invoke-Ps $upgrade ($oldUpgradeArgs+@('-Apply'));Assert-True ($createNew.Code-eq0-and$createNew.Text.Contains('RECOVERED_COMMIT')-and-not(Test-Path -LiteralPath $createActive)-and(Test-Path -LiteralPath $createRecoveryPath -PathType Container)) 'recovery-v2-create-new-commit'
                [IO.Directory]::Move($createRecoveryPath,$createActive);Set-RecoveryLiveState $createActive $oldProjectPath $oldBootstrapPath $oldControllerPath 'OLD';$createOld=Invoke-Ps $upgrade ($oldUpgradeArgs+@('-Apply'));$createOldConfig=Get-Content -LiteralPath $oldProjectPath -Raw -Encoding utf8|ConvertFrom-Json;Assert-True ($createOld.Code-eq0-and$createOld.Text.Contains('RECOVERED_ROLLBACK')-and[string]$createOldConfig.frameworkVersion-ceq'1.5.2'-and-not(Test-Path -LiteralPath $oldControllerPath)-and-not(Test-Path -LiteralPath $createActive)) 'recovery-v2-create-old-rollback'
                [IO.Directory]::Move($createRecoveryPath,$createActive);Set-RecoveryLiveState $createActive $oldProjectPath $oldBootstrapPath $oldControllerPath 'MIXED';$createMixed=Invoke-Ps $upgrade ($oldUpgradeArgs+@('-Apply'));$createMixedConfig=Get-Content -LiteralPath $oldProjectPath -Raw -Encoding utf8|ConvertFrom-Json;Assert-True ($createMixed.Code-eq0-and$createMixed.Text.Contains('RECOVERED_ROLLBACK')-and[string]$createMixedConfig.frameworkVersion-ceq'1.5.2'-and-not(Test-Path -LiteralPath $oldControllerPath)-and-not(Test-Path -LiteralPath $createActive)) 'recovery-v2-create-mixed-rollback'
                $prepOnly=Join-Path $oldRepo '.ai-workspace\.fwu-prep-manual';Write-Utf8 (Join-Path $prepOnly 'sentinel.txt') 'preserve prep only';$prepProjectBefore=Get-Identity $oldProjectPath;$prepBootstrapBefore=Get-Identity $oldBootstrapPath;$prepOnlyResult=Invoke-Ps $upgrade ($oldUpgradeArgs+@('-Apply'));Assert-True ($prepOnlyResult.Code-ne0-and$prepOnlyResult.Text.Contains('Abandoned upgrade preparation exists')-and(Test-Path -LiteralPath (Join-Path $prepOnly 'sentinel.txt') -PathType Leaf)-and-not(Test-Path -LiteralPath $createActive)-and(Get-Identity $oldProjectPath)-ceq$prepProjectBefore-and(Get-Identity $oldBootstrapPath)-ceq$prepBootstrapBefore) 'recovery-v2-prep-only-preserved';Remove-Item -LiteralPath $prepOnly -Recurse -Force
            }
        }
        $repoRegister=Join-Path $temp 'register-161';New-GitRepo $repoRegister;$registered=Register-Project $register $ws $repoRegister 'register-161' '1.6.1' 'controller-register';$registeredConfig=Get-Content -LiteralPath (Join-Path $repoRegister '.ai-workspace\project.json') -Raw|ConvertFrom-Json;Assert-True ($registered.Code-eq0-and[int]$registeredConfig.schemaVersion-eq3-and[string]$registeredConfig.frameworkVersion-ceq'1.6.1'-and(Test-Path -LiteralPath (Join-Path $repoRegister '.ai-workspace\controller.json'))-and-not(Test-Path -LiteralPath (Join-Path $repoRegister '.ai-workspace\knowledge'))) 'register-1.6.1-schema3-default-off'
        $registeredRepeat=Register-Project $register $ws $repoRegister 'register-161' '1.6.1' 'controller-register';Assert-True ($registeredRepeat.Code-eq0-and$registeredRepeat.Text.Contains('ALREADY_REGISTERED')) 'register-1.6.1-repeat-health'

        $repoUpgrade=Join-Path $temp 'upgrade-160';New-GitRepo $repoUpgrade;$registered160=Register-Project $register $ws $repoUpgrade 'upgrade-160' '1.6.0' 'controller-upgrade';$projectPath=Join-Path $repoUpgrade '.ai-workspace\project.json';$bootstrapPath=Join-Path $repoUpgrade '.ai-workspace\BOOTSTRAP.md';$controllerPath=Join-Path $repoUpgrade '.ai-workspace\controller.json';$controllerBefore=Get-Identity $controllerPath;$bootstrap160=Get-Content -LiteralPath $bootstrapPath -Raw -Encoding utf8;$bootstrap160=$bootstrap160.Replace('<!-- PROJECT-CUSTOM:END -->',"custom-161-preserved`n<!-- PROJECT-CUSTOM:END -->");Write-Utf8 $bootstrapPath $bootstrap160;$customBefore=[regex]::Match($bootstrap160,'(?s)<!-- PROJECT-CUSTOM:BEGIN -->.*?<!-- PROJECT-CUSTOM:END -->').Value;$config160=Get-Content -LiteralPath $projectPath -Raw|ConvertFrom-Json;$config160.frameworkCapabilities=[pscustomobject]@{KNOWLEDGE_REFERENCE=[pscustomobject]@{enabled=$true;indexLocator='.ai-workspace/knowledge/index.json'}};Write-Utf8 $projectPath ($config160|ConvertTo-Json -Depth 20);$config160Raw=Get-Content -LiteralPath $projectPath -Raw -Encoding utf8;$capabilitiesBefore=$config160Raw.Substring($config160Raw.IndexOf('  "frameworkCapabilities":'))
        $upgradeArgs=@('-ProjectId','upgrade-160','-RepositoryPath',$repoUpgrade,'-ToVersion','1.6.1','-ControllerId','controller-upgrade','-WorkspaceRoot',$ws);$preview=Invoke-Ps $upgrade $upgradeArgs;$apply=Invoke-Ps $upgrade ($upgradeArgs+@('-Apply'));$config161Raw=Get-Content -LiteralPath $projectPath -Raw -Encoding utf8;$config161=$config161Raw|ConvertFrom-Json;$capabilitiesAfter=$config161Raw.Substring($config161Raw.IndexOf('  "frameworkCapabilities":'));$customAfter=[regex]::Match((Get-Content -LiteralPath $bootstrapPath -Raw -Encoding utf8),'(?s)<!-- PROJECT-CUSTOM:BEGIN -->.*?<!-- PROJECT-CUSTOM:END -->').Value;$recovery=@(Get-ChildItem -LiteralPath (Join-Path $repoUpgrade '.ai-workspace') -Directory -Filter '.framework-upgrade-recovery-*');$upgradeOk=$registered160.Code-eq0-and$preview.Code-eq0-and$apply.Code-eq0-and[int]$config161.schemaVersion-eq3-and[string]$config161.frameworkVersion-ceq'1.6.1'-and(@($config161.frameworkCapabilities.PSObject.Properties.Name)-contains'KNOWLEDGE_REFERENCE')-and$capabilitiesAfter-ceq$capabilitiesBefore-and(Get-Identity $controllerPath)-ceq$controllerBefore-and$customAfter-ceq$customBefore-and$recovery.Count-eq1;if(-not$upgradeOk){Write-Output ('DIAG|preview='+$preview.Code+'|'+$preview.Text);Write-Output ('DIAG|apply='+$apply.Code+'|'+$apply.Text);Write-Output ('DIAG|registered='+$registered160.Code+'|schema='+[int]$config161.schemaVersion+'|version='+[string]$config161.frameworkVersion+'|capability='+(@($config161.frameworkCapabilities.PSObject.Properties.Name)-contains'KNOWLEDGE_REFERENCE')+'|capabilitiesExact='+($capabilitiesAfter-ceq$capabilitiesBefore)+'|controllerExact='+((Get-Identity $controllerPath)-ceq$controllerBefore)+'|customExact='+($customAfter-ceq$customBefore)+'|recovery='+$recovery.Count)};Assert-True $upgradeOk 'upgrade-1.6.0-to-1.6.1-two-object-preserves-controller-capabilities-custom'
        $repeat=Invoke-Ps $upgrade ($upgradeArgs+@('-Apply'));Assert-True ($repeat.Code-eq0-and$repeat.Text.Contains('Already on requested version')) 'upgrade-1.6.1-repeat-health'

        $activeTransaction=Join-Path $repoUpgrade '.ai-workspace\.framework-upgrade-transaction';$noneRecoveryPath=$recovery[0].FullName;[IO.Directory]::Move($noneRecoveryPath,$activeTransaction);Set-RecoveryLiveState $activeTransaction $projectPath $bootstrapPath $controllerPath 'MIXED';$recoveryProjectBefore=Get-Identity $projectPath;$recoveryBootstrapBefore=Get-Identity $bootstrapPath;$recoveryArgs=@('-ProjectId','upgrade-160','-RepositoryPath',$repoUpgrade,'-ToVersion','1.6.1','-WorkspaceRoot',$ws,'-Apply')
        $nonePreview=Invoke-Ps $upgrade @('-ProjectId','upgrade-160','-RepositoryPath',$repoUpgrade,'-ToVersion','1.6.1','-ControllerId','controller-upgrade','-WorkspaceRoot',$ws);Assert-True ($nonePreview.Code-eq0-and$nonePreview.Text.Contains('RECOVERY_REQUIRED')-and(Get-Identity $projectPath)-ceq$recoveryProjectBefore-and(Get-Identity $bootstrapPath)-ceq$recoveryBootstrapBefore-and(Test-Path -LiteralPath $activeTransaction -PathType Container)) 'recovery-v2-none-preview-validates-without-mutation'
        $noneMismatch=Invoke-Ps $upgrade @('-ProjectId','upgrade-160','-RepositoryPath',$repoUpgrade,'-ToVersion','1.5.2','-ControllerId','controller-upgrade','-WorkspaceRoot',$ws,'-Apply');Assert-True ($noneMismatch.Code-ne0-and$noneMismatch.Text.Contains('Requested target does not match')-and(Get-Identity $projectPath)-ceq$recoveryProjectBefore-and(Get-Identity $bootstrapPath)-ceq$recoveryBootstrapBefore-and(Test-Path -LiteralPath $activeTransaction -PathType Container)) 'recovery-v2-none-target-mismatch-preserves-active'
        $omittedRecovery=Invoke-Ps $upgrade $recoveryArgs;Assert-True ($omittedRecovery.Code-ne0-and$omittedRecovery.Text.Contains('ControllerId is required for Framework 1.6.0 to 1.6.1 transaction recovery')-and(Get-Identity $projectPath)-ceq$recoveryProjectBefore-and(Get-Identity $bootstrapPath)-ceq$recoveryBootstrapBefore-and(Test-Path -LiteralPath $activeTransaction -PathType Container)) 'upgrade-1.6.1-recovery-omitted-controller-id-no-mutation'
        $wrongRecovery=Invoke-Ps $upgrade ($recoveryArgs+@('-ControllerId','wrong-controller'));Assert-True ($wrongRecovery.Code-ne0-and$wrongRecovery.Text.Contains('controller.json values are invalid')-and(Get-Identity $projectPath)-ceq$recoveryProjectBefore-and(Get-Identity $bootstrapPath)-ceq$recoveryBootstrapBefore-and(Test-Path -LiteralPath $activeTransaction -PathType Container)) 'upgrade-1.6.1-recovery-wrong-controller-id-no-mutation'
        $controllerRawBefore=Get-Content -LiteralPath $controllerPath -Raw -Encoding utf8;[IO.File]::Delete($controllerPath);$missingRecovery=Invoke-Ps $upgrade ($recoveryArgs+@('-ControllerId','controller-upgrade'));$missingRecoveryOk=$missingRecovery.Code-ne0-and$missingRecovery.Text.Contains('Schema3 patch recovery controller.json is missing')-and(Get-Identity $projectPath)-ceq$recoveryProjectBefore-and(Get-Identity $bootstrapPath)-ceq$recoveryBootstrapBefore-and(Test-Path -LiteralPath $activeTransaction -PathType Container);Write-Utf8 $controllerPath $controllerRawBefore;Assert-True $missingRecoveryOk 'upgrade-1.6.1-recovery-missing-controller-no-mutation'
        $driftedController=$controllerRawBefore|ConvertFrom-Json;$driftedController.state='STALE';Write-Utf8 $controllerPath ($driftedController|ConvertTo-Json -Depth 10);$driftedRecovery=Invoke-Ps $upgrade ($recoveryArgs+@('-ControllerId','controller-upgrade'));$driftedRecoveryOk=$driftedRecovery.Code-ne0-and$driftedRecovery.Text.Contains('controller.json values are invalid')-and(Get-Identity $projectPath)-ceq$recoveryProjectBefore-and(Get-Identity $bootstrapPath)-ceq$recoveryBootstrapBefore-and(Test-Path -LiteralPath $activeTransaction -PathType Container);Write-Utf8 $controllerPath $controllerRawBefore;Assert-True $driftedRecoveryOk 'upgrade-1.6.1-recovery-drifted-controller-no-mutation'
        $recover=Invoke-Ps $upgrade ($recoveryArgs+@('-ControllerId','controller-upgrade'));$rolledBack=Get-Content -LiteralPath $projectPath -Raw|ConvertFrom-Json;Assert-True ($recover.Code-eq0-and$recover.Text.Contains('Recovered previous Framework upgrade transaction')-and[string]$rolledBack.frameworkVersion-ceq'1.6.0'-and(Get-Identity $controllerPath)-ceq$controllerBefore-and-not(Test-Path -LiteralPath $activeTransaction)) 'upgrade-1.6.1-mixed-state-recovery-rollback'
        $commitProjectBefore=Get-Identity $projectPath;$commitBootstrapBefore=Get-Identity $bootstrapPath;$commitControllerBefore=Get-Identity $controllerPath;$bootstrapAttributes=[IO.File]::GetAttributes($bootstrapPath);[IO.File]::SetAttributes($bootstrapPath,($bootstrapAttributes-bor[IO.FileAttributes]::ReadOnly));try{$commitCatch=Invoke-Ps $upgrade ($upgradeArgs+@('-Apply'))}finally{[IO.File]::SetAttributes($bootstrapPath,$bootstrapAttributes)};$commitRecovery=@(Get-ChildItem -LiteralPath (Join-Path $repoUpgrade '.ai-workspace') -Directory -Filter '.framework-upgrade-recovery-*');Assert-True ($commitCatch.Code-ne0-and$commitCatch.Text.Contains('Upgrade failed and was rolled back')-and(Get-Identity $projectPath)-ceq$commitProjectBefore-and(Get-Identity $bootstrapPath)-ceq$commitBootstrapBefore-and(Get-Identity $controllerPath)-ceq$commitControllerBefore-and-not(Test-Path -LiteralPath $activeTransaction)-and$commitRecovery.Count-ge2) 'recovery-v2-commit-catch-rolls-back-through-single-gate'
        [IO.Directory]::Move($noneRecoveryPath,$activeTransaction);Set-RecoveryLiveState $activeTransaction $projectPath $bootstrapPath $controllerPath 'OLD';$noneOld=Invoke-Ps $upgrade ($recoveryArgs+@('-ControllerId','controller-upgrade'));$noneOldConfig=Get-Content -LiteralPath $projectPath -Raw -Encoding utf8|ConvertFrom-Json;Assert-True ($noneOld.Code-eq0-and$noneOld.Text.Contains('RECOVERED_ROLLBACK')-and[string]$noneOldConfig.frameworkVersion-ceq'1.6.0'-and-not(Test-Path -LiteralPath $activeTransaction)) 'recovery-v2-none-old-rollback'
        [IO.Directory]::Move($noneRecoveryPath,$activeTransaction);Set-RecoveryLiveState $activeTransaction $projectPath $bootstrapPath $controllerPath 'NEW';$noneNew=Invoke-Ps $upgrade ($recoveryArgs+@('-ControllerId','controller-upgrade'));$noneNewConfig=Get-Content -LiteralPath $projectPath -Raw -Encoding utf8|ConvertFrom-Json;Assert-True ($noneNew.Code-eq0-and$noneNew.Text.Contains('RECOVERED_COMMIT')-and[string]$noneNewConfig.frameworkVersion-ceq'1.6.1'-and-not(Test-Path -LiteralPath $activeTransaction)) 'recovery-v2-none-new-commit'

        $genericRepo=Join-Path $temp 'generic-none';New-GitRepo $genericRepo;$genericRegistered=Register-Project $register $ws $genericRepo 'generic-none' '1.4.1' '';$genericArgs=@('-ProjectId','generic-none','-RepositoryPath',$genericRepo,'-ToVersion','1.5.2','-WorkspaceRoot',$ws);$genericApply=Invoke-Ps $upgrade ($genericArgs+@('-Apply'));$genericProject=Join-Path $genericRepo '.ai-workspace\project.json';$genericBootstrap=Join-Path $genericRepo '.ai-workspace\BOOTSTRAP.md';$genericController=Join-Path $genericRepo '.ai-workspace\controller.json';$genericConfig=Get-Content -LiteralPath $genericProject -Raw -Encoding utf8|ConvertFrom-Json;$genericRecovery=@(Get-ChildItem -LiteralPath (Join-Path $genericRepo '.ai-workspace') -Directory -Filter '.framework-upgrade-recovery-*');Assert-True ($genericRegistered.Code-eq0-and$genericApply.Code-eq0-and[string]$genericConfig.frameworkVersion-ceq'1.5.2'-and$genericRecovery.Count-eq1-and-not(Test-Path -LiteralPath $genericController)) 'recovery-v2-old-generic-none-setup'
        $genericActive=Join-Path $genericRepo '.ai-workspace\.framework-upgrade-transaction';$genericRecoveryPath=$genericRecovery[0].FullName;[IO.Directory]::Move($genericRecoveryPath,$genericActive);Set-RecoveryLiveState $genericActive $genericProject $genericBootstrap $genericController 'MIXED';$genericProjectBefore=Get-Identity $genericProject;$genericBootstrapBefore=Get-Identity $genericBootstrap;$genericPreview=Invoke-Ps $upgrade $genericArgs;Assert-True ($genericPreview.Code-eq0-and$genericPreview.Text.Contains('RECOVERY_REQUIRED')-and(Get-Identity $genericProject)-ceq$genericProjectBefore-and(Get-Identity $genericBootstrap)-ceq$genericBootstrapBefore-and(Test-Path -LiteralPath $genericActive -PathType Container)) 'recovery-v2-old-generic-none-preview'
        $genericRecover=Invoke-Ps $upgrade ($genericArgs+@('-Apply'));$genericRecoveredConfig=Get-Content -LiteralPath $genericProject -Raw -Encoding utf8|ConvertFrom-Json;Assert-True ($genericRecover.Code-eq0-and$genericRecover.Text.Contains('RECOVERED_ROLLBACK')-and[string]$genericRecoveredConfig.frameworkVersion-ceq'1.4.1'-and-not(Test-Path -LiteralPath $genericController)-and-not(Test-Path -LiteralPath $genericActive)) 'recovery-v2-old-generic-none-recovery'

        $repoOld=Join-Path $temp 'old-direct';New-GitRepo $repoOld;$oldRegistered=Register-Project $register $ws $repoOld 'old-direct' '1.5.2' '';$oldDirect=Invoke-Ps $upgrade @('-ProjectId','old-direct','-RepositoryPath',$repoOld,'-ToVersion','1.6.1','-ControllerId','controller-old','-WorkspaceRoot',$ws,'-Apply');$oldRejectOk=$oldRegistered.Code-eq0-and$oldDirect.Code-ne0-and$oldDirect.Text.Contains('direct upgrade requires a healthy schema3')-and-not(Test-Path -LiteralPath (Join-Path $repoOld '.ai-workspace\controller.json'));if(-not$oldRejectOk){Write-Output ('DIAG|old-register='+$oldRegistered.Code+'|'+$oldRegistered.Text);Write-Output ('DIAG|old-direct='+$oldDirect.Code+'|'+$oldDirect.Text)};Assert-True $oldRejectOk 'upgrade-schema2-direct-to-1.6.1-rejected-no-write'

        Write-Utf8 (Join-Path $repoRegister 'scope\public.txt') 'visible';$configIdentity=Get-Identity (Join-Path $repoRegister '.ai-workspace\project.json');$status=Invoke-Ps $safeGit @('-ProjectRoot',$repoRegister,'-Operation','STATUS','-AllowPath','scope/public.txt','-ExpectedProjectConfigIdentity',$configIdentity);Assert-True ($status.Code-eq0-and$status.Text.Contains('scope/public.txt')) 'safe-git-1.6.1-version-projection'
        }else{
            Assert-True ((Get-Identity $register)-ceq'26779|4AF20EB77DEA77DAD4B7716AAB9C4C6FD79CD6FF271D5475401D8BB541667D74'-and(Get-Identity $upgrade)-ceq'48922|C3EF6638F0102FB6F2AEF59A6671ADB743DBEB1F2C7BF9EFAB8F2491DACA8181') 'root-1.6.1-adoption-separate-gate-live-root-1.6.0-preserved'
        }
    }

    if(-not$SkipManifest){
        $manifest=Get-Content -LiteralPath (Join-Path $candidateRoot 'RELEASE_MANIFEST.json') -Raw|ConvertFrom-Json;[string[]]$payload=@($actual|Where-Object{$_-cne'RELEASE_MANIFEST.json'});[Array]::Sort($payload,[StringComparer]::Ordinal);$rows=@();$total=[int64]0;foreach($path in $payload){$full=Join-Path $candidateRoot $path;$bytes=[IO.File]::ReadAllBytes($full);$total+=$bytes.Length;$rows+=("$path|$($bytes.Length)|"+(Get-Identity $full).Split('|')[1])};$sha=[Security.Cryptography.SHA256]::Create();try{$canonical=([BitConverter]::ToString($sha.ComputeHash($utf8.GetBytes(($rows-join"`n"))))).Replace('-','')}finally{$sha.Dispose()};$manifestOk=[int]$manifest.fileCount-eq$payload.Count-and[int64]$manifest.totalBytes-eq$total-and[string]$manifest.canonical-ceq$canonical;if(-not$manifestOk){Write-Output ('DIAG|manifest|count='+$payload.Count+'|total='+$total+'|canonical='+$canonical)};Assert-True $manifestOk 'release-manifest-canonical'
    }
}
finally{
    if(Test-Path -LiteralPath $temp){Get-ChildItem -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue|ForEach-Object{try{$_.Attributes=[IO.FileAttributes]::Normal}catch{}};Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue}
}

Write-Output ("RESULT|"+$script:passed+"/"+$script:passed+" passed|scope=Framework-1.6.1-stable|lifecycle=STABLE")
